### ISSUE TITLE
Decide on library for N-dimensional arrays

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1017]
With plenty of action on #603 these days, we will be needing a clean way to express N-dimensional arrays in C++ which the language itself doesn't really provide. There are a number of libraries that provide multi-dimensional arrays, including:
- [Boost](https://www.boost.org/doc/libs/1_62_0/libs/multi_array/doc/user.html)
- [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) (intended mostly for 2D only, although they have an experimental N-d array)
- [Armadillo](http://arma.sourceforge.net/) (again, primarily for matrices)
- [DyND](http://libdynd.org/) (doesn't seem very mature or actively developed?)
- [xtensor](https://xtensor.readthedocs.io/en/latest/)
- [kokkos array_ref](https://github.com/kokkos/array_ref)

Looking a little bit at all the options, I'm currently a big fan of xtensor. It has a beautiful, numpy-inspired API that will ease the learning curve for new developers. It is header-only so we should be able to just directly include it in our source tree the same way we handle pugixml. It does require some C++14 features and would require we bump our gcc dependency to 4.9, but I think I'd be willing to live with that. I'm curious to hear others thoughts.

**Comment by smharper** [comment]
I want to push back slightly on a C++14 dependency.  Recently I've been helping a lot of people install OpenMC, and it can be a really brutal process for folks who haven't installed software from source before.  MacOS in particular gets tough if you need a modern GCC (maybe it would be better if we were 100% C++ and could use Clang, but that's a ways off).

Would a Boost dependency still allow us to stick with C++11?  I haven't looked into it a lot, but I remember seeing that Boost also had some string processing tools that might be handy.

**Comment by paulromano** [comment]
I do empathize with you (and poor newcomers). Things will get better when Fortran is gone, for sure. In principle, Clang does have ABI compatibility with gcc so you could mix gfortran and clang++. I haven't tried it yet though.

With the case of xtensor, it requires gcc 4.9 so one version higher than where we are currently. I would think that from the perspective of a MacOS user, that makes no difference since the default gcc on Mac is something ancient (4.2?). If you need a newer compiler, it's the same problem whether it is 4.8 or 4.9.

**Comment by GiudGiud** [comment]
This is meant for tally arrays right ?
Any of those have advantages with regards to shared memory parallelism ? MGXS could use a speed boost on large problems like BEAVRS, so it could be worth it to move some of the work on libraries to C++ and make it parallel. 
Otherwise I'd like to point out that boost and xtensor have Python bindings, which will come in handy, and that xtensor seems a lot easier to install given that you can just get it from conda. 

Would the library be distributed with OpenMC ?

**Comment by paulromano** [comment]
It is really meant for any area of the code where we are dealing with multidimensional arrays, not specifically just tallies. There wouldn't be any performance benefits for shared memory parallelism. Most libraries just provide a nice abstraction for interacting with multidimensional arrays, but under the hood there is just a normal array that is allocated.

My plan would be to distribute the library with OpenMC, the same way we handle pugixml and Faddeeva, so that users don't need to install these components themselves.
