### ISSUE TITLE
Events used to contribute to Zernike filter

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1018]
As @lindsayad discovered the hard way, currently collisions outside of the defined domain for a Zernike polynomial used for a Zernike filter can still contribute to the tally. Effectively, we are fitting polynomials to data that is possibly outside of the defined domain, so I'm going to call that a bug. Fixing should be as easy as only scoring when the normalized radius is <=1.

@lindsayad I'd welcome a PR from you, but if you're too busy I can also fix it myself.

**Comment by hanzhuoran** [comment]
I believe I fixed this in my PR.
