### ISSUE TITLE
ENDF Parsing Blank Space

### ISSUE THREAD

**Issue by icmeyer** [openmc-dev/openmc#1027]
In the ENDF parsing routine there is a function to convert ENDF's odd format to floating point. 
https://github.com/mit-crpg/openmc/blob/499f2f24944435c095d3d69acdd8fea98ddf1edd/openmc/data/endf.py#L71

The issue is that occasionally evaluations produced by SAMMY will contain white space indicating a 0. This is not currently the case for publicly distributed ENDF files but may rear its head in more specific use cases. For performance considerations it may be best to keep it as is, rather than eat the cost of a conditional for checking blank space. Maybe something like:

    try:
        return float(ENDF_FLOAT_RE.sub(r'\1e\2', s))
    except:
        if ENDF_FLOAT_RE.sub(r'\1e\2', s).isspace():
            return 0
        else:
            raise TypeError('Expected float value or blank entry')

**Comment by paulromano** [comment]
Thanks for creating an issue for this @icmeyer. Looking at ENDF-102, here's what they have to say about integers:

> All numbers are given in fields of 11 columns. For fields representing integers, the fields have the following form:
>
> ±nnnnnnnnnn
>
> Here, n is a number between 0-9 or a space character and any leading “+” sign is optional. Therefore, integers are limited to a maximum absolute value of 9,999,999,999. Integers can be read by the FORTRAN77 “I11” format specification.

So, if you read it literally, technically all those `n`s could be spaces. I'm not sure if the intent is for that to be permissible. If you have a field of all blanks that is read by Fortran's I11 format spec, it looks like the Fortran standard does actually say that it's to be interpreted as zero (hence why Fortran-based codes don't choke on this). From section 10.7.2.1 in the F2008 standard:

> On input, leading blanks are not significant. When the input field is not an IEEE exceptional
specification (10.7.2.3.2), the interpretation of blanks, other than leading blanks, is determined by
the blank interpretation mode (10.8.6). Plus signs may be omitted. **A field containing only blanks
is considered to be zero.**

@brown170 Is the intent in ENDF-102 to allow fields of all whitespace to be interpreted as zeros?
