### ISSUE TITLE
XML whitespace issue when compiled with Intel

### ISSUE THREAD

**Issue by cjosey** [openmc-dev/openmc#1038]
When OpenMC is compiled with a newer Intel compiler (17.0.4 and 18.0.2 tested), the XML parser will fail to properly handle whitespace in certain parts of the XML input.

Specifically, upon running ``examples/xml/pincell`` with latest develop, the following error will be shown:
```
Reading settings XML file...
 ERROR: Error converting XML text: 
        -0.62992 -0.62992 -1.
        
        0.62992  0.62992  1.
```
Changing the ``<parameters>`` tag in ``settings.xml`` to:
```
<parameters>-0.62992 -0.62992 -1. 0.62992  0.62992  1.</parameters>
```
Allows the simulation to continue onward.  This issue does not appear when compiled with gcc-8.1.

Other information:
OS: RHEL 7.5
HDF5 version: 1.8.16 compiled in serial (I think)

**Comment by paulromano** [comment]
Looks like a compiler bug to me. I just made a [post on Intel's forum](https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/783872) reporting the behavior. Ironically, I reported almost exactly the [same bug](https://www.pgroup.com/userforum/viewtopic.php?p=21785) to PGI over a year ago. Gotta love Fortran compilers...
