### ISSUE TITLE
C_NONE and MATERIAL_VOID are the same value in C

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#1049]
Could this be a problem?

I'm having trouble defining a cell as void in C and I think these values being the same causes an issue in setup [here](https://github.com/openmc-dev/openmc/blob/0ff0568a10eaa5634fc71f7c78624f2a86b4a570/src/geometry_aux.cpp#L21) in `adjust_indices_c`.

**Comment by paulromano** [comment]
@smharper addressed this in his open PR #1045 -- take a look there.

**Comment by pshriwise** [comment]
Thanks! I'll keep an eye on it and rebase once it's merged.

**Comment by paulromano** [comment]
Closing this with the merging of #1045. If you still are running into problem @pshriwise, feel free to reopen.
