### ISSUE TITLE
 Tally.filters doesn't support inputing multi-dimensional legendre filters as a list

### ISSUE THREAD

**Issue by hanzhuoran** [openmc-dev/openmc#1057]
As @GiudGiud discovered, if we set up FET like `tally.filters = [filter_x, filter_y, filter_z]` and 
`filter_x = openmc.SpatialLegendreFilter(1, 'x', min, max),`
`filter_y = openmc.SpatialLegendreFilter(1, 'y', min, max),`
`filter_z = openmc.SpatialLegendreFilter(1, 'z', min, max)`, we will have an error message about duplicate tallies. 

This is because we only check the type of the filters. All three filters are in the same type, even though they are on different axis.

An ad hoc method is to use `tally.filters.append` to append the filters one by one. Appending on a list does not raise the error checking process.

**Comment by paulromano** [comment]
@hanzhuoran Is this fixed now with #1058 being merged?

**Comment by hanzhuoran** [comment]
This one is fixed.
