### ISSUE TITLE
Checkpointing in OpenMC?

### ISSUE THREAD

**Issue by jasonpfi** [openmc-dev/openmc#1117]
I will need to be check-pointing progress every few hours due to a probable power loss. Is there check-pointing with the application, or is that something I will need to do with a third party app?

**Comment by paulromano** [comment]
Yes, you can tell OpenMC to generate "statepoint" files periodically which can be used to restart a simulation. If you are using the Python API, read [this section](https://openmc.readthedocs.io/en/latest/usersguide/settings.html#generation-of-output-files) of the user's manual. If you are working with XML files directly, you would add a `<state_point>` element in your settings.xml file (see description [here](https://openmc.readthedocs.io/en/latest/io_formats/settings.html#state-point-element)).
