### ISSUE TITLE
Improve documentation on how to use CAD geometries

### ISSUE THREAD

**Issue by D-Benjamin** [openmc-dev/openmc#1123]
Recently, I do a research with OpenMC, and I need to create a complex geometry that OpenMC can not make it. So I wonder if it is possible to use another tool(such as 'CAD') to create a geometry than input to OpenMC? If it is possible, than how?
    Any reply will be appreciated !!

**Comment by pshriwise** [comment]
OpenMC has recently added the capability to use CAD geometries via the [DAGMC](https://svalinn.github.io/DAGMC/) toolkit. Geometries are typically created using a software tool called [Trelis](https://www.csimsoft.com/trelis.jsp), but CAD-based surface mesh geometries from other sources have been used in the past as well. Please let us know if you have any other questions!

**Comment by nmurali2002** [comment]
> OpenMC has recently added the capability to use CAD geometries via the [DAGMC](https://svalinn.github.io/DAGMC/) toolkit. Geometries are typically created using a CAD/meshing software tool called [Trelis](https://www.csimsoft.com/trelis.jsp), but CAD-based surface mesh geometries from other sources have been used in the past as well. Please let us know if you have any other questions!

The DAGMC website doesn't have installation instructions for OpenMC - any help?
Also, this CAD functionality looks awesome - thank you so much for helping to add that capability!

**Comment by D-Benjamin** [comment]
> The DAGMC website doesn't have installation instructions for OpenMC - any help?
> Also, this CAD functionality looks awesome - thank you so much for helping to add that capability!

Sorry, I'm a new to OpenMC! I try to simplify the geometry model  in my later Master's thesis work since the OpenMC can not make it by itself. And I will not study how to use DAGMC in a short time. But thanks for your focus on this problem, and I hope to get your reply if you can make progress in using DAGMG. keep in touch!!

Best Wishes!
D.Benjamin

**Comment by D-Benjamin** [comment]
> I am also keen to use this great feature. It looks like the workflow for this is evolving but there are is some preparation steps that are generic for other DAG codes that you could do in the mean time.
> 
> I guess the first stage would be to acquire a copy of Trelis and install the [DAGMC plugin](https://svalinn.github.io/DAGMC/install/plugin.html).
> 
> Then import your CAD models and tag the geometry with groups that identify the different materials. Not sure if OpenMc going to use the same tag names as DAG e.g "mat:steel" ?
> 
> I guess that the Trelis tagged geometry will then need to be exported as a h5 file and somehow imported to OpenMc.

Thanks for your focus on this problem. I believe it will have great help on me. By the way, I  wonder if the meshing tools(Such as 'ICEM' or 'Gambit') can take place of the 'Trelis'. Thanks a lot

Best Wishes!
D.Benjamin

**Comment by D-Benjamin** [comment]
> > OpenMC has recently added the capability to use CAD geometries via the [DAGMC](https://svalinn.github.io/DAGMC/) toolkit. Geometries are typically created using a CAD/meshing software tool called [Trelis](https://www.csimsoft.com/trelis.jsp), but CAD-based surface mesh geometries from other sources have been used in the past as well. Please let us know if you have any other questions!
> 
> The DAGMC website doesn't have installation instructions for OpenMC - any help?
> Also, this CAD functionality looks awesome - thank you so much for helping to add that capability!

Sorry, I'm a new to OpenMC! I try to simplify the geometry model in my later Master's thesis work since the OpenMC can not make it by itself. And I will not study how to use DAGMC in a short time. But thanks for your focus on this problem, and I hope to get your reply if you can make progress in using DAGMG. keep in touch!!

Best Wishes!
D.Benjamin

**Comment by D-Benjamin** [comment]
> OpenMC has recently added the capability to use CAD geometries via the [DAGMC](https://svalinn.github.io/DAGMC/) toolkit. Geometries are typically created using a CAD/meshing software tool called [Trelis](https://www.csimsoft.com/trelis.jsp), but CAD-based surface mesh geometries from other sources have been used in the past as well. Please let us know if you have any other questions!

Thanks for your focus on this problem. I believe it will have great help on me. By the way, I wonder if the meshing tools(Such as 'ICEM' or 'Gambit') can take place of the 'Trelis'. Thanks a lot

Best Wishes!
D.Benjamin

**Comment by Shimwell** [comment]
Hi D.Benjamin

I think Trellis has a unique feature of allowing merging and imprinting surfaces.

https://svalinn.github.io/DAGMC/usersguide/trelis_basics.html

I guess that is why is was selected and the plugin was created so that it exports h5 geometry. Just to confuse you Trellis is also called Cubit.

I have not used the other meshing packages but I believe Cubit is free in some cases https://cubit.sandia.gov/public/licensing.html

**Comment by pshriwise** [comment]
@D-Benjamin I'll add some documentation on how DAGMC can be enabled when building OpenMC very soon, thanks for bringing it to our attention.

@Shimwell is steering you well. The imprinting and merging capabilities in CUBIT/Trelis are important to providing robust surface mesh geometries to the DAGMC kernel. However, we have generated DAGMC models from non-intersecting, non-coincident surface meshes before and are willing to be guides/aides in that process. If either ICEM or Gambit has imprint and/or merge capabilities then this becomes less onerous :)

**Comment by D-Benjamin** [comment]
> @D-Benjamin I'll add some documentation on how DAGMC can be enabled when building OpenMC very soon, thanks for bringing it to our attention.

@pshriwise 
Hi, pshriwise,
    Have you finished the documentation on how DAGMC can be enabled when building OpenMC?  Recently, I need to create a complex geometry urgently which OpenMC can not make it by itself. Or is there any another way to construct a complex geometry and then simulate by OpenMC?
    Hope to get your reply soon.

Best Wishes!
Benjamin

**Comment by pshriwise** [comment]
@D-Benjamin I’m overdue on that, aren’t I?! Apologies.

At some point I made the decision to wait until I could implement support for our material-laden geometry workflow, called [UWUW](https://svalinn.github.io/DAGMC/usersguide/uw2.html), before writing it all up so I could include information on this as well.

In the meantime, what stage are you at in creating this geometry. Do you have a CAD file you’re working with?

**Comment by D-Benjamin** [comment]
@pshriwise I'd like to create a geometry which is similar to the picture below. OpenMC doesn't have the capability of making complex geometry. Maybe I have to use the method of stacking blocks to complete this work. Anyway, I'm really looking forward to your release of this new capability of OpenMC.

![image](https://user-images.githubusercontent.com/45137022/51293533-68d1e900-1a4a-11e9-9ca6-77cd4af3e13f.png)

**Comment by D-Benjamin** [comment]
> @D-Benjamin I’m overdue on that, aren’t I?! Apologies.
> 
> At some point I made the decision to wait until I could implement support for our material-laden geometry workflow, called [UWUW](https://svalinn.github.io/DAGMC/usersguide/uw2.html), before writing it all up so I could include information on this as well.
> 
> In the meantime, what stage are you at in creating this geometry. Do you have a CAD file you’re working with?

@pshriwise Hi pahriwise, I may find a error in the DAGMC documentation when I install the MOAB. the website is "https://svalinn.github.io/DAGMC/install/dependencies.html". After run following commands, there is a error hint: "configure: error: BLAS library not found"  on the terminate.

`$ ../src/configure --enable-optimize \
                            --enable-shared \
                            --disable-debug \
                            --with-hdf5=$HOME/dagmc_bld/HDF5 \
                            --prefix=$HOME/dagmc_bld/MOAB`

    And when I run command "make", there is a hit: "can not find makefile", And then, stop. I'm sure I had followed the source install route. But I tried installing MOAB-4.6.3, it can works. However, the documentation reminder "As of DAGMC version 3.1, MOAB version 5.1.0 or higher is required". So I hope to get your help, I have struggle for it for a long time. My operating system is Ubuntu16.04LTS. Thanks!

**Comment by pshriwise** [comment]
Hrmmm so MOAB will require either BLAS/ or Eigen3 for its linear algebra needs. Can you check that one of those is installed on your machine? 

You can specify which of the two you’d like to use in the configure command using the `—with-blas` and `—with-eigen3`, respectively.

Let me know if that helps!

**Comment by D-Benjamin** [comment]
> @D-Benjamin I hadn’t noticed earlier that you’re on Ubuntu. That should make getting blas/lapack much easier :)
> 
> You can make sure they’re installed using the following:
> `sudo apt-get install libblas-dev liblapack-dev`
> 
> OR
> 
> `sudo apt-get install libeigen3-dev`
> 
> If you’d rather use eigen3

@pshriwise Thank you, pshriwise! I have installed the MOAB successfully by your instruction

**Comment by pshriwise** [comment]
Excellent! Do keep me updated as to how things are going. There are a lot of instructions for model preparation on the [DAGMC site](https://svalinn.github.io/DAGMC/usersguide/uw2.html). I’d recommend setting up your module using the UWUW workflow - which will be supported by OpenMC very soon. I’m hoping to submit that capability for review within a week or so. 

You can also use the MCNP model prep guide, which is what OpenMC is using currently.

**Comment by D-Benjamin** [comment]
> Excellent! Do keep me updated as to how things are going. There are a lot of instructions for model preparation on the [DAGMC site](https://svalinn.github.io/DAGMC/usersguide/uw2.html). I’d recommend setting up your module using the UWUW workflow - which will be supported by OpenMC very soon. I’m hoping to submit that capability for review within a week or so.
> 
> You can also use the MCNP model prep guide, which is what OpenMC is using currently.

@pshriwise Thanks for your contribution on the OpenMC and thanks for your help in these days! I'll waiting for you to submit it so that I can use this new great feature to make my thesis's work better. Please let me know when it is issued and I'll focus it all the time. Thank you!

**Comment by pshriwise** [comment]
Hi @D-Benjamin!

I wanted to let you know that documentation for [preparation of a DAGMC model in CUBIT/Trelis for OpenMC](http://svalinn.github.io/DAGMC/usersguide/codes/openmc.html) and [use of DAGMC's CAD-based geometry in OpenMC](http://svalinn.github.io/DAGMC/usersguide/codes/openmc.html) have been added to the DagMC and OpenMC projects.

Please feel free to contact me with any questions you might have along the way. I hope this is helpful to you in your research endeavors!

**Comment by D-Benjamin** [comment]
Hi, @pshriwise ,

Thanks for your help, and now I'm Installing DAGMC as a dependency of OpenMC according to updated document. But there may be something wrong with it. When I run:
```
cmake .. -DMOAB_DIR=$HOME/dagmc_bld/MOAB \
           -DBUILD_TALLY=ON \
           -DCMAKE_INSTALL_PATH=$INSTALL_PATH
```
A error hint will appear:
```
CMake Error: The source directory "/home/benjamin/dagmc_bld/DAGMC" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
I'm sure that I run it from the build directory(that is "$HOME/dagmc_bld/DAGMC/bld"), which I built as specified on [document](http://svalinn.github.io/DAGMC/install/openmc.html).
Hope to get your reply soon! Thanks!!
