### ISSUE TITLE
Confusion of Rotational symmetry simulink by OpenMC

### ISSUE THREAD

**Issue by D-Benjamin** [openmc-dev/openmc#1129]
Hello everyone:
    I'm puzzled about the rotational symmetry simulink and I have some questions.
    Following is a few of contents in OpenMC use's guide[ chapter 6.1.1] :
    //"Rotationally-periodic boundary conditions can be specified for a pair of XPlane and YPlane"//

   Does it means the angle must be equal to 90° when you do the rotational symmetry simulink? Can we only simulate 1/8 core of reactor by OpenMC or even less?

Any reply will be appreciated!
Best Wishes!

**Comment by paulromano** [comment]
@D-Benjamin Yes, at the moment, rotationally-periodic boundary conditions can only be applied to pairs of x- and y-planes, so the best you could do right now is a 1/4-core model.

FYI, questions like these are better suited for our [user's group mailing list](https://groups.google.com/forum/#!forum/openmc-users), so I'd encourage you to join the mailing list. Github issues can be used for bug reports, feature requests, etc. Let us know if you have other questions!

**Comment by D-Benjamin** [comment]
> @D-Benjamin Yes, at the moment, rotationally-periodic boundary conditions can only be applied to pairs of x- and y-planes, so the best you could do right now is a 1/4-core model.
> 
> FYI, questions like these are better suited for our [user's group mailing list](https://groups.google.com/forum/#!forum/openmc-users), so I'd encourage you to join the mailing list. Github issues can be used for bug reports, feature requests, etc. Let us know if you have other questions!

Thanks for your recommendation, I plan to join it

**Comment by D-Benjamin** [comment]
> FYI, questions like these are better suited for our [user's group mailing list](https://groups.google.com/forum/#!forum/openmc-users), so I'd encourage you to join the mailing list. Github issues can be used for bug reports, feature requests, etc. Let us know if you have other questions!

@paulromano Thanks for your recommendation! I plan to join it
