### ISSUE TITLE
Energy cut-off at 8.1 MeV for Be7

### ISSUE THREAD

**Issue by liangjg** [openmc-dev/openmc#1138]
@salcedop reported that with `Be7` in a simulation, the flux beyond 8.1 MeV is zero. I found this issue had been noticed and discussed previously, see #406 and #474. And in #474 the neutron transport energy is cut-off at 8.1 MeV to make sure logarithmic grid works. But this approach introduces bias to the energy source and neglects all the reactions/cross-sections beyond 8.1 MeV. For example, in a PWR pincell model, including insignificant `Be7` can cause the keff 220 pcm smaller, not to mention the zero flux/reaction-rate tallies beyond 8.1 MeV.
However, it seems `Be7` is not an import nuclide: it does not exist naturally, and from endf 7.1, no nuclide decays to `Be7` and it is not a fission product either, so it should never appear in a model?
I'm not sure if this issue concerns us. Just be careful when using `Be7`.

**Comment by paulromano** [comment]
Yeah, I noticed this a long time ago. Just one of the many examples of an evaluation being seriously messed up. Unfortunately there's not too much we can do if a user puts Be7 in their model beyond what we do now, which is to limit the maximum neutron energy. We could potentially write out a warning if the maximum energy is < 20 MeV?
