### ISSUE TITLE
OpenMC Geometry Bug

### ISSUE THREAD

**Issue by makeclean** [openmc-dev/openmc#1139]
OpenMC doesnt check (at least for direct XML input) that the surfaces bounding a cell actually exist. The following file based on xml/basic runs succesfully without any issues.

```
<?xml version="1.0"?>
<geometry>

  <!-- Definition of Cells -->
  <cell id="1" universe="0" fill="37" region="-2" />
  <cell id="100" universe="37" material="40" region="-1" />
  <cell id="101" universe="37" material="41" region="1" />
  <cell id="2" universe="0" material="41" region="2 -3 4" />

  <!-- Defition of Surfaces -->
  <surface id="1" type="z-cylinder" coeffs="0 0 7" />
  <surface id="2" type="z-cylinder" coeffs="0 0 9" />
  <surface id="3" type="z-cylinder" coeffs="0 0 11" boundary="vacuum" />

</geometry>

```
Note that the order in the region section doesnt matter, it still runs to completion.

I think there should be a baseline check either way that every surface called for in the cells region should have a matching surface, else fail. Also, a warning should be produced if there are unused surface definitions.

**Comment by pshriwise** [comment]
Looks like we need to do a check for unused surfaces to close this. Is that right @paulromano?

**Comment by makeclean** [comment]
I think this was actually fixed long long ago, I'll try and find a sha

**Comment by pshriwise** [comment]
It looked like the non-existant surfaces were handled, but we still haven't added a check for unused surfaces in our initialization step.

**Comment by pshriwise** [comment]
At least I didn't see that check anywhere, but if you find it - then yeah, please ref here and close this up :)

**Comment by pshriwise** [comment]
Did we ever confirm that this issue was resolved @makeclean?

**Comment by paulromano** [comment]
I'm going to assume it was resolved given that there was a follow-on PR. @makeclean if you still see issues with this, feel free to reopen.
