### ISSUE TITLE
openmc.dev domain?

### ISSUE THREAD

**Issue by liangjg** [openmc-dev/openmc#1173]
@openmc-dev/committers, not sure if we want this, but [openmc.dev](https://domains.google.com/m/registrar/search?searchTerm=openmc.dev&hl=en) is now available. And, [beginning February 28, .dev domains will be available without an additional fee](https://domains.google/tld/dev/).

**Comment by paulromano** [comment]
Thanks for bringing this up. I'm actually in the process of acquiring openmc.org, so we'll be able to use that.

**Comment by liangjg** [comment]
OK, good.
