### ISSUE TITLE
openmc-voxel-to-vtk loads entire file in memory

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1175]
An ANL user reported running out of memory when trying to convert a 1000x1000x1000 voxel plot to VTK. While OpenMC writes the voxel file one slice at a time, the `openmc-voxel-to-vtk` script reads all data in before trying to convert it to VTK. It seems like it should be pretty straightforward to have `openmc-voxel-to-vtk` also convert one slice at a time to not consume so much memory.

@pshriwise Do you want to look into this when you get a chance? (on top of the million other tasks you have going on :)

**Comment by pshriwise** [comment]
What's one more? :)

Sure, I'm looking at a lot of that code right now. I'll see if I can find suitable fix.
