### ISSUE TITLE
endf parsing non utf-8 chars

### ISSUE THREAD

**Issue by Shimwell** [openmc-dev/openmc#1177]
When trying to convert the [CENDL 3.1 library](https://www.oecd-nea.org/dbforms/data/eva/evatapes/cendl_31/CENDL-31.zip) I notice that one file (22-Ti-047.C31) is not encoded with 'utf-8' format and contains some none utf-8 characters on line 206. 

This causes endf.py to crash with the following error. 

```
Converting: cendl-3.1-endf/22-Ti-047.C31
Traceback (most recent call last):
  File "data/generate_cendl.py", line 113, in <module>
    data = openmc.data.IncidentNeutron.from_njoy(filename)
  File "/home/jshim/.local/lib/python3.6/site-packages/openmc/data/neutron.py", line 812, in from_njoy
    pendf_file, **kwargs)
  File "/home/jshim/.local/lib/python3.6/site-packages/openmc/data/njoy.py", line 250, in make_ace
    ev = endf.Evaluation(filename)
  File "/home/jshim/.local/lib/python3.6/site-packages/openmc/data/endf.py", line 431, in __init__
    line = fh.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 381: invalid start byte
```

I guess this is because of the open method in mode 'r'

`with open(str(filename), 'r') as fh:`

I think one potential fix would be switching from mode 'r' to mode 'rb' when using open but perhaps this would cause issues elsewhere.

**Comment by paulromano** [comment]
The ENDF-6 format specification is pretty clear about non-ASCII characters:

> Given that different compilers, programming languages and operating systems treat character strings differently (not including Unicode issues), ENDF restricts characters in TEXT records to printable, non-whitespace ASCII characters

So, the CENDL file you have come across is not a valid ENDF file. I've also seen this happen with JEFF 3.2. My best suggestion for you is to fix the file and replace the non-ASCII characters.
