### ISSUE TITLE
10% of tests failed

### ISSUE THREAD

**Issue by Aarontama** [openmc-dev/openmc#1182]
I have tried to install openmc and the following tests have failed...

filter_energyfun #18 
multipole #41 
resonance_scattering #50  
source #55 
surface_tally #63 
tally_aggregation #66 
tally_arithmetic #67 
triso #78 

I have been looking around for hours and I am at a road block. I did noticed if I commented out my multipole environment variable in bashrc, I have all these test failed including 1 more:

diff_tally #8 

I thought maybe it has to do something with the multipole data?

**Comment by paulromano** [comment]
Hi @Aarontama, and welcome to the community! In the future, questions like this are better suited for our [user's group mailing list](https://groups.google.com/forum/#!forum/openmc-users).

If you want to be sure that you are using the same test data that is used for continuous integration tests, you can find a link [here](https://github.com/openmc-dev/openmc/blob/develop/tools/ci/download-xs.sh#L6). Notably, that includes the necessary multipole data you'll need for a few tests (including `diff_tally` and `multipole`). As for the other tests, sometimes you have to limit the number of OpenMP threads being used. You might want to try `export OMP_NUM_THREADS=4` before running the test suite.

Also, if you are using a mac, tests are known to fail on macOS (#801).

If you have further questions, please direct them to the user's group.
