### ISSUE TITLE
Photon heating

### ISSUE THREAD

**Issue by liangjg** [openmc-dev/openmc#1196]
We are reading [number 5 element of JXS when generating incident photon data from ACE for MT 515](https://github.com/openmc-dev/openmc/blob/develop/openmc/data/photon.py#L882-L884),
``` python
class PhotonReaction(EqualityMixin):

    @classmethod
    def from_ace(cls, ace, mt):

        n = ace.nxs[3]
        elif mt == 515:
            # Pair production
            idx = ace.jxs[1] + 4*n

        # Store cross section
        xs = ace.xss[idx : idx+n].copy()
```
However, the ACE format says the [number 5 element of JXS  is the heating number](https://github.com/NuclearData/ACEFormat/blob/master/src/ContinuousEnergyPhoton.tex#L16-L27).
``` latex
    1        & ESZG   & Energy table \\
    2        & JINC   & Incoherent form factors \\
    3        & JCOH   & Coherent form factors \\
    4        & JFLO   & Fluorescence data \\
    5        & LHNM   & Heating numbers \\
    6        & LNEPS  & Number of electrons per shell \\
    7        & LBEPS  & Binding energy per shell \\
    8        & LPIPS  & Probability of interaction per shell \\
```
But I didn't see where the `pair production` should be from this table. 
@amandalund @paulromano Did I miss something here? BTW I'm trying to add the heating number in the photon library so we can do neutron-photon coupled energy deposition tallies.

**Comment by paulromano** [comment]
It looks like the .tex documentation there for photoatomic data is incomplete. Pair production appears in the ESZG block starting at index `JXS(1) + 4*NXS(3)`. If you have a copy of MCNP5 user's manual, vol III, you'll see it there. Unfortunately that volume is under export control and can't be shared. You can find heating data in the ACE file starting at XSS(JXS(5)) and it is tabulated on the same energy grid as other cross sections. It's in units of MeV / collision, just like the neutron data.
