### ISSUE TITLE
Coverage of C++ code

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1229]
We currently obtain coverage of Python code during testing, which is then reported on coveralls. So, with respect to Python, we at least know what is not being covered. For C++ code, we actually are not collecting/reporting coverage numbers at all right now. Getting coverage will look something like the following:

1. Add a CMake option (rather fix the existing option) to throw coverage flags on. Looks like `--coverage` is all that's needed.
2. When OpenMC is run, `gcov` will generate `.gcda` files (in the build directory alongside object files) that contain coverage information 
3. Use `lcov` to collect information from the `.gcda` files into a single file.
4. At this point there are multiple options. We might be able to report C++ coverage in a separate CI job, and coveralls parallel build webhook might take care of this appropriately? Not sure. If we can't combine with existing Python coverage, we could also use a different service (e.g., codecov) to report C++ coverage.

**Comment by GiudGiud** [comment]
I've done something similar for OpenMOC last year. I can look into this for openmc. I used the cpp-coveralls library then the Python coveralls to merge results and upload.

**Comment by paulromano** [comment]
Awesome! Thanks for taking a stab at that. Looks like it was pretty simple to do actually. Look forward to a PR.

**Comment by paulromano** [comment]
Closed via #1235
