### ISSUE TITLE
Include path to depletion chain in cross_sections.xml

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1239]
Right now, for depletion, it's necessary to either set an `OPENMC_DEPLETE_CHAIN` environment variable or the `chain_file` argument of `openmc.deplete.Operator`. It would be nice to also be able to specify the path in `cross_sections.xml` so that only a single environment variable is needed.

**Comment by drewejohnson** [comment]
Would it be beneficial/helpful to first look for the chain file in the case `settings.xml` file/`openmc.deplete.Operator.settings` attribute, then the system `cross_sections.xml` file? This could allow _easy_ experimentation on the effect of the depletion chain.

**Comment by paulromano** [comment]
Yes, I definitely agree that if we have the depletion chain specified in `cross_sections.xml`, we ought to retain some way to easily change the depletion chain for experimentation. Do you see any reason why the `chain_file` argument to `Operator` would not be adequate for that purpose?

**Comment by drewejohnson** [comment]
I can't think of any, but I've still working on familiarizing myself with the depletion capabilities. 

The chain specified in `cross_sections.xml` could be the default and used unless `chain_file` is not passed. Something along these lines?

**Comment by paulromano** [comment]
Yup, that's what I was thinking.
