### ISSUE TITLE
Change order of arguments for surface classes

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1244]
One thing that has always annoyed me is that `XPlane`, `YPlane`, and `ZPlane` (and surfaces in general) don't accept their coefficients as the first arguments in `__init__`. Instead, the first argument is `surface_id`, a holdover from when it was required to assign one yourself. I'd like to propose changing the order so that surface coefficients always come first (and surface_id last), so for example you could do something like:
```Python
side = 3
x_min = openmc.XPlane(-side)
x_max = openmc.XPlane(side)
y_min = openmc.YPlane(-side)
y_max = openmc.YPlane(side)
```
Right now, you specifically have to say `x0=` or `y0=`. This would potentially break existing code where a user does something like `XPlane(10, x0=5.0)`, although the more verbose `XPlane(surface_id=10, x0=5.0)` would still work.

**Comment by drewejohnson** [comment]
Closed with #1330
