### ISSUE TITLE
Get rid of variable length arrays (VLAs) in C++

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1248]
As observed in #1243, trying to compile with MSVC results in errors due to the use of variable-length arrays, which are not part of the C++ standard. We've been getting by because evidently g++, clang++, and icpc all support VLAs as an extension. The simplest alternative is to use a heap-allocated vector, i.e., instead of
```C++
void foo(int n) {
  T bar[n];
}
```
you could have
```C++
void foo(int n) {
  std::vector<T> bar(n);
}
```
One potential concern of mine is whether any VLAs are used during transport (i.e., within OpenMP threads). If we switch to std::vector, there could be possible thread contention on a mutex for `malloc`.

**Comment by liangjg** [comment]
@paulromano [this commit](https://github.com/liangjg/openmc/commit/16d2d641e4deadc2c37bafb017b14d5a4e4079ea) contains a preliminary fix on the VLAs. I'll try to submit a PR later.

**Comment by paulromano** [comment]
@liangjg wonderful, thanks!
