### ISSUE TITLE
Restart depletion fails with MPI

### ISSUE THREAD

**Issue by drewejohnson** [openmc-dev/openmc#1275]
When performing a restart run with multiple MPI processes, it appears that one operator tries building reaction rate data/material data before all the cross sections have been loaded.

## Steps to reproduce
1. Build a simple problem, and deplete for some period of time with some power
1. Create a new operator for restart mode by reading in from the previous `depletion_results.h5` file
1. Deplete again with some power and some time step but with multiple MPI processes.

I have two files: `start.py` and `restart.py` for the first depletion sequence and for the restart. Running `mpirun -n N restart.py` always fails, whether or not `start.py` used multiple processes.

## Error
`mpirun -n 2 restart.py 2>&1 > out.log`
```
 Reading c_H_in_H2O from /home/drew/nndc_hdf5/c_H_in_H2O.h5
 Maximum neutron transport energy: 20000000.000000 eV for U235
 Reading tallies XML file...
 Writing summary.h5 file...
Time to matexp:  0.1556260585784912
Traceback (most recent call last):
  File "restart.py", line 20, in <module>
    openmc.deplete.integrator.predictor(op, [time_steps[0]], power)
  File "/home/drew/openmc/openmc/deplete/integrator/predictor.py", line 100, in predictor
    op_results = [operator(x[0], power[-1])]
  File "/home/drew/openmc/openmc/deplete/operator.py", line 175, in __call__
    self.number.set_density(vec)
  File "/home/drew/openmc/openmc/deplete/atom_number.py", line 214, in set_density
    self.set_mat_slice(i, density_slice)
  File "/home/drew/openmc/openmc/deplete/atom_number.py", line 199, in set_mat_slice
    self[mat, :self.n_nuc_burn] = val
  File "/home/drew/openmc/openmc/deplete/atom_number.py", line 104, in __setitem__
    self.number[mat, nuc] = val
IndexError: index 0 is out of bounds for axis 0 with size 0
 Reading I135 from /home/drew/nndc_hdf5/I135.h5
 Reading Xe135 from /home/drew/nndc_hdf5/Xe135.h5
```
[Full error - pastebin](https://pastebin.com/RwaDfNc5)

The process also hung at the last line

**Comment by drewejohnson** [comment]
The cause of the error is the distribution (or lack there of) of the previous results to multiple operators on different MPI processes. 

Each operator/process  [knows it's particular materials to deplete](https://github.com/openmc-dev/openmc/blob/a7d4dc0d5c4dd3546ad9e9c3b392f7c6ab7b3d9e/openmc/deplete/operator.py#L139), and creates corresponding `AtomNumber` objects to hold densities through time.

However, when the previous `ResultsList` is created with `ResultsList("depletion_results.h5")`, all MPI processes essentially share this object with knowledge of all materials, with no distribution. This is passed [directly on to the operator](https://github.com/openmc-dev/openmc/blob/develop/openmc/deplete/operator.py#L123-L128). At the start of the depletion routine, the initial concentrations are taken [directly from the operator](https://github.com/openmc-dev/openmc/blob/a7d4dc0d5c4dd3546ad9e9c3b392f7c6ab7b3d9e/openmc/deplete/integrator/cecm.py#L82). This puts all the processes in charge of depleting all materials, and then passing concentrations through `operator.__call__` to the `AtomNumber` objects, which are configured to only handle process-specific materials.

## Possible fixes

1) `ResultsList.__init__` handles the distribution, with a unique instance on each process, and these are passed directly to the `Operator`, or
2) When previous results are passed into `Operator`s, they distribute and create process-specific `prev_results` attributes.

My preference would be for path 2, because the `ResultsList` is not aware of what materials an `operator` may need at initialization.

**Comment by paulromano** [comment]
Yes, I agree option 2 better.
