### ISSUE TITLE
Failed to build OpenMC test suite

### ISSUE THREAD

**Issue by zxkjack123** [openmc-dev/openmc#1282]
Following the guidance here: https://openmc.readthedocs.io/en/stable/devguide/workflow.html#openmc-test-suite, I tried to build the OpenMC test suite. However the following error happened:
```
~/opt/openmc/build# make test
make: *** No rule to make target 'test'.  Stop.
```
And this is the output of `pytest` in `tests` directory:
```
pytest 
============================= test session starts ==============================
Platform Linux -- Python 3.6.7, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /root/opt/openmc, inifile: pytest.ini
plugins: cov-2.7.1
collected 406 items / 1 skipped / 405 selected                                 

regression_tests/asymmetric_lattice/test.py F                            [  0%]
regression_tests/cmfd_feed/test.py 
```

This is my OpenMC install command:
```
alias openmc_build='export FC=/usr/bin/mpif90  && export CC=/usr/bin/mpicc && export CXX=/usr/bin/mpicxx && cmake ../ -Doptimize=on -DHDF5_PREFER_PARALLEL=on -DCMAKE_INSTALL_PREFIX=$HOME/opt/OpenMC -Ddebug=ON -Ddagmc=ON -DDAGMC_ROOT=$HOME/opt/dagmc && make && make install'
```

How to fix the problem?

**Comment by drewejohnson** [comment]
It looks like you might be building an older version of `openmc`, as the fortran compiler isn't necessary anymore and testing is done with `pytest` as opposed with `make test`. If you are trying to build the newest version, can you report back what happens following the `latest` build instructions https://docs.openmc.org/en/latest/usersguide/install.html and test suite https://docs.openmc.org/en/latest/devguide/tests.html?

**Comment by zxkjack123** [comment]
Thanks @drewejohnson.
I updated `openmc` and install again following the `latest` build instructions, but the problem is still there. 

The following is what I did:
- I updated the `openmc` to `upstream/develop` (upstream: https://github.com/openmc-dev/openmc.git
). 
- Then installed it again using the command (actually the same script, but in multiple lines for better reading):
```
export FC=/usr/bin/mpif90
export CC=/usr/bin/mpicc
export CXX=/usr/bin/mpicxx
cmake ../ -Doptimize=on -DHDF5_PREFER_PARALLEL=on -DCMAKE_INSTALL_PREFIX=$HOME/opt/OpenMC -Ddebug=ON -Ddagmc=ON -DDAGMC_ROOT=$HOME/opt/dagmc
make
make install
cd $HOME/opt/openmc
pip install -e .[test]
```
- Check the `openmc` could be found:
```
which openmc
/root/opt/OpenMC/bin/openmc
```
- Check `openmc` python module is importable:
```
python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmc
>>> openmc.__version__
'0.10.0'
```
- Run `pytest` and the problem still there:
```
~/opt/openmc/tests# pytest 
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /root/opt/openmc, inifile: pytest.ini
plugins: cov-2.7.1
collected 406 items / 1 skipped / 405 selected                                 

regression_tests/asymmetric_lattice/test.py F                            [  0%]
regression_tests/cmfd_feed/test.py 
```

**Comment by drewejohnson** [comment]
If you run grab some example [xml](https://github.com/openmc-dev/openmc/tree/develop/examples/xml/pincell) or [python](https://github.com/openmc-dev/openmc/tree/develop/examples/python/pincell), will `openmc` run?

Have you downloaded a set of cross sections? This is not currently listed in the developer guide, but you do need some cross sections to run openmc. If there aren't cross sections for openmc to find, it will fail basically automatically.

[Test cross section download script](https://github.com/openmc-dev/openmc/blob/develop/tools/ci/download-xs.sh) is used to check `openmc` using `pytest`

**Comment by paulromano** [comment]
Along those same lines, it's important that the cross section data you're using matches the version of OpenMC you're running. Periodically, the test data changes. As @drewejohnson mentioned, the `download-xs.sh` script is the best place to look for the correct data. When running pytest, you might also want to throw on `-v` (verbose) and `-s` (show stdout) flags.

**Comment by zxkjack123** [comment]
> If you run grab some example [xml](https://github.com/openmc-dev/openmc/tree/develop/examples/xml/pincell) or [python](https://github.com/openmc-dev/openmc/tree/develop/examples/python/pincell), will `openmc` run?
> 
> Have you downloaded a set of cross sections? This is not currently listed in the developer guide, but you do need some cross sections to run openmc. If there aren't cross sections for openmc to find, it will fail basically automatically.
> 
> [Test cross section download script](https://github.com/openmc-dev/openmc/blob/develop/tools/ci/download-xs.sh) is used to check `openmc` using `pytest`

I `openmc` I installed failed running the test:
```
~/opt/openmc/examples/xml/pincell# openmc
                                %%%%%%%%%%%%%%%
                           %%%%%%%%%%%%%%%%%%%%%%%%
                        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                    %%%%%%%%%%%%%%%%%%%%%%%%
                                     %%%%%%%%%%%%%%%%%%%%%%%%
                 ###############      %%%%%%%%%%%%%%%%%%%%%%%%
                ##################     %%%%%%%%%%%%%%%%%%%%%%%
                ###################     %%%%%%%%%%%%%%%%%%%%%%%
                ####################     %%%%%%%%%%%%%%%%%%%%%%
                #####################     %%%%%%%%%%%%%%%%%%%%%
                ######################     %%%%%%%%%%%%%%%%%%%%
                #######################     %%%%%%%%%%%%%%%%%%
                 #######################     %%%%%%%%%%%%%%%%%
                 ######################     %%%%%%%%%%%%%%%%%
                  ####################     %%%%%%%%%%%%%%%%%
                    #################     %%%%%%%%%%%%%%%%%
                     ###############     %%%%%%%%%%%%%%%%
                       ############     %%%%%%%%%%%%%%%
                          ########     %%%%%%%%%%%%%%
                                      %%%%%%%%%%%

                   | The OpenMC Monte Carlo Code
         Copyright | 2011-2019 MIT and OpenMC contributors
           License | http://openmc.readthedocs.io/en/latest/license.html
           Version | 0.11.0-dev
          Git SHA1 | 61c911cffdae2406f9f4bc667a9a6954748bb70c
         Date/Time | 2019-07-16 15:02:13
     MPI Processes | 1
    OpenMP Threads | 2

 Reading settings XML file...
 Reading cross sections XML file...
 Reading materials XML file...
 Reading geometry XML file...
 Reading U234 from /root/nndc_hdf5/nndc/U234.h5
 ERROR: HDF5 data format uses version 2.0 whereas your installation of OpenMC
        expects version 3.x data.
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=-1
:
system msg for write_line failure : Bad file descriptor
```

I find a strange line in the print message when I build `openmc`:
```
Installing collected packages: openmc
  Found existing installation: openmc 0.10.0
    Can't uninstall 'openmc'. No files were found to uninstall.
  Running setup.py develop for openmc
Successfully installed openmc
```
But the `openmc`  in my `openmc/bin` is updated.  Is this related to my error?

**Comment by zxkjack123** [comment]
Update:
`pytest` available now after the changes:
- Update to the newest `upstream/develop`
- Download nuc data again using `download-xs.sh`

Summary of `pytest`:
```
...
unit_tests/test_data_neutron.py ......E.E...............FEF              [ 44%]
unit_tests/test_data_photon.py ...................                       [ 49%]
unit_tests/test_data_thermal.py ....FEE...E...                           [ 52%]
...
=== 4 failed, 405 passed, 2 skipped, 11 warnings, 6 error in 370.44 seconds ====
```
It it normal to have 4 failed tests? @drewejohnson @paulromano

**Comment by drewejohnson** [comment]
Yes and no. They should never fail in the controlled test environment, but a few may fail on your local system and not mean `openmc` is broken. Some of those tests may be failing because you don't have [`njoy`](https://github.com/njoy) installed in a place needed for the tests for methods like testing [`IncidentNeutron.from_njoy`](https://docs.openmc.org/en/latest/pythonapi/generated/openmc.data.IncidentNeutron.html?highlight=from_njoy#openmc.data.IncidentNeutron.from_njoy). Running `pytest` with the `-s` and -`v` options like Paul mentioned would provide some answers there.

**Comment by zxkjack123** [comment]
Thanks a lot @drewejohnson @paulromano! Problem fixed! Got tthe following message:
```
============================== 417 passed, 15 warnings in 594.39 seconds ==============================
```

There were three main reasons of my problem:
- Outdated version nuclear data (nndc_hdf5) but new version OpenMC.
- Missing NJOY
- Forgot to build test suite after re-install OpenMC. The command `pip install -e .[test]
` has to be run every time when I re-install OpenMC.
