### ISSUE TITLE
Incorrect value read from openmc.deplete.ResultsList for fisrst simulation time step 

### ISSUE THREAD

**Issue by dryuri92** [openmc-dev/openmc#1288]
I were testing deplete functionality both with old and new *.hdf5 cross-sections version and  when try to get `results = od.ResultsList('depletion_results.h5')
                                          results.get_atoms('1','nuclide_name')`
concentration for nuclide initially not pointed in materials.xml for first time step I received the same value 4.68084739e+02.

**Comment by drewejohnson** [comment]
Interesting. Can you provide the full output from `results.get_atoms('1', 'nuclide_name')`? Depending on the problem [very small time step, very low power, trace nuclide], it could be that that nuclide isn't changing with time.

**Comment by dryuri92** [comment]
I use one of the depletion_test as a pattern and benchmark data. My input:`# Power and timesteps
dt1 = 15.*24*60*60  # 15 days
dt2 = 1.5*30*24*60*60  # 1.5 months
N = floor(dt2/dt1)
dt = np.full(N, dt1)
# FROM VVER BENCHMARK
qv = 108 #MWt/m^3 or Wt/cm^3
H = 23.6 #cm
numfuelpin = 308 # number of fuelled pin
Q = sqrt(3.0)/2.0*H*H*qv #*l
power = Q/numfuelpin
# Perform simulation using the predictor algorithm
openmc.deplete.integrator.predictor(op, dt, power)` with a `power ~ 170 W/cm`.

**Comment by drewejohnson** [comment]
One thing the [`operator`](https://docs.openmc.org/en/latest/pythonapi/generated/openmc.deplete.Operator.html#openmc.deplete.Operator) does prior to running the transport simulation is set isotopes with zero concentration, like `Pu239`, to some very small quantity. This is done according to the `dilute_initial` attribute. The reasoning for this is to ensure that 1) useful reaction rates are obtained and 2) mitigate some potential divide by zero and round off errors through the depletion process. The values are small enough to be _functionally_ zero, compared to all other isotopes, 400 vs. 2x10^18 and greater for U235.

**Comment by dryuri92** [comment]
@drewejohnson ,yes I understand that made for some numerical reason, but is it right for users to get in fisrst time step incorrect value by calling `get_atoms` function?

**Comment by dryuri92** [comment]
@drewejohnson I mean is it should be on public code side rather than on private?

**Comment by drewejohnson** [comment]
`dilute_initial` could probably be moved to give the user more control like you suggest
