### ISSUE TITLE
Remove complement operator in C++ RPN

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#1290]
Some context: I've been playing around with creating robust bounding boxes for surfaces, cells, and universes in our C++ code to make this information accessible in the CAPI. While surfaces and universes are straightforward, cell bounding boxes require more consideration in accounting for the CSG operations defining their regions. In particular, cells with complement regions are problematic. A bounding box complement is difficult to define without knowledge of the specific halfspaces that make up that region, requiring what I'll claim is messy and complicated parsing of the RPN to isolate these regions. 

As an alternative, I found it fairly straightforward to avoid the use of complement operators altogether in OpenMC's internal RPN representation by applying De Morgan's laws in the `generate_rpn` function. These laws are also applied in the Python API to get bounding boxes, but it is significantly more clear there thanks to the `openmc.Region` class and subclasses. 

The removal of complement operators from the C++-side RPN allows us to simplify the `CSGCell::contains_complex` slightly as well. 

Is there any major downside to this? I suppose it could be a little confusing if users re-create a `geometry.xml` from a `summary.h5` file. The RPN will have changed at that point, I think...

Another option would be to implement a `Region` class in C++ similar to the one in the Python API, though I worry that this wouldn't be as efficient during simulation.

**Comment by pshriwise** [comment]
I think I'm actually going to go the route of parsing the RPN to determine the bounding box. This will keep our internal representation the same and avoid having inconsistent input/output of complex cell definitions.

It turns out there are artifacts in the RPN from `generate_rpn` that allow us to determine when parenthesis begin and end. De Morgan's laws can then be applied on-the-fly to these sections of the RPN to get the bounding box. Specifically, two consecutive surface tokens (which aren't the first two entries in the RPN) indicate a left parenthesis and two (or three) consecutive operator tokens indicate a right parenthesis. A Sub-RPN set of tokens can be extracted using these rules and, in turn, a bounding box formed representing that region. 

In the case that the last token in the Sub-RPN set is a complement operator, DeMorgan's laws can be applied to the Sub-RPN and the next token in the RPN will be added to the Sub-RPN. This next token should always be the operator connecting the region in the parenthesis with the rest of the RPN.

I'll try to outline this more clearly in the imminent PR. I think this better addresses the formation of complex cell bounding boxes than my original plan.

**Comment by paulromano** [comment]
Another way you can think about doing this is to build an abstract syntax tree from the RPN and then apply De Morgan's law on the complement within the AST. Anyway, sounds like you have a path forward.

**Comment by paulromano** [comment]
@pshriwise I'm closing this issue since you were able to find an alternative solution.
