### ISSUE TITLE
Python API: display ao instead of wo for Material

### ISSUE THREAD

**Issue by RonRahaman** [openmc-dev/openmc#1291]
In the Python API, when you print a `Material`, it displayes the weight percentages rather than the atom percentages.  Would you consider showing the atom percentages instead?

`'ao'` is the default when you're adding nuclides and elements to a `Material`, and it's in all my specs.  I know I can use `get_nuclide_atom_densities()`, but it would be really nice if it was in the display.  

```
In [4]: m_fuel
Out[4]:
Material
	ID             =	1
	Name           =	m_fuel - uranium oxycarbide - triso partciles
	Temperature    =	None
	Density        =	10.5 [g/cm3]
	S(a,b) Tables
	Nuclides
	U234           =	0.03565284   [wo]
	U235           =	17.790767159999998 [wo]
	U238           =	71.75358     [wo]
	C0             =	1.8          [wo]
	O16            =	8.616527990092724 [wo]
	O17            =	0.003472009907274255 [wo]
```

**Comment by paulromano** [comment]
If the nuclide densities are specified as atom fractions, the string representation will indeed show [ao]. The reason this material in particular is showing [wo] is because that's how it's specified:
```Python
m_fuel.add_nuclide(..., percent_type='wo')
```
