### ISSUE TITLE
Setting temperature outside loaded range results in segfault

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1292]
In a coupled TH simulation, if the temperature of a material is set to a value that is outside range of temperatures that have been loaded for nuclides, OpenMC will currently just segfault (usually this happens in `Nuclide::calculate_xs` when determining `i_temp` which becomes out of bounds). There ought to be a check that the temperature is valid. We might not want to do this for every single call to `openmc_cell_set_temperature` because it would involve checking the range of temperatures for every nuclide. Instead, it might be better to keep track of a single global value for the minimum/maximum temperature available and use that instead.

**Comment by dryuri92** [comment]
@paulromano Maybe use `temperature_range` array to check and specify it in `settings.xml` for such purposes?
