### ISSUE TITLE
Assignment of material's temperature by python code should be remained when using DAGMC-OpenMC

### ISSUE THREAD

**Issue by D-Benjamin** [openmc-dev/openmc#1293]
Hi All,
    New feature of using CAD-Based Geometries have been released in latest version. However, the way of assigning temperature have changed. We can not assign material's temperature by:

```
u235 = openmc.Material(name="fuel")
u235.add_nuclide('U235', 1.0, 'ao')
u235.set_density('g/cc', 11)
u235.temperature = 900         #This line will be no use even if you add it
```

   Materials' temperature can not be assigned, the only way to assign temperature is by using "Cubit/Trelis" when we creating geometry model:

`CUBIT> group "temp:900" add vol x` ([here is the link](https://svalinn.github.io/DAGMC/usersguide/codes/openmc.html#temperatures))

Thus, it will be very inconvenient when we want to change the materials' temperature, we have to launch "Cubit/Trelis" to change it. In particular, if we want to achieve a coupling between the neutronics and thermal-hydraulics(such as between OpenMC and a thermal-hydraulics code), we need exchange the power distribution, materials' temperature and density distribution by editing script. It is impossible to exchange large amounts of data manually by launching "Cubit/Trelis" and enter "`CUBIT> group "temp:900" add vol x`" every time. So I highly recommend that assignment of material's temperature by python code should be remained when using DAGMC-OpenMC.

Best Regards,
Benjamin

**Comment by pshriwise** [comment]
As a repeat from the original issue, I totally agree and thanks for bringing this to our attention. The rules for temperature settings should not change for a DagMC run and it's much more convenient to be able to vary temperatures using materials when using a DagMC model in the legacy workflow. So I have a PR for that coming soon (hopefully today or tomorrow).

As for coupling with TH codes, cell temperatures can be modified using OpenMC's `openmc_get/set_cell_temperature` methods in the CAPI thanks to a recent addition by @aprilnovak.  Given that these are available now, temperatures can technically be corrected if the ones in the `materials.xml` are ignored, but I'll wager we both agree it's best to fix the root of the problem. :)
