### ISSUE TITLE
Unable to read in volume_*.h5 files using openmc.VolumeCalculation.load_results when a domain has no volume..

### ISSUE THREAD

**Issue by MattMavis** [openmc-dev/openmc#1296]
Hi,

Currently, when reading in the .h5 volume files generated from openmc.calculate_volumes(), if a domain has no volume in the area sampled, the file is written without the atoms and nuclides datasets. This causes openmc.VolumeCalculation.load_results to fail when loading the files as it expects the nuclides and atoms datasets to be present. The error is displayed below:

`Traceback (most recent call last):
  File "volume_test.py", line 334, in <module>
    vol_calc.load_results('volume_' + str(i) +'.h5')
  File "/home/mmavis/.local/lib/python3.7/site-packages/openmc/volume.py", line 250, in load_results
    results = type(self).from_hdf5(filename)
  File "/home/mmavis/.local/lib/python3.7/site-packages/openmc/volume.py", line 215, in from_hdf5
    nucnames = group['nuclides'][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/mmavis/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'nuclides' doesn't exist)"
`

A possible solution to this is to modify the VolumeCalculation::to_hdf5 function in volume_calc.cpp to write null values to the output file when the nuclide/atom data is missing.
Below I have included my modification that works:
```

void VolumeCalculation::to_hdf5(const std::string& filename,
  const std::vector<Result>& results) const
{
  // Define null values for nuclides and atoms
  std::vector<std::string> name_null = {"null"};
  std::vector<double> vector_null = {0.0E0 };
  // Create HDF5 file
  hid_t file_id = file_open(filename, 'w');

  // Write header info
  write_attribute(file_id, "filetype", "volume");
  write_attribute(file_id, "version", VERSION_VOLUME);
  write_attribute(file_id, "openmc_version", VERSION);
#ifdef GIT_SHA1
  write_attribute(file_id, "git_sha1", GIT_SHA1);
#endif

  // Write current date and time
  write_attribute(file_id, "date_and_time", time_stamp());

  // Write basic metadata
  write_attribute(file_id, "samples", n_samples_);
  write_attribute(file_id, "lower_left", lower_left_);
  write_attribute(file_id, "upper_right", upper_right_);
  if (domain_type_ == FILTER_CELL) {
    write_attribute(file_id, "domain_type", "cell");
  }
  else if (domain_type_ == FILTER_MATERIAL) {
    write_attribute(file_id, "domain_type", "material");
  }
  else if (domain_type_ == FILTER_UNIVERSE) {
    write_attribute(file_id, "domain_type", "universe");
  }

  for (int i = 0; i < domain_ids_.size(); ++i)
  {
    hid_t group_id = create_group(file_id, "domain_"
      + std::to_string(domain_ids_[i]));

    // Write volume for domain
    const auto& result {results[i]};
    write_dataset(group_id, "volume", result.volume);

    // Create array of nuclide names from the vector
    auto n_nuc = result.nuclides.size();

    if (!result.nuclides.empty()) {
      std::vector<std::string> nucnames;
      for (int i_nuc : result.nuclides) {
        nucnames.push_back(data::nuclides[i_nuc]->name_);
      }

      // Create array of total # of atoms with uncertainty for each nuclide
      xt::xtensor<double, 2> atom_data({n_nuc, 2});
      xt::view(atom_data, xt::all(), 0) = xt::adapt(result.atoms);
      xt::view(atom_data, xt::all(), 1) = xt::adapt(result.uncertainty);

      // Write results
      write_dataset(group_id, "nuclides", nucnames);
      write_dataset(group_id, "atoms", atom_data);
    }
    else {
      // Create array of null values for atoms
      xt::xtensor<double, 2> atom_null({1, 2});
      xt::view(atom_null, xt::all(), 0) = xt::adapt(vector_null);
      xt::view(atom_null, xt::all(), 1) = xt::adapt(vector_null);

      //Write null values
      write_dataset(group_id, "nuclides", name_null);
      write_dataset(group_id, "atoms", atom_null);
    }
    close_group(group_id);
  }

  file_close(file_id);
}

```
The modification works for me, submitting for consideration and/or further refinement.
Best Regards,
Matt

**Comment by paulromano** [comment]
Fixed in #1361.
