### ISSUE TITLE
openmc runtime error

### ISSUE THREAD

**Issue by jrexpert92** [openmc-dev/openmc#1305]
i am getting this error on running openmc "ERROR: HDF5 data format uses version 1.0 whereas your installation of OpenMC expects version 3.x data" 

i couldn't rectify this problem  please suggest something

**Comment by paulromano** [comment]
Hi @jrexpert92. Please see https://openmc.org/ for up-to-date pre-generated data libraries (version 3) that will work with your installation. FYI, in the future, these types of inquiries are better suited for the OpenMC [user's group mailing list](https://groups.google.com/forum/#!forum/openmc-users).
