### ISSUE TITLE
Give more useful exception when an unrecognized tally scores is provided

### ISSUE THREAD

**Issue by gridley** [openmc-dev/openmc#1365]
Greetings,

Does anyone else think that a more helpful error message would be in order when someone gives a bad tally score type? Currently the error message is:

> terminate called after throwing an instance of 'std::invalid_argument'
  what():  Invalid tally score "banana"
Aborted (core dumped)

It would be quite helpful if the list of available score types were printed when this error happens. OpenFOAM does this automatically for any input which is restricted to a fixed list of strings.

**Comment by paulromano** [comment]
The list of tally scores is [pretty big](https://docs.openmc.org/en/latest/usersguide/tallies.html#scores), so I don't think we'd want to dump a huge wall of text on the user. I think that the error message is informative as is, although I suppose we could point them to the user's guide for a list of valid scores.

**Comment by gridley** [comment]
Hm, OK, well, if you actually want a change to be made to the code, I'm happy to do this. Otherwise, agree that it's fine to not dump the options; I had not looked at that page of the docs and had no clue there was such an extensive list of options.

**Comment by paulromano** [comment]
Resolved by #1625
