### ISSUE TITLE
OpenMC 0.11.0 not available in conda-forge on MacOS

### ISSUE THREAD

**Issue by fshriver** [openmc-dev/openmc#1378]
Hello,

I'm trying to install the OpenMC package through the conda-forge channel and successfully installed openmc-0.11.0 on two separate linux distributions this way. However, after installing Anaconda3 on my MacBook Air and running:

`conda search openmc --channel conda-forge`

I am only shown openmc-0.10.0 and below; openmc-0.11.0 is not present. Are the package distributions available to macOS behind those available on Linux? Understandable, if so; I just want to make sure I'm not doing anything incorrect.

**Comment by paulromano** [comment]
Yes, the latest conda build was configured to skip macOS. However, there's no reason we shouldn't be able to build on macOS, so I'm working on getting it [set up](https://github.com/conda-forge/openmc-feedstock/pull/24). I'll make another comment here if and when a macOS build is ready.

**Comment by paulromano** [comment]
@fshriver Version 0.11.0 should now be available for macOS on conda-forge. Let us know if you run into any trouble with it.
