### ISSUE TITLE
Add vim to Dockerfile?

### ISSUE THREAD

**Issue by RonRahaman** [openmc-dev/openmc#1391]
I've been using your Docker image over the last couple weeks because MacOS 15 and XCode 11 have been making life 
[miserable](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90835) 
[for](https://trac.macports.org/ticket/59113) 
[everyone](https://github.com/Homebrew/homebrew-core/issues/40676).  

It's great, and I can use it for several of my other programming projects.  Could you add vim to the image as well? :)

**Comment by paulromano** [comment]
The purpose of the Docker image is to have the minimum set of requirements for OpenMC, not necessarily as a general development environment. There's really nothing special about it -- it is just Ubuntu + compilers + NJOY + OpenMC. I would suggest creating your own image that includes vim and whatever other development tools you typically need and putting it up on Docker hub.
