### ISSUE TITLE
Can't install openmc 0.11

### ISSUE THREAD

**Issue by logic0905** [openmc-dev/openmc#1415]
Hi all,

I study how to use openmc for my scientyfic work for two weeks.
I work in Spyder IDE (anaconda 1.9.7, Python 3.7, Ubuntu 18.04).

When I try to install openmc from conda forge it install only version 0.10

I try to install 0.11 version manually it show some conflickt messege with some of Pethon modules.

What I do wrong?

Thank's :)

**Comment by paulromano** [comment]
@logic0905 What conflict messages are you seeing and at what stage of the install? What operating system are you on?

**Comment by logic0905** [comment]
Dear Paul,
I work in Ubuntu 18.04 in wirtual box in win 10.
I do regular installation 
1) conda config --add channels conda-forge
2)conda install openmc
And it install 0.10 version.
3)conda update openmc don't do enething
4) conda install openmc=0.11
starts and  shows that:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining hdf5:   6%|█▍                      | 24/407 [00:00<00:00, 3673.04it/ ]
Comparing specs that have this dependency:   0%|          | 0/5 [00:00<?, ?it/s]
Finding shortest conflict pa-  for hdf5[version='>=1.10.3,<1.10.4.0a0']:   8%| |Finding shortest conflict path for hdf5[version='>=1.10.3,<1.10.4.0a0']:  15%|▏|Finding shortest conflict pa/  for hdf5[version='>=1.10.5,<1.10.6.0a0']:  15%|▏|Finding shortest conflict path for hdf5[version='>=1.10.5,<1.10.6.0a0']:  23%|▏|Finding shortest conflict\ ath for hdf5[version='>=1.8.20,<1.9.0a0']:  23%|▏| 3/Finding shortest conflict path for hdf5[version='>=1.8.20,<1.9.0a0']:  31%|▎| 4/Finding shortest conflict pa\  for hdf5[version='>=1.10.1,<1.10.2.0a0']:  31%|▎|Finding shortest conflict path for hdf5[version='>=1.10.1,<1.10.2.0a0']:  38%|▍|Finding shortest confli|  path for hdf5[version='1.8.18|1.8.18.*']:  38%|▍| 5/13Finding shortest conflict path for hdf5[version='1.8.18|1.8.18.*']:  46%|▍| 6/13Finding shortest conflict pa/  for hdf5[version='>=1.10.4,<1.10.5.0a0']:  46%|▍|Finding shortest conflict path for hdf5[version='>=1.10.4,<1.10.5.0a0']:  54%|▌|Finding shortest confli\  path for hdf5[version='1.8.17|1.8.17.*']:  54%|▌| 7/13Finding shortest conflict path for hdf5[version='1.8.17|1.8.17.*']:  62%|▌| 8\ 3Finding shortest conflict path for hdf5:  62%|█▊ | 8/13 [00:03<00:02,  1.93it/s]Finding shortest conflict pat- for hdf5[version='>=1.10.2,<1.10.3.0a0']:  69%|▋|Finding shortest conflict path for hdf5[version='>=1.10.2,<1.10.3.0a0']:  77%- |Finding shortest conflict path for hdf5:  77%|█▌| 10/13 [00:05<00:01,  2.20it/s]Finding shortest conflict path for hdf5[version='>=1.8.18,<1.8.19.0a0']:  85%|▊|Finding shortest conflict pat| for hdf5[version='>=1.8.18,<1.8.19.0a0']:  92%|▉|Finding shortest conflict path for hdf5==1.10.1:  92%|▉| 12/13 [04:13<01:14, 74.Comparing specs that have this dependen/ :  40%|▍| 2/5 [04:13<06:20, 126.74s/it]Finding shortest conflict path for hdf5[version='>=1.10.5,<1.10.6.0a0',build=mpiFinding shortest conflict path for hdf5[versi\ ='>=1.10.5,<1.10.6.0a0',build=mpiFinding shortest conflict path for hdf5[version='>=1.10.5,<1.10.6.0a0',build=mpiFinding shortest conflict path for hdf5[version='>=1.10.5,<1.10.6.0a0']:  50%|▌|Finding shortest conflict p\ h for hdf5[version='>=1.10.5,<1.10.6.0a0']:  75%|▊|Comparing specs tha| have this dependency:  60%|▌| 3/5 [07:22<04:55, 147.54s/it]Finding shortest conflict path for hdf5[version='>=1.10.4,<1.10.5.0a0']:   0%| |Finding shortest conflict path for hdf5==1.10.4=hb1b8bf9_0:  33%|▎| 1/3 [00:04<0Finding shorte|  conflict path for hdf5==1.10.4=hb1b8bf9_0:  67%|▋| 2/3 [00:04<0Comparing specs that have this dependency:  80%|▊| 4/5 [08:31<02:07, 127.86s/it]Finding shortest conflict path for hdf5[/ rsion='>=1.10.5,<1.10.6.0a0',build=mpiFinding shortest conflict path for hdf5[version='>=1.10.3,<1.10.4.0a0']:   5%| |Finding shortest conflict pa|  for hdf5[version='>=1.10.1,<1.10.2.0a0']:  11%| |Finding shortest conflict path for hdf5[version='>=1.10.1,<1.10.2.0a0']:  16%|▏|Finding shortest conflict path for hdf5[version=- =1.10.4,<1.10.5.0a0',build=mpiFinding shortest conflict path for hdf5[version='>=1.10.4,<1.10.5.0a0',build=mpiFinding shortest confli-  path for hdf5[version='1.8.18|1.8.18.*']:  21%|▏| 4/19Finding shortest conflict path for hdf5[version='1.8.18|1.8.18.*']:  26%|▎| 5/19Find\ g shortest conflict path for hdf5==1.10.1:  26%|▎| 5/19 [00:02<00:05,  2.6Finding shortest conflict path for hdf5==1.10.1:  32%|▎| 6/19 [00:02<00:05,  2.5Fin- ng shortest conflict path for hdf5=1.10.2:  32%|▎| 6/19 [00:02<00:05,  2.53Finding shortest conflict path for hdf5=1.10.2:  37%|▎| 7/19 [00:02<00:05,  2.32Fin| ng shortest conflict path for hdf5=1.10.1:  37%|▎| 7/19 [00:03<00:05,  2.32Finding shortest conflict path for hdf5=1.10.1:  42%|▍| 8/19 [00:03<00:07,  1.56Finding shortest conflict path for hdf5[versio| '>=1.10.4,<1.10.5.0a0',build=mpiFinding shortest conflict path for hdf5[version='>=1.10.4,<1.10.5.0a0',build=mpiFind/ g shortest conflict path for hdf5=1.8.17:  47%|▍| 9/19 [00:05<00:07,  1.27Finding shortest conflict path for hdf5=1.8.17:  53%|▌| 10/19 [00:05<00:05,  1.5Finding shortest conflic- path for hdf5[version='1.8.17|1.8.17.*']:  53%|▌| 10/1Finding shortest conflict path for hdf5[version='1.8.17|1.8.17.*']:  58%|▌| 11/1Finding shortest conflict path for hdf5[version/ >=1.10.5,<1.10.6.0a0',build=mpiFinding shortest conflict path for hdf5[version='>=1.10.5,<1.10.6.0a0',build=| iFinding shortest conflict path for hdf5:  63%|█▎| 12/19 [00:07<00:03,  2.02it/s]Finding shortest conflict pat/ for hdf5[version='>=1.10.2,<1.10.3.0a0']:  68%|▋|Finding shortest conflict path for hdf5[version='>=1.10.2,<1.10.3.0a0']:  74%\ |Finding shortest conflict path for hdf5:  74%|█▍| 14/19 [00:08<00:02,  1.72it/s]Finding shortest conflict pat/ for hdf5[version='>=1.10.5,<1.10.6.0a0']:  79%|▊|Finding shortest conflict path for hdf5[version='>=1.10.5,<1.10.6.0a0']:  84%|▊|Finding shortest conflict - th for hdf5[version='>=1.8.20,<1.9.0a0']:  84%|▊| 16Finding shortest conflict path for hdf5[version='>=1.8.20,<1.9.0a0']:  89%|▉| 17Finding shortest conflict path for hdf5[version='>=1.10.4,<1.10.5.0a0']:  89%|▉|Finding shortest conflict pat| for hdf5[version='>=1.10.4,<1.10.5.0a0']:  95%|▉|Examining backports.functools_lru_cache:  14%|▏| 57/407 [12:27<2:47:40, 28.74s/iExamining ripgrep:  14%|██▉                  | 58/407 [12:27<2:47:11, 28.74s/it]Examining h5py:  21%|████▉                   | 84/407 [12:27<2:34:44, 28.74s/\ ]
Comparing- pecs that have this dependency:  33%|▎| 1/3 [03:11<06:23, 191.73s/it]
Finding shortest conflict path for h5py==2.9.0=py27h7918eee_0:   0%| | 0/4 [00:0Finding shortest conflict path for h5py==2.9.0=py37h7918eee_0:  25%|▎| 1/4 [00:0Finding shortest \ nflict path for h5py==2.9.0=py37h7918eee_0:  50%|▌| 2/4 [00:0Examining sphinxcontrib-serializinghtml:  30%|▎| 124/407 [16:43<1:40:56, 21.40s/Examining jupyterlab:  31%|█████▏           | 125/407 [16:43<1:40:34, 21.40s/it]Examining backports.shutil_get_terminal_size:  43%|▍| 173/407 [16:43<1:23:27, 21Examining isort:  43%|█████████▍            | 174/407 [16:43<1:23:06, 21.40s/it]failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package hdf5 conflicts for:
h5py -> hdf5[version='1.10.1|1.10.1.*|1.10.2.*|1.8.17.*|1.8.17|1.8.17.*|1.8.18|1.8.18.*|>=1.10.1,<1.10.2.0a0|>=1.10.2,<1.10.3.0a0|>=1.10.3,<1.10.4.0a0|>=1.10.4,<1.10.5.0a0|>=1.10.4,<1.10.5.0a0|>=1.10.4,<1.10.5.0a0|>=1.10.5,<1.10.6.0a0|>=1.10.5,<1.10.6.0a0|>=1.10.5,<1.10.6.0a0|>=1.8.18,<1.8.19.0a0|>=1.8.20,<1.9.0a0',build='mpi_openmpi_*|mpi_mpich_*|mpi_mpich_*|mpi_openmpi_*']
openmc=0.11.0 -> h5py -> hdf5[version='>=1.10.5,<1.10.6.0a0',build='mpi_openmpi_*|mpi_mpich_*']
openmc=0.11.0 -> hdf5[version='>=1.10.5,<1.10.6.0a0']
anaconda==2019.10 -> hdf5==1.10.4=hb1b8bf9_0
hdf5
anaconda==2019.10 -> h5py==2.9.0=py37h7918eee_0 -> hdf5[version='>=1.10.4,<1.10.5.0a0']
pytables -> hdf5[version='1.10.1|1.10.1.*|1.8.17|1.8.17.*|1.8.18|1.8.18.*|>=1.10.1,<1.10.2.0a0|>=1.10.2,<1.10.3.0a0|>=1.10.3,<1.10.4.0a0|>=1.10.4,<1.10.5.0a0|>=1.10.5,<1.10.6.0a0|>=1.8.18,<1.8.19.0a0|>=1.8.20,<1.9.0a0']
Package h5py conflicts for:
anaconda==2019.10 -> h5py==2.9.0[build='py27h7918eee_0|py36h7918eee_0|py37h7918eee_0']
h5py
openmc=0.11.0 -> h5py

**Comment by logic0905** [comment]
Update.
For some reason after command 'conda update --all' it install openmc 0.11.

But two small issues:
1) It don't work (calledprocesserror: Commamd 'openmc' returned non-zero exit status 255)
2) Befor updating it requested to downgraid of anaconda '2019.10-py37_0' to 'custom-py37_1'

So I retun back to V. 0.10  :(

**Comment by paulromano** [comment]
It sounds like you are trying to install OpenMC into a conda environment with the full Anaconda distribution already installed in it. I would suggest trying to first create a [new conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) and then installing OpenMC in that so that it doesn't conflict with other packages.

Regarding the first issue (openmc doesn't run), can you provide more information on how you tried to run it? Have you installed cross sections? If not, please have a look at the section of our user's guide on [cross section configuration](https://docs.openmc.org/en/latest/usersguide/cross_sections.html).

**Comment by logic0905** [comment]
Dear Paulo,
Thank you for your help.
I made a new attempt in another "fresh" environment. And when I try to run a simulation in 0.11 Ver. the program does not start and shows an error:
The 'openmc' command returned a non-zero output status of 255. '.
In 0.10 the same program works. Or at least it don't show any errors and give reasonable results for attenuating the neutron flux in the concrete wall.

Translated with www.DeepL.com/Translator (free version)

**Comment by logic0905** [comment]
Dear Paulo,

After I start to use "official library" (from: https://openmc.org/official-data-libraries/ ) Version 0.11 is starting to work.

So issues was:
1) To avoid a lot of problems better to use separate environment for openmc (and other big package :) ) 
2) Ver. 0.10 and 0.11 use different type of cross sections libraries.

Now I will study features of new version.
Again thanks for your help!
Later I will ask some questions about calculation itself, but in other tread :)

**Comment by paulromano** [comment]
Glad to hear you have it working now! You may want to consider joining our [user's group mailing list](https://groups.google.com/forum/#!forum/openmc-users) for future communication.
