### ISSUE TITLE
Cross section Configuration v0.11.0

### ISSUE THREAD

**Issue by ahmedkmadani** [openmc-dev/openmc#1416]
using Ubuntu 18 opemc v0.11.0, using pre-generated libraries mcnp_endfb70.tar.xz and I'm getting this error what am I missing. Thanks in advance 
![Screenshot from 2019-11-20 23-35-21](https://user-images.githubusercontent.com/4350758/69287561-9188b900-0bee-11ea-9e37-044e9ff632dc.png)

**Comment by paulromano** [comment]
@ahmedkmadani You should put that path on one line with the XML tags:
```xml
<cross_sections>/home/ahmedk/.../cross_sections.xml</cross_sections>
```
and then it should run just fine.

**Comment by ahmedkmadani** [comment]
@paulromano Thanks
