### ISSUE TITLE
volume calc

### ISSUE THREAD

**Issue by makeclean** [openmc-dev/openmc#1422]
In volume calc mode OpenMC segfaults from HDF5 when writing 0.0's as volumes. MWE incoming

**Comment by paulromano** [comment]
@makeclean I tried to reproduce by setting a bounding box completely outside a cell/material so that it would produce a 0.0 volume, but it didn't segfault. Can you please elaborate on what you ran that resulted in a segfault?

**Comment by paulromano** [comment]
Maybe this was a duplicate of #1296 and #1360 (which was fixed in #1361)? Closing as I'm not able to reproduce. Please feel free to reopen if you are still seeing issues with volume calcs.
