### ISSUE TITLE
Plotting in JupyterHub

### ISSUE THREAD

**Issue by deanforrest** [openmc-dev/openmc#1438]
I'm using the [Modeling Hexagonal Lattices](https://openmc.readthedocs.io/en/stable/examples/hexagonal.html) example to test out JupyterHub functionality but it will not perform inline plotting in the Jupyter notebook.
After running In 9 in the example:

`p = openmc.Plot.from_geometry(geom)`
`p.color_by = 'material'`
`p.colors = colors = {`
 `   water: 'blue',`
`    fuel: 'olive',`
 `   fuel2: 'yellow'`
`}`
`p.to_ipython_image()`

I get the following error:
`---------------------------------------------------------------------------`
`CalledProcessError                        Traceback (most recent call last)`
`<ipython-input-9-1cc877228d57> in <module>`
`      6     fuel2: 'yellow'`
 `     7 }`
`----> 8 p.to_ipython_image()`

`~/anaconda3/envs/openmc11/lib/python3.6/site-packages/openmc/plots.py in to_ipython_image(self, openmc_exec, cwd, convert_exec)`
`    705 `
`    706         # Run OpenMC in geometry plotting mode`
`--> 707         openmc.plot_geometry(False, openmc_exec, cwd)`
`    708 `
`    709         # Convert to .png`

`~/anaconda3/envs/openmc11/lib/python3.6/site-packages/openmc/executor.py in plot_geometry(output, openmc_exec, cwd)`
 `    49 `
 `    50     """`
`---> 51     _run([openmc_exec, '-p'], output, cwd)`
`     52 `
`     53 `

`~/anaconda3/envs/openmc11/lib/python3.6/site-packages/openmc/executor.py in _run(args, output, cwd)`
`     28     if p.returncode != 0:`
`     29         raise subprocess.CalledProcessError(p.returncode, ' '.join(args),`
`---> 30                                             ''.join(lines))`
`     31 `
`     32 `
`CalledProcessError: Command 'openmc -p' returned non-zero exit status 255.`

I'm not sure if this a Conda environment error, server error, or an issue with OpenMC.

**Comment by rockfool** [comment]
I am not sure the cause of this issue if you could not upload your detailed jupyter notebook script.
This error msg seems to indicate that input files (*.xml) are not generated correctly before running "openmc -p". I guess you did not export geometry.xml and materials.xml before running "p.to_ipython_image()".

**Comment by rockfool** [comment]
I tested the above example, and it was working well to reproduce the plotting in Ln [9]. 
So this issue is not caused by OpenMC itself. Could you please confirm that you installed the right version of openmc and python api? The error msg "Command 'openmc -p' returned non-zero exit status 255." shows that input files (*.xml) are not genereated correctly before plotting. Please check the geometry.xml and materials.xml in your working directory.

**Comment by deanforrest** [comment]
The environment is using Python 3.6 and OpenMC 0.11.0, and I have confirmed that all the xml files have generated with the right contents and permissions. I am able to execute the openmc -p and create the corresponding ppm file using the terminal in the working directory, but JupyterHub is not able to. 

This seems to be an issue with JupyterHub and not the OpenMC installation. Do you have any suggestions for the JupyterHub installation?

**Comment by deanforrest** [comment]
Alright, so everything works well with Jupyter itself, not the hub server. I'll close the issue as its unrelated to OpenMC, but any further suggestions for JupyterHub would be appreciated.
