### ISSUE TITLE
Fixed source calculations should generate source particles at transport time

### ISSUE THREAD

**Issue by simondrichards** [openmc-dev/openmc#1446]
This issue is added in response to a requirement from @Shimwell and @ukaea.

In an eigenvalue calculation we need to iterate over a set of batches, and the source particles for each batch need to be stored in a source bank at the start of each batch.

In a fixed source calculation we don't need to iterate over batches, instead we can just run a single batch which may contain a very large number of source particles. Storing all of the source particles at the start of the calculation is unnecessary, may require a lot of memory, and places a memory restriction on the number of particles which we can simulate. It is more appropriate in fixed source calculation to sample source particles as and when they are needed at transport time. This deprecates the need for the source history bank in fixed source calculations.

This issue is therefore to remove the need to store source particles in fixed source calculations, sampling them instead when they are required at transport time.

I welcome comments on this issue, and it is something which my collaborators or I plan to work on shortly.

**Comment by makeclean** [comment]
note this is related (duplicate?) of #1364

**Comment by simondrichards** [comment]
Thanks @makeclean, you are correct.

Have you already created issues for the other tasks we were discussing yesterday?

**Comment by paulromano** [comment]
Hi @simondrichards! Nice to have you as part of the community. I'm going to go ahead and close this issue since we all agree it's a duplicate. Mind if I assign you on the other issue?

**Comment by simondrichards** [comment]
I'm happy for you to assign me on #1364 @paulromano. It may turn out that someone else in our team ends up doing the development.

**Comment by paulromano** [comment]
Either way is fine -- at least by assigning you others will know that someone is already working on it. Thanks!
