### ISSUE TITLE
Proposal: use clang-format for C++ formatting

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1463]
As our development community continues to increase in size, we risk spending more and more time worrying about consistent styling in our code base. One way to easily reduce this burden is to use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to apply a consistent style automatically. Myself and others have adopted this for the [ENRICO](https://github.com/enrico-dev/enrico) coupling project and it's worked out very well. We have a `.clang-format` file in the root directory of the repository that lists the rules for formatting. Then, each developer sets up their editor to automatically run clang-format when saving C++ files. This ensures that when pull requests come in, there is no need to review the style itself -- reviewers can focus on the technical content. I'd like to propose adopting this for OpenMC. We can do it in two stages:

- [x] Have a PR that just adds the .clang-format file to the repo. That is, any arguments over what style to adopt would happen as part of this PR.
- [x] At an appropriate point in time (when the number of outstanding PRs is low perhaps), we can run clang-format on the whole repo to get everything consistently formatted.

**Comment by paulromano** [comment]
Finished in #1868

**Comment by shimwell** [comment]
Just to mention there is a Clang pre-commit https://github.com/pre-commit/mirrors-clang-format that could automate clang format for developers that want to install [pre-commit](https://pre-commit.com/hooks.html)
