### ISSUE TITLE
Adding elements by name rather than symbol

### ISSUE THREAD

**Issue by ChasingNeutrons** [openmc-dev/openmc#1468]
This issue is added in response to a requirement from @Shimwell and @ukaea.

As a matter of convenience, it would be nice to be able to create elements with 'add_element' using their full names, as well as the current method of only being able to use their symbol, i.e., 'Lithium' rather than 'Li'. I will begin working on this shortly.

Any suggestions or thoughts would be much appreciated.

**Comment by Shimwell** [comment]
Currently elements are made from symbols, which is great and concise.

However for those of us that don't score 100% on this guess the element quiz it might be a handy feature ;-) particular as the user base grows

https://www.proprofs.com/quiz-school/story.php?title=chemistry-121-periodic-table-part-1

What do people prefer lower or upper case for the first letter of the full element name

**Comment by paulromano** [comment]
I would just lowercase the passed value and compare it to a lowercased key, so any of the following would work: `Lithium`, `lithium`, `lItHiUm`. Implementation wise, I would store the element names in `openmc/data/data.py` where we other similar data (atomic symbols, e.g.). A tuple would probably suffice, putting a None value up front so that the indexing works right:
```Python
ELEMENT_NAME = (
    None, 'Hydrogen', 'Helium', 'Lithium', ...
)
```

**Comment by smharper** [comment]
A dictionary of element name to symbol would allow us to support multiple spellings of each element name. Then we could accept either "aluminum" or "aluminium" to meet the needs of our international user base :wink:

Similarly: cesium and caesium.

**Comment by paulromano** [comment]
Good idea @smharper. I've had arguments with my wife (who is not from the US) about aluminum vs aluminium, haha.

**Comment by Shimwell** [comment]
"aluminum" / "aluminium" and others is much appreciated
