### ISSUE TITLE
Enrichment of an isotope in any element

### ISSUE THREAD

**Issue by Mikolaj-A-Kowalski** [openmc-dev/openmc#1470]
This is yet another issue related to requirements from @Shimwell and @ukaea.  

The required functionality is: 
"Arbitrary isotopes should be able to be enriched and the remaining atom fraction shared between the other natural isotopes with a natural abundance proportionally to their natural abundance." 

My plan is to modify the Element.expand in Python API by adding an additional optional argument "enrichment_target", which will be a string that will specify the isotope that needs to be enriched. Because, the new treatment that preserves other isotopes proportional to their natural abundance is not compatible with the current treatment for uranium, if "enrichment" is provided without the "enrichment_target" the current procedure will be applied. 

That being said in current implementation if expand function is called with "enrichment"  for an element that is not Uranium, then Uranium isotopes are added to the mixture. Maybe I should add a check and print error message when the "uranium enrichment procedure" is to be applied and the element that is not Uranium? 

There is also a question if the "enrichment" should be interpreted as weight or atomic %. Should I add an additional argument to specify that? What would be a better default weight or atomic. I am inclined to go with weight because it is consistent with the current procedure for uranium.     

BTW Hello. 
Thanks for your help and comments.

**Comment by Shimwell** [comment]
This will be a great feature for those of us in fusion where we have enriched lithium 6 in breeder materials like Li4SiO4

Keeping the default enrichment_target = U sounds like a good method of preserving current functionality while allowing others isotopes to be enriched

Personally I would love to see atomic % included if it is not too much trouble.

When there are just the two natural isotopes like Lithium and Uranium then finding the weight or atomic % is easy.

When there are elements with 3 or more isotopes and one is enriched I guess the other two should be present proportional to their original natural fraction or some other rule.

That addition of Uranium to the mixture sounds worrying, not sure if that is intended. Wondering if the unit tests covert this use case.

**Comment by paulromano** [comment]
A few comments here:

- There is a check in `Material.add_element` for the combination of (not U) + (enrichment specified), in which case a `ValueError` is raised.
- I agree that in the case of two natural isotopes, there is a single correct answer.
- In any other case, I'm not aware of a general solution. It really depends at that point _how_ the material was enriched. For example, with LWR fuel, there is a basic question of whether the higher enrichment of U was obtained by blending natural U with weapons HEU or through actual enrichment of the natural U. The two are obviously not equivalent. Right now, the assignments of isotopes for U is based on a correlation in https://doi.org/10.2172/5561567. To be honest, I'm not sure what fuel the correlation there is based on, but we chose this to be consistent with SCALE.

Other than Li and U, are there other use cases that either of you are aware of? If those are the only cases, then I think it's ok to have our current special treatment for U plus a more general treatment for an element with 2 naturally occurring isotopes.

**Comment by Mikolaj-A-Kowalski** [comment]
Sorry I should have been more clear.  I meant that the addition of the extra isotopes happens in `Element.expand`. I don't know how likely it is that anybody will use it outside `Material.add_element`, but adding an exception or at least a note in a docstring may save somebody a headache down the line.

I will also aim to add flag for atomic/weight enrichment as yet another argument to `Element.expand` and `Material.add_element`.

**Comment by paulromano** [comment]
@Mikolaj-A-Kowalski Ah yes, you're right. I think the natural solution is to just move that check to `Element.expand` rather than being in `Material.add_element` which ensures that it is caught in either case.

**Comment by Shimwell** [comment]
> A few comments here:
> 
>     * There is a check in `Material.add_element` for the combination of (not U) + (enrichment specified), in which case a `ValueError` is raised.
> 
>     * I agree that in the case of two natural isotopes, there is a single correct answer.
> 
>     * In any other case, I'm not aware of a general solution. It really depends at that point _how_ the material was enriched. For example, with LWR fuel, there is a basic question of whether the higher enrichment of U was obtained by blending natural U with weapons HEU or through actual enrichment of the natural U. The two are obviously not equivalent. Right now, the assignments of isotopes for U is based on a correlation in https://doi.org/10.2172/5561567. To be honest, I'm not sure what fuel the correlation there is based on, but we chose this to be consistent with SCALE.
> 
> 
> Other than Li and U, are there other use cases that either of you are aware of? If those are the only cases, then I think it's ok to have our current special treatment for U plus a more general treatment for an element with 2 naturally occurring isotopes.

Yep, perhaps it is bet to just get the enrichment function working for any straight forward elements with 2 natural isotopes. Perhaps return a error if anyone tries to enrich an element with three or more natural isotopes.

I guess there might also be a mismatch between available cross sections in the corss_section.xml and in nature, could this complicate things

**Comment by paulromano** [comment]
Re: missing cross sections, I believe such cases should be rare nowadays, so I'm not particularly worried about that possibility.

**Comment by simondrichards** [comment]
In addition to Li and U, I guess B is another likely use case. Fortunately this is another case with only two naturally-occurring isotopes, so the proposed method should work.

**Comment by paulromano** [comment]
Completed in #1503
