### ISSUE TITLE
Model.run doesn't pick out correct statepoint when trigger is being used

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1473]
A pull request describing this and proposing an initial (incomplete) solution was given in #1046

**Comment by alex-lyons** [comment]
I've followed Paul's suggestions in PR #1046.
As a bonus, the Model class now has an attribute 'statepoint' which contains the name of the last written statepoint file after Model.run() completes. This will be useful particularly for trigger runs when the number of batches isn't known in advance.
Writing a regression test for it.

**Comment by Shimwell** [comment]
I think this issue can be closed now
