### ISSUE TITLE
Material Cell Inventory Calculations 

### ISSUE THREAD

**Issue by Mikolaj-A-Kowalski** [openmc-dev/openmc#1505]
This is another issue related to requirements form @Shimwell and @ukaea. 
Me and @ChasingNeutrons shall be working on it. 

The goal is to: 

1. Provide easier access to the "volume" attribute of a cell
2. Simplify stochastic volume calculations so it is not required to provide materials 
3. Allow to calculate total number of atoms from known (pre-determined by the user) volume of a material cell 

Our plan is to: 

1. Currently it is possible to set and get volume of the cell by getter and setter, so nothing can be done in this regard. However, it might be useful to add `Volume` entry to the output of ``Cell.__repr__()``, so it is more explicit whether the volume of the cell was set. This may be superficial change. We would appreciate a feedback if it is really needed. Also please correct me if I'm wrong, but the setter for volume does not check the range. It seems that it is possible to create a cell with -ve volume. We plan to add an exception to prevent it.   
      
2. If somebody is interested only in the volumes of the cells and wants to perform stochastic calculation without any materials most natural is to fill all `material` cells with `void`. It might be worth to add an example of creating a `void` cell to Section 6.2 (Cells) in the User Guide. Currently the fact that if no ``fill`` is provided to a cell, it will be exported to xml with "void" material fill is not stated in the Section 6.2. I found the information about it in the `Examples`.   
      
3. We aim to add a getter for ``_atoms`` to the cell.  
      
We will appreciate any comments.

**Comment by paulromano** [comment]
No immediate comments on my behalf -- this all sounds very reasonable!

**Comment by Mikolaj-A-Kowalski** [comment]
Merged in PR #1523.
