### ISSUE TITLE
Feature addition: Surface source

### ISSUE THREAD

**Issue by ypark234** [openmc-dev/openmc#1509]
Having the capability of banking particles crossing user-defined surfaces and reading them in different simulations as a source (similar to MCNP's SSW/SSR cards) would be useful in designing localized geometry without having to run the full geometry every time the local design changes.
Related paper: Paul P. H. Wilson and Patrick Snouffer, "A MONTE CARLO SURFACE SOURCE METHOD FOR ADVANCED TEST REACTOR EXPERIMENT PROTOTYPING", PHYSOR2010 (2010)

I am currently working on it, and I will create a relevant PR in the future.
Any comments or suggestions would be much appreciated!

**Comment by paulromano** [comment]
Thanks for adding the issue to track this, and look forward to seeing the PR!
