### ISSUE TITLE
MGXS mode doesn't work with interpolation temperature method

### ISSUE THREAD

**Issue by dryuri92** [openmc-dev/openmc#1512]
> ERROR: MGXS Library does not contain cross sections for fuel at temperatures
        that bound 1027.000000

kTs list of data contains temperatures: 300, 600, 900, 1200, 1800, 2100 K
The problem doesn't work with mgxs library when temperature method is interpolation. This mistake take place for both cases temperature of cell is equal one from the "kts" list of mgxs.h5 or doesn't.

**Comment by nelsonag** [comment]
Thanks again for this @dryuri92!
