### ISSUE TITLE
Material.remove only removing one isotope

### ISSUE THREAD

**Issue by Shimwell** [openmc-dev/openmc#1532]
Hi all, 

I spotted what might be a bug in the openmc.Material.remove_nuclide() method

If there is a material with multiple entries for the same isotope then only the first matching nuclide is removed due to the [break line in the material.py code ](https://github.com/openmc-dev/openmc/blob/2160e6b156f8e01331c9177881570ef754399bde/openmc/material.py#L439)

This current behavior can be a little unpredictable as users might not know which nuclide in the material is going to be removed.

It probably was not a problem due to the construction of materials via add_nuclide and add_element. However multiple isotopes within the same occurs material often occur when mixing materials (recently implemented). Perhaps this remove_nuclide method should remove all matching nuclide from the material?

I can submit a PR for this behavior change if people think remove_nuclide should remove all entries of the nuclide from the material instead of just the first one?

**Comment by paulromano** [comment]
I'll fix this in the open PR I have (#1531)

**Comment by Shimwell** [comment]
Thanks for fixing this
