### ISSUE TITLE
optional writing of source for fixed_source simulations

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#1537]
A recent PR #1518 implemented a new bank model which is a nice improvement for fixed source simulations. Thanks @alex-lyons 

The new bank model no longer exports source information like particle x,y,z, E and u,v,w to the statepoint file. This is great as we often run simulation with fixed_source mode with many particles and the automatic writing of this data to the statepoint file was generating large files and taking a long time.

However it would be nice to be able to optinally add source information in some cases so we can do things like plot the source locations, distributions etc

So I have been looking at the documentation the and it appears we have a `sourcepoint` setting called `write` in` openmc.settings ` that should control if we write the source to the h5 file or not. 

https://docs.openmc.org/en/latest/pythonapi/generated/openmc.Settings.html

Then there is an additional check in the simulations.cpp that prohibit writing of source points for fixed source.

```
if (contains(settings::sourcepoint_batch, simulation::current_batch)
        && settings::source_write && !settings::source_separate) {
      bool b = (settings::run_mode == RunMode::EIGENVALUE);
```

https://github.com/openmc-dev/openmc/blob/571ed3b6ab449e555fc9c8452106425d26b19bd3/src/simulation.cpp#L367

Perhaps we should just use the `openmc.settings sourcepoint write` to determine if source points should be writing and not involve the simulation type.

https://github.com/Shimwell/openmc/blob/8b8392f94326a965de47d3ba6fb010a9bbb8f922/src/simulation.cpp#L366-L367

Unfortunately this would not be enough to write the source points to the statepoint file and some additional code is probably needed in the bank model but I get a bit lost and was wondering if anyone has any suggestions or perhaps this is not an issue for anyone else?

**Comment by Shimwell** [comment]
Just in case anyone else is looking for a solution to this there are a few work arounds, here is an example of getting data points by pretending to perform an eiganvalue simulation

```

import xml.etree.ElementTree as ET

import h5py
import openmc

sett = openmc.Settings()
sett.run_mode = "eigenvalue" # this will fail but it will write the inital_source.h5 file first
sett.particles = 10
sett.batches = 3
sett.inactive = 0
sett.write_initial_source = True

# Create a DT point source
source = openmc.Source()
source.space = openmc.stats.Point((0, 0, 0))
source.angle = openmc.stats.Isotropic()
source.energy = openmc.stats.Muir(kt=10e3) # might want to change the 10KeV plasma temperature
sett.source = source

sett.export_to_xml()

# this just adds write_initial_source == True to the settings.xml
tree = ET.parse("settings.xml")
root = tree.getroot()
elem = ET.SubElement(root, "write_initial_source")
elem.text = "true"
tree.write("settings.xml")

# no materials needed
openmc.Materials([]).export_to_xml()

# simple geometry
outer_surface = openmc.Sphere(r=100, boundary_type='vacuum')
cell = openmc.Cell(region=-outer_surface)
universe = openmc.Universe(cells=[cell])
geom = openmc.Geometry(universe)
geom.export_to_xml()

# this will crash hence the try except loop, but it writes the inital source.h5
try:
    openmc.run()
except:
    pass

# Read the intial_source.h5 and pull the coordinates from the dataset
filename = "initial_source.h5"
x = []
y = []
z = []
dir_x = []
dir_y = []
dir_z = []
e = []
with h5py.File(filename, "r") as f:
    dataset = f["source_bank"]
    for data in dataset:
        x += [data[0][0]]
        y += [data[0][1]]
        z += [data[0][2]]
        e += [data[2]]
        dir_x = [data[1][0]]
        dir_y = [data[1][1]]
        dir_z = [data[1][2]]

print('neutron x birth positions', x)
print('neutron y birth positions', y)
print('neutron z birth positions', z)
print('neutron dir_x birth positions', dir_x)
print('neutron dir_y birth positions', dir_y)
print('neutron dir_z birth positions', dir_z)
print('neutron birth energy', e)
```

**Comment by paulromano** [comment]
Just a thought -- one of the simplest approaches here might be to expose the `sample_external_source` C++ function to Python via `openmc.lib`. This would give a power user the ability to sample the source as they wish completely separate from a simulation.

**Comment by shimwell** [comment]
I am keen understand how to contribute to the openmc.lib so I had a little go and am wondering if I am on the right track.

Would core.py need these extra lines
https://github.com/shimwell/openmc-1/blob/f7b968663c098848e5f5da0f25ac50b61f3597d6/openmc/lib/core.py#L93-L95

Also would core.py need a function link this
https://github.com/shimwell/openmc-1/blob/f7b968663c098848e5f5da0f25ac50b61f3597d6/openmc/lib/core.py#L102-L111

**Comment by pshriwise** [comment]
We'll need these changes, but there's a bit more to it. We'll need to expose the function through the CAPI in `capi.h` and add a wrapper function `openmc_sample_external_source` that matches the C-style pattern we have in place for errorcodes and such.

**Comment by shimwell** [comment]
Is [this](https://github.com/shimwell/openmc-1/blob/254884576ea65705138d7d6742e53ed719ab2908/include/openmc/capi.h#L124) all that is needed to expose the function through the CAPI in ```capi.h```
