### ISSUE TITLE
Reference publication is outdated.

### ISSUE THREAD

**Issue by cjwyett** [openmc-dev/openmc#1548]
Could we please have a new publication to cite? 

Romano 2015 contains a lot of redundant/now-incorrect information.

**Comment by paulromano** [comment]
Fair point -- unfortunately we don't have a more recent overview paper. There was a special Monte Carlo codes session planned for the SNA+MC 2020 conference that might have resulted in a new paper, but it's unclear what will happen with the conference proceedings because of the pandemic.

**Comment by paulromano** [comment]
As an alternative to citing the 2015 Annals paper, you can cite a specific version of OpenMC using Zenodo:
https://doi.org/10.5281/zenodo.591748
