### ISSUE TITLE
Error in processing nuclear data from ENDF to hdf5

### ISSUE THREAD

**Issue by AnderGray** [openmc-dev/openmc#1564]
I'm trying to process an endf file to hdf5. The endf file was produced by [sandy](https://github.com/luca-fiorito-11/sandy).

The following code:
```python
data = openmc.data.IncidentNeutron.from_njoy(fileIn)
data.export_to_hdf5(fileOut, 'w')
```
produces the following error:
```python
data = openmc.data.IncidentNeutron.from_njoy(fileIn)
  File "MyDir/python/2.7.8/lib/python3.6/site-packages/openmc/data/neutron.py", line 816, in from_njoy
    make_ace(filename, temperatures, **kwargs)
  File "MyDir/python/2.7.8/lib/python3.6/site-packages/openmc/data/njoy.py", line 342, in make_ace
    zsymam = ev.target['zsymam']
KeyError: 'zsymam'
```

`fileIn` and `fileOut` are just strings for the filenames of my input endf file and my output h5. Has anyone encountered this problem before/ know of a solution?

I have tried giving a temperature but the error is the same: 
```python
 data = openmc.data.IncidentNeutron.from_njoy(fileIn, temperatures=293.6)
```

**Comment by paulromano** [comment]
Thanks for reporting this @AnderGray. Would you be able to share the ENDF file it crashes on? I have some other fixes in the works that I was just about to submit a pull request for and can include a fix for this too.

**Comment by AnderGray** [comment]
[Fe54-1.zip](https://github.com/openmc-dev/openmc/files/4635753/Fe54-1.zip)

I may have made a mistake though, this might be an ACE file

**Comment by paulromano** [comment]
@AnderGray A fix for this was just merged. I've confirmed that I can successfully run `from_njoy` on your file. Let me know if you have any further issues with the files produced from sandy.
