### ISSUE TITLE
Converting multiple temperature containing ACE file to hdf5 using export_to_hdf5

### ISSUE THREAD

**Issue by khurrumsaleem** [openmc-dev/openmc#1575]
Hello All,

I am writing to report an issue I am facing right now. I generated ACE files using data.njoy.make_ace. I am using 25 different temperature values. Using the generated ACE files, i try to convert it to HDF5 using export_to_hdf5 only the first temperature value (250 K in my case) is exported. rest of the temperature values are not even read in. i check with <nuclide>.kTs and <nuclide>.temperatures. Is this the normal behavior or is it a bug?

By the way, i tried converting using XSDIR file also and ran into an error saying 

Converting 1001.01c (ACE) to H1 (HDF5)
Converting 1001.02c (ACE) to H1 (HDF5)
/home/saleem/.local/lib/python3.8/site-packages/openmc/data/neutron.py:283: UserWarning: Tried to add cross sections for MT=1 at T=293K but this reaction doesn't exist.
  warn("Tried to add cross sections for MT={} at T={} but this "
/home/saleem/.local/lib/python3.8/site-packages/openmc/data/neutron.py:283: UserWarning: Tried to add cross sections for MT=101 at T=293K but this reaction doesn't exist.
  warn("Tried to add cross sections for MT={} at T={} but this "
Traceback (most recent call last):
  File "/mnt/e/openmc/scripts/openmc-ace-to-hdf5", line 126, in <module>
    data.export_to_hdf5(converted[name] + '_1', 'w', libver=args.libver)
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

Any help will be appreciated. Thanks

**Comment by AI-Pranto** [comment]
Two days ago I had the same problem also  for O16 at 323.6 K temperature . Did you get ACE file at 293 K temperature ? ( My guess not)

**Comment by AI-Pranto** [comment]
I think adding multiple temperatures in `openmc.data.njoy.make_ace` is a problem. In my case,
``` python
openmc.data.njoy.make_ace('n-008_O_016.endf', temperatures = [323.6], acer = 'O16.ace', stdout = True)
```
successful. But 
``` python 
openmc.data.njoy.make_ace('n-008_O_016.endf', temperatures = [300 , 323.6], acer = 'O16.ace', stdout = True) 
```
This time I got an error. 
`/home/pranto/anaconda3/envs/openmc811/lib/python3.8/site-packages/openmc/data/neutron.py:278: UserWarning: Tried to add cross sections for MT=1 at T=324K but this reaction doesn't exist.
  warn("Tried to add cross sections for MT={} at T={} but this "
`
It only wrote the ACE file at the first temperature ( 300 K )

**Comment by khurrumsaleem** [comment]
@AI-Pranto in my case ace files are made just fine. it is the conversion of the files to HDF5 that is throwing error.

**Comment by AI-Pranto** [comment]
@khurrumsaleem Have you used `IncidentNeutron.add_temperature_from_ace() ` to append cross sections data to an existing ACE file? 
``` python
x = openmc.data.IncidentNeutron.from_ace('H1.ace')
x.add_temperature_from_ace('ACE file at 293 K')
```

**Comment by khurrumsaleem** [comment]
@AI-Pranto yes i have done that successfully but for that we need separate ace files for each temperature. the problem i have is that all the temperature aces i generate are appended in the same file.

**Comment by AI-Pranto** [comment]
While using `openmc.data.njoy.make_ace()`, I expected that It will write ACE file for different temperatures separately but It didn't! 
My guess is that you have got ACE file only for 250 K temperature, not for all later temperatures. Can you check whether or not you have got ACE file for all input temperatures?

**Comment by khurrumsaleem** [comment]
![output](https://user-images.githubusercontent.com/5681739/83325665-67900d80-a287-11ea-86f3-86f74111b2c5.PNG)

as you can see from the picture all temperature aces are generated successfully.

**Comment by AI-Pranto** [comment]
That' good! It looks like, It doesn't store MT=1, 101 values at multiple temperatures.

**Comment by paulromano** [comment]
If you have an ACE file with multiple tables inside, you can't just pass the filename to `from_ace` or `add_temperature_from_ace` because it will only get the first table in the file by default. What you need to do is the following:
```Python
from openmc.data import ace

lib = ace.Library(ace_filename)
data = openmc.data.IncidentNeutron.from_ace(lib.tables[0])
for table in lib.tables[1:]:
    data.add_temperature_from_ace(table)
```
As you can see, this uses the `Library` class from the `ace` module to load the ACE file so that you have access to each of the individual tables (`lib.tables`). This is how `IncidentNeutron.from_njoy` works (also -- if you can, I would recommend just using `from_njoy`).

**Comment by khurrumsaleem** [comment]
thank you @paulromano. It works as expected.
