### ISSUE TITLE
HDF5 File Format Error with Conda Install and Prebuilt OpenMC Library

### ISSUE THREAD

**Issue by carey-sublette** [openmc-dev/openmc#1582]
I am attempting to do a basic validation of a vanilla openmc install on a Linux distribution but it fails with:
 ERROR: HDF5 data format uses version 3.0 whereas your installation of OpenMC expects version 1.x data.

The install was done with:
 conda config --add channels conda-forge
conda install openmc

The library is the one linked here:
https://openmc.org/official-data-libraries/

And I am just trying to run the basic example to verify the basic setup works.

**Comment by AI-Pranto** [comment]
You received this error because you installed `OpenMC 0.10`. For a quick fix,
`conda uninstall openmc` 
`conda install openmc=0.11 python=3.X`

**Comment by paulromano** [comment]
This was resolved on the user's group. @carey-sublette If you have any further trouble, please let us know.
