### ISSUE TITLE
Fail to run a depletion from previous results

### ISSUE THREAD

**Issue by kingyue737** [openmc-dev/openmc#1608]
I ran a depletion from previous results, but the simulation started from the scratch.

I don't understand why assign None to self.prev_res here. 
https://github.com/openmc-dev/openmc/blob/4ce7df9f5408d7355ef4986e89a102e3b67708bc/openmc/deplete/operator.py#L186
Replacing "None" with "prev_results" seems to fix this problem.

**Comment by drewejohnson** [comment]
Good catch. We don't need this line, since we pass `prev_res` off to the `TransportOperator` above. This incorrectly over-writes that action

**Comment by AI-Pranto** [comment]
Still getting error in openmc-**0.12**
```
File "/home/pranto/anaconda3/envs/openmc12/lib/python3.8/site-packages/openmc/deplete/operator.py", line 215, in __init__
    prev_results[-1].transfer_volumes(geometry)
AttributeError: 'str' object has no attribute 'transfer_volumes'
```

**Comment by drewejohnson** [comment]
I think this is a different error. Did you pass a string file name as `prev_results` or a [`ResultsList`](https://docs.openmc.org/en/latest/pythonapi/generated/openmc.deplete.ResultsList.html#openmc.deplete.ResultsList.from_hdf5)? I linked to the `from_hdf5` class method which should be used rather than `ResultsList("previous_results.h5")`

**Comment by AI-Pranto** [comment]
I passed the previous result file as `prev_results`.
``` python
prev_results = openmc.deplete.ResultsList("depletion_results.h5")
ops = openmc.deplete.Operator(geometry, settings, chain_file, prev_results)
```
Did I miss something, @drewejohnson?

**Comment by drewejohnson** [comment]
Use `ResultList.from_hdf5`

> It is recommended to use from_hdf5() over direct creation.

**Comment by AI-Pranto** [comment]
Got it @drewejohnson. Thanks
