### ISSUE TITLE
Add support for deserialization of custom source

### ISSUE THREAD

**Issue by DanShort12** [openmc-dev/openmc#1621]
The current implementation of a custom source is supported by the user providing a compiled shared object library, which implements the `sample_source` function, having a template providing an array of random seeds and returning a `Particle::Bank`. This is convenient for static sources, where the parametrisation of that source does not change but is less convenient is the source can vary e.g. between sequential runs. In this case the current solution would require the user to recompile their custom source with the new parametrisation and use the new library in the new run.

This Issue suggests to also attempt to dynamically load a `sample_source` function with an additional parameter that accepts a path to a file containing a serialised representation of the parameterised source. The existing function template would still be loadable, to avoid regression effects. This would allow the source to be deserialized before sampling, allowing for a more dynamic approach that does not require recompilation. Docs and tests relating to the custom source would also need to be updated to describe this alternative approach.

I'd be happy to put a PR together for this (assuming there is some availability to review that), but wanted to throw the issue out there first in case there are any comments or alternative suggestions before I get started.

**Comment by DanShort12** [comment]
Of course the name of the new function would have to be different from `sample_source` to allow it to be a c-style function and avoid name mangling. I'd suggest something like `deserialize_sample_source`.

**Comment by makeclean** [comment]
Why not just pass the parametrisation through the input xml (or equivalently through the serialised xml form the python interface)?

On 28 Jul 2020, at 19:50, DanShort12 <notifications@github.com<mailto:notifications@github.com>> wrote:



Of course the name of the new function would have to be different from sample_source to allow it to be a c-style function and avoid name mangling. I'd suggest something like deserialize_sample_source.

**Comment by DanShort12** [comment]
Fair point, I was considering a couple of factors:

1.  A general user might not want to serialise/deserialise to/from XML, in which case they'd have to embed their favoured format within the settings.xml, with appropriate escaping.
2.  If the serialisation is passed into settings.xml as XML then the schema of the serialised source and the settings.xml get merged, so again unless the serialised representation is escaped there may be some unexpected interactions.

That being said, from the perspective of OpenMC the proposed new element in the settings.xml would have a string-like value so a user could in principle use whatever string they like, whether that be a file path of a direct injection of the serialised source. Perhaps a compromise would be to give that element a name that is not so specific (`serialised_source` rather than `serialised_source_path`, for example), then the implementation in OpenMC is agnostic to how the user wants to perform their serialisation/deserialisation routines?
