### ISSUE TITLE
[Feature request] Non-uniform cylindrical meshes

### ISSUE THREAD

**Issue by GiudGiud** [openmc-dev/openmc#1653]
Those would be convenient to generate MGXS for 2D-RZ calculations mostly. Those could remain common for cylindrical reactors with highly heterogeneous geometries (TMSR, PB-FHR for example).
Also for tokamaks?

**Comment by nelsonag** [comment]
I’d agree with this. Came across the need for this in a particular reactor analysis I’m working on now. The model of interest has R-Z symmetry that such a mesh is best suited for.
