### ISSUE TITLE
sampling uniformly distributed source in sphere or cylinder?

### ISSUE THREAD

**Issue by liangjg** [openmc-dev/openmc#1665]
A user reported unexpected results when using spherical/cylindrical external sources. It turns out the spatial distribution “cylindrical” and “spherical” are not implemented for uniformly distribution sampling, i.e.
``` python
r_dist = openmc.stats.Uniform(0., 1.)
phi_dist = openmc.stats.Uniform(0.0, 2*pi)
z_dist = openmc.stats.Uniform(-1., 1.)
spatial1 = openmc.stats.CylindricalIndependent(r_dist, phi_dist, z_dist, origin=(0., 0., 0.))
```
is not giving a uniformly distributed source in cylinder, as explained here: https://mathworld.wolfram.com/DiskPointPicking.html. It is similar for sphere (https://mathworld.wolfram.com/SpherePointPicking.html).

This is the user's issue because he `Cylindrical/Spherical` features were designed for specifying independent distributions in `r-, phi-, and z-coordinates` or `r-, theta-, phi-coordinates` instead of  sampling from cylinder or sphere. I just wanted to make a note here. It would be great if sampling from cylinder or sphere is supported in openmc someday.

**Comment by gridley** [comment]
Just a note that might be obvious already: for the cylinder example you've presented here, they should be able to obtain uniform sampling by using instead:

```
r_dist = openmc.stats.Legendre(0., 2.0)
```

As for sampling from the sphere, I don't think that's possible at the moment since there's not support for a cosine distribution as you need for the polar variable.

**Comment by liangjg** [comment]
@gridley thanks for your advice for the cylinder sampling!

**Comment by paulromano** [comment]
@liangjg We do have the ability to do [custom sources](https://docs.openmc.org/en/latest/usersguide/settings.html#custom-sources), so it wouldn't be very difficult to write a source function that implements a method for sampling uniform points inside a sphere.

**Comment by liangjg** [comment]
> Just a note that might be obvious already: for the cylinder example you've presented here, they should be able to obtain uniform sampling by using instead:
> 
> ```
> r_dist = openmc.stats.Legendre(0., 2.0)
> ```
> 
> As for sampling from the sphere, I don't think that's possible at the moment since there's not support for a cosine distribution as you need for the polar variable.

@gridley  Just wanted to try this approach but found it is likely not working because:
1. `Legendre` distribution is not yet implemented in OpenMC: `openmc.stats.Legendre` can not be exported to XML and openmc is not recognizing `Legendre` distribution right now.
2. Probability function for distance `r` from the center of a point picked at random in a unit disk should be `p(r) = 2r`, so if second-order `Legendre` is going to be used, the coefficients should be `0.0, 4/3` rather than `0.0, 2.0`? However, the next issue is how to sample from Legendre Polynomials (within a range)...

@paulromano I guess [custom sources](https://docs.openmc.org/en/latest/usersguide/settings.html#custom-sources) is currently the approach for sampling inside both a cylinder and sphere. Thanks.

**Comment by gridley** [comment]
Ah yeah... of course it wouldn't naturally use the radius. Makes sense.
