### ISSUE TITLE
Add DAGMC to Dockerfile?

### ISSUE THREAD

**Issue by Shimwell** [openmc-dev/openmc#1709]
The Dockerfile is a nice minimal set of requirements for OpenMC. I'm just wondering if we can add a DAGMC onto that. Perhaps this goes beyond the minimal set but I was keen to ask as I guess these codes are often used together.

Happy to make a PR if this idea is acceptable

**Comment by Shimwell** [comment]
Just wanted to mention that this could be done by adding another Dockerfile to the repo or alternatively adding some arguments to the docker build command and some conditional RUN commands in the existing Dockerfile

**Comment by pshriwise** [comment]
I'm biased, but definitely for this. :smile: 

I'd vote for the option of adding arguments to the build command for some of our optional dependencies.

**Comment by paulromano** [comment]
@Shimwell If you're the one doing the work to figure it out, I have no objections!

**Comment by Shimwell** [comment]
Super I shall look into adding optional DAGMC via arguments to the Dockerfile

**Comment by pshriwise** [comment]
Yes, by all means.

**Comment by Shimwell** [comment]
Ok I have had a quick practice making these build-arg driven docker images. 

I updated the example repository with a new argument accepting dockerfile and two new yml files that build the docker file differently using the build-args

https://github.com/Shimwell/example-dockerhub-upload

I would plan to do the optional DAGMC in a similar manner unless there are any objections

**Comment by pshriwise** [comment]
Looks very nice to me!

**Comment by Shimwell** [comment]
Great, thanks for the feedback, I have got started on this issue over on this fork branch 
https://github.com/Shimwell/openmc/tree/adding_optional_dagmc_to_docker

I guess we want the DAGMC without FORTRAN, so I have been looking at the recent DAGMC [PR](https://github.com/svalinn/DAGMC/pull/687/files) 
I was also assuming that we want MOAB compiled with cmake instead of autoreconf

Then I was wondering about Embree but thought it might be best to take advice on including that or not. What do you think @pshriwise , you are the best person to decide this?

I am getting closer with the Dockerfile and it looks nearly ready but appears to be not finding things (hdf5, moab) occasionally. I shall have another go soon.

**Comment by makeclean** [comment]
The Embree thing is a great idea (double down) now the hard part will be running it, @pshriwise remind me if I'm wrong, but there is a bunch of stuff that will work without AVX512 and a bunch that wont. The issue here being if the person compiling it has AVX512, then the person running it doesnt? E.g. people on AMD chips or people with older Intel i5/i7's, so maybe lowest common denominator, AVX2, would that confer any benefit? Threaded OBB building is nice

**Comment by pshriwise** [comment]
I'd be behind that as well @Shimwell. And good point, @makeclean. I think you're right about sticking with AVX2 in the Embree build. I think setting the `-DEMBREE_ISA_AVX2=ON` flag in its configure step should do the trick.

**Comment by pshriwise** [comment]
I was thinking about this more just now.

I’m not at all confident that the serial ray tracing performance will be maintained across architectures, but using Embree through Double-Down still provides much better scalability for many threads vs the native MOAB ray tracer. So I’d still say it’s worth it to provide it as an option here. Plus, as @makeclean said, threaded building of the BVH it provides is a nice perk. 🙂

**Comment by Shimwell** [comment]
DAGMC has a release planned so I guess the dockerfile shoult target the release when it is available.
 https://github.com/svalinn/DAGMC/pull/712

**Comment by paulromano** [comment]
Completed in #1725
