### ISSUE TITLE
Trouble with executing make when installing OpenMC from source

### ISSUE THREAD

**Issue by connoramoreno** [openmc-dev/openmc#1728]
Foreword: I'm a Mac user on Big Sur.

I'm having an issue with executing `make` while building OpenMC (instructions: https://docs.openmc.org/en/stable/usersguide/install.html#obtaining-the-source). I'm getting the following error:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:97:15: fatal error: 
      'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/libopenmc.dir/src/mesh.cpp.o] Error 1
make[1]: *** [CMakeFiles/libopenmc.dir/all] Error 2
make: *** [all] Error 2
```
and if I'm understanding what I'm finding online correctly, the issue has to do with not having the `/usr/include` folder (as in, it's entirely absent from my system). The solution i've been able to find online (https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave) says to download the Xcode command line tools (which I have) and then open the package
`/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` 
or equivalent (i'm on Big Sur) to install SDK headers. However, this package isn't present on my system as the instructions say it should be. Any help would be much appreciated! Please let me know if further information is required. Thanks!

**Comment by paulromano** [comment]
Hi @connoramoreno. I'm not a macOS user so unfortunately I don't have any good ideas to offer, other than to ping a few of my colleagues who may have a better idea. @amandalund @jtramm

**Comment by makeclean** [comment]
Can you compile anything? Can you compile a something like

```
#include <iostream>
int main() {
  std::cout << "hello world!" << std::endl;
  return 0;
}
```
Have you installed xcode compilation tools? 
```
xcode-select --install
```
Also, to get the most out of OpenMC on a Mac, I would recommend installing Brew, then installing the gnu compilers from there, as then you will get threading support.

**Comment by connoramoreno** [comment]
@makeclean I switched the Brew (was using MacPorts before) and OpenMC built successfully. Thanks for your help!
