### ISSUE TITLE
Event mode fails for fixed source problems without any multiplying media

### ISSUE THREAD

**Issue by gridley** [openmc-dev/openmc#1760]
OK, so, particles get destroyed after each one is run in history mode. In event mode though, the particle state never gets destroyed, so everything need to be manually reset after the particle dies. At the moment, in event+fixed source mode, it is possible for the `n_event_` member of a particle to increase arbitrarily until `MAX_EVENTS` gets hit as this is not reset manually.

You can easily reproduce this by generating the fixed source regression test, deleting the uranium from the problem, and running many generations. The simulation eventually dies as all particles get maxed out `n_event_` values and instantly die at the start of each generation. You have to delete the uranium because this causes some multiplication reactions which do reset `n_event_` in the calls to `event_revive_from_secondary` that result.

**Comment by paulromano** [comment]
Fixed in #1761.
