### ISSUE TITLE
WARNING appears when modeling a reactor

### ISSUE THREAD

**Issue by ternence6** [openmc-dev/openmc#1765]
when running openmc-0.12.1-dev to do ‘eigenvalue’ calculations for the model like mpower,the result is as follows:
 `====================>     K EIGENVALUE SIMULATION     <====================

  Bat./Gen.      k            Average k
  =========   ========   ====================
        1/1    0.27709
 WARNING:  WARNING: The shared fission bank is full. Additional fission sites created in  this generation will not be banked.`
And in the end,'Segmentation fault(core dumped)'
At the same time,the plotting mode works as usual.
Does anyone ever face the similar problem?

**Comment by gridley** [comment]
This will happen if k is getting near 3 for your model. Is it?

**Comment by gridley** [comment]
How many source neutrons did you run? This would be likely if you ran a very small number.

**Comment by ternence6** [comment]
> How many source neutrons did you run? This would be likely if you ran a very small number.
```
settings.particles = 10000
settings.batches = 1000
settings.inactive = 200
```

**Comment by gridley** [comment]
Looks good, can you give more info about your input?

**Comment by ternence6** [comment]
`z_cylinder0 = openmc.ZCylinder(r=115)
z_cylinder1 = openmc.ZCylinder(r=121)
z_cylinder2 = openmc.ZCylinder(r=121.5)
z_cylinder3 = openmc.ZCylinder(r=156)
z_cylinder4 = openmc.ZCylinder(r=170,boundary_type='vacuum')
#  fuel rod and UO2Gd pin
z_cylinder5 = openmc.ZCylinder(r=0.409575)
z_cylinder6 = openmc.ZCylinder(r=0.4175)
z_cylinder7 = openmc.ZCylinder(r=0.4750)
#  empty rod and Al2O3B4C BPR
z_cylinder8 = openmc.ZCylinder(r=0.5624)
z_cylinder9 = openmc.ZCylinder(r=0.6032)
#  control rod
z_cylinder10 = openmc.ZCylinder(r=0.2210)
z_cylinder11 = openmc.ZCylinder(r=0.4331)
z_cylinder12 = openmc.ZCylinder(r=0.5725)
z_cylinder13 = openmc.ZCylinder(r=0.6226)

z_plane0 = openmc.ZPlane(z0=-120)
z_plane1 = openmc.ZPlane(z0=120)
z_plane2 = openmc.ZPlane(z0=-150)
z_plane3 = openmc.ZPlane(z0=150)
z_plane4 = openmc.ZPlane(z0=-155)
z_plane5 = openmc.ZPlane(z0=155)
z_plane6 = openmc.ZPlane(z0=-239)
z_plane7 = openmc.ZPlane(z0=-253,boundary_type='vacuum')
z_plane8 = openmc.ZPlane(z0=169,boundary_type='vacuum')
H_fuel1_cell = openmc.Cell(fill=fuel1,region=-z_cylinder5&+z_plane0&-z_plane1)
H_He_cell = openmc.Cell(fill=He,region=+z_cylinder5&-z_cylinder6&+z_plane0&-z_plane1)
H_SiC_cell = openmc.Cell(fill=SiC,region=+z_cylinder6&-z_cylinder7&+z_plane0&-z_plane1)
H_water_cell = openmc.Cell(fill=water_h,region=+z_cylinder7&+z_plane0&-z_plane1)
H = openmc.Universe(cells=[H_fuel1_cell,H_He_cell,H_SiC_cell,H_water_cell])

M_fuel1_cell = openmc.Cell(fill=fuel2,region=-z_cylinder5&+z_plane0&-z_plane1)
M_He_cell = openmc.Cell(fill=He,region=+z_cylinder5&-z_cylinder6&+z_plane0&-z_plane1)
M_SiC_cell = openmc.Cell(fill=SiC,region=+z_cylinder6&-z_cylinder7&+z_plane0&-z_plane1)
M_water_cell = openmc.Cell(fill=water_h,region=+z_cylinder7&+z_plane0&-z_plane1)
M = openmc.Universe(cells=[M_fuel1_cell,M_He_cell,M_SiC_cell,M_water_cell])

L_fuel1_cell = openmc.Cell(fill=fuel3,region=-z_cylinder5&+z_plane0&-z_plane1)
L_He_cell = openmc.Cell(fill=He,region=+z_cylinder5&-z_cylinder6&+z_plane0&-z_plane1)
L_SiC_cell = openmc.Cell(fill=SiC,region=+z_cylinder6&-z_cylinder7&+z_plane0&-z_plane1)
L_water_cell = openmc.Cell(fill=water_h,region=+z_cylinder7&+z_plane0&-z_plane1)
L = openmc.Universe(cells=[L_fuel1_cell,L_He_cell,L_SiC_cell,L_water_cell])

pin2_air_cell = openmc.Cell(fill=air,region=-z_cylinder8&+z_plane0&-z_plane1)
pin2_can_cell = openmc.Cell(fill=can,region=+z_cylinder8&-z_cylinder9&+z_plane0&-z_plane1)
pin2_water_cell = openmc.Cell(fill=water_h,region=+z_cylinder9&+z_plane0&-z_plane1)
pin2 = openmc.Universe(cells=[pin2_air_cell,pin2_can_cell,pin2_water_cell])

pin3_UO2Gd_cell = openmc.Cell(fill=UO2Gd,region=-z_cylinder5&+z_plane0&-z_plane1)
pin3_He_cell = openmc.Cell(fill=He,region=+z_cylinder5&-z_cylinder6&+z_plane0&-z_plane1)
pin3_can_cell = openmc.Cell(fill=can,region=+z_cylinder6&-z_cylinder7&+z_plane0&-z_plane1)
pin3_water_cell = openmc.Cell(fill=water_h,region=+z_cylinder7&+z_plane0&-z_plane1)
pin3 = openmc.Universe(cells=[pin3_UO2Gd_cell,pin3_He_cell,pin3_can_cell,pin3_water_cell])

pin4_He_cell = openmc.Cell(fill=He,region=-z_cylinder8&+z_plane0&-z_plane1)
pin4_Al2O3B4C_cell = openmc.Cell(fill=Al2O3B4C,region=+z_cylinder8&-z_cylinder9&+z_plane0&-z_plane1)
pin4_water_cell = openmc.Cell(fill=water_h,region=+z_cylinder9&+z_plane0&-z_plane1)
pin4 = openmc.Universe(cells=[pin4_He_cell,pin4_Al2O3B4C_cell,pin4_water_cell])

pin5_air_cell = openmc.Cell(fill=air,region=-z_cylinder10|(+z_cylinder11&-z_cylinder12)&+z_plane0&-z_plane1)
pin5_AgInCd_cell = openmc.Cell(fill=AgInCd,region=+z_cylinder10&-z_cylinder11&+z_plane0&-z_plane1)
pin5_can_cell = openmc.Cell(fill=can,region=+z_cylinder12&-z_cylinder13&+z_plane0&-z_plane1)
pin5_water_cell = openmc.Cell(fill=water_h,region=+z_cylinder13&+z_plane0&-z_plane1)
pin5 = openmc.Universe(cells=[pin5_air_cell,pin5_AgInCd_cell,pin5_can_cell,pin5_water_cell])

all_water_cell = openmc.Cell(fill=water_h,region=+z_plane0&-z_plane1)
outer_universe = openmc.Universe(cells=(all_water_cell,))

lat1 = openmc.RectLattice()
lat1.lower_left = (-10.71,-10.71)
lat1.pitch = (1.26,1.26)
lat1.universes = [[H]*17,
                  [H]+[pin3]+[H]+[pin3]+[H]*4+[pin4]+[H]*4+[pin3]+[H]+[pin3]+[H],
                  [H]*5+[pin2]+[H]*2+[pin2]+[H]*2+[pin2]+[H]*5,
                  [H]+[pin3]+[H]+[pin2]+[H]*9+[pin2]+[H]+[pin3]+[H],
                  [H]*4+[pin4]+[H]*3+[pin4]+[H]*3+[pin4]+[H]*4,
                  [H]*2+[pin2]+[H]*2+[pin2]+[H]*2+[pin2]+[H]*2+[pin2]+[H]*2+[pin2]+[H]*2,
                  [H]*4+[pin3]+[H]*7+[pin3]+[H]*4,
                  [H]*7+[pin4]+[H]+[pin4]+[H]*7,
                  [H]+[pin4]+[pin2]+[pin4]+[H]+[pin2]+[H]*2+[pin3]+[H]*2+[pin2]+[H]+[pin4]+[pin2]+[pin4]+[H],
                  [H]*7+[pin4]+[H]+[pin4]+[H]*7,
                  [H]*4+[pin3]+[H]*7+[pin3]+[H]*4,
                  [H]*2+[pin2]+[H]*2+[pin2]+[H]*2+[pin2]+[H]*2+[pin2]+[H]*2+[pin2]+[H]*2,
                  [H]*4+[pin4]+[H]*3+[pin4]+[H]*3+[pin4]+[H]*4,
                  [H]+[pin3]+[H]+[pin2]+[H]*9+[pin2]+[H]+[pin3]+[H],
                  [H]*5+[pin2]+[H]*2+[pin2]+[H]*2+[pin2]+[H]*5,
                  [H]+[pin3]+[H]+[pin3]+[H]*4+[pin4]+[H]*4+[pin3]+[H]+[pin3]+[H],
                  [H]*17]

lat2 = openmc.RectLattice()
lat2.lower_left = (-10.71,-10.71)
lat2.pitch = (1.26,1.26)
lat2.universes = [[M]*17,
                  [M]+[pin3]+[M]*13+[pin3]+[M],
                  [M]*5+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*5,
                  [M]+[pin3]+[M]+[pin2]+[M]*9+[pin2]+[M]+[pin3]+[M],
                  [M]*17,
                  [M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2,
                  [M]*17,
                  [M]*17,
                  [M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2,
                  [M]*17,
                  [M]*17,
                  [M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*2,
                  [M]*17,
                  [M]+[pin3]+[M]+[pin2]+[M]*9+[pin2]+[M]+[pin3]+[M],
                  [M]*5+[pin2]+[M]*2+[pin2]+[M]*2+[pin2]+[M]*5,
                  [M]+[pin3]+[M]*13+[pin3]+[M],
                  [M]*17]

lat3 = openmc.RectLattice()
lat3.lower_left = (-10.71,-10.71)
lat3.pitch = (1.26,1.26)
lat3.universes = [[L]*17,
                  [L]*17,
                  [L]*5+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*5,
                  [L]*3+[pin2]+[L]*9+[pin2]+[L]*3,
                  [L]*17,
                  [L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2,
                  [L]*17,
                  [L]*17,
                  [L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2,
                  [L]*17,
                  [L]*17,
                  [L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*2,
                  [L]*17,
                  [L]*3+[pin2]+[L]*9+[pin2]+[L]*3,
                  [L]*5+[pin2]+[L]*2+[pin2]+[L]*2+[pin2]+[L]*5,
                  [L]*17,
                  [L]*17]

lat4 = openmc.RectLattice()
lat4.lower_left = (-10.71,-10.71)
lat4.pitch = (1.26,1.26)
lat4.outer = outer_universe
lat4.universes = [[outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17,
                  [outer_universe]*17]


cell_110 = openmc.Cell(fill=lat1,region=+z_plane0&-z_plane1&+x_plane0&-x_plane1&+y_plane0&-y_plane1)
U110 = openmc.Universe(cells=(cell_110,))
cell_120 = openmc.Cell(fill=lat2,region=+z_plane0&-z_plane1&-z_plane1&+x_plane0&-x_plane1&+y_plane0&-y_plane1)
U120 = openmc.Universe(cells=(cell_120,))
cell_130 = openmc.Cell(fill=lat3,region=+z_plane0&-z_plane1&-z_plane1&+x_plane0&-x_plane1&+y_plane0&-y_plane1)
U130 = openmc.Universe(cells=(cell_130,))
cell_150 = openmc.Cell(fill=lat4,region=+z_plane0&-z_plane1&-z_plane1&+x_plane0&-x_plane1&+y_plane0&-y_plane1)
U150 = openmc.Universe(cells=(cell_150,))


lat5 = openmc.RectLattice()
lat5.lower_left = (-96.3,-96.3)
lat5.pitch = (21.4,21.4)
lat5.outer = outer_universe
lat5.universes = [[U150]*2+[U120]*5+[U150]*2,
                  [U150]+[U130]+[U110]*5+[U130]+[U150],
                  [U120]+[U110]*2+[U120]*3+[U110]*2+[U120],
                  [U120]+[U110]+[U120]+[U110]*3+[U120]+[U110]+[U120],
                  [U120]+[U110]+[U120]+[U110]+[U130]+[U110]+[U120]+[U110]+[U120],
                  [U120]+[U110]+[U120]+[U110]*3+[U120]+[U110]+[U120],
                  [U120]+[U110]*2+[U120]*3+[U110]*2+[U120],
                  [U150]+[U130]+[U110]*5+[U130]+[U150],
                  [U150]*2+[U120]*5+[U150]*2]

root_cell1 = openmc.Cell(cell_id=200,fill=lat5,region=-z_cylinder0&+z_plane0&-z_plane1)
root_cell2 = openmc.Cell(cell_id=201,fill=water_h,region=(~(-z_cylinder0&+z_plane0&-z_plane1))&-z_cylinder1&+z_plane2&-z_plane3)
root_cell3 = openmc.Cell(cell_id=202,fill=can,region=(~(-z_cylinder1&+z_plane2&-z_plane3))&-z_cylinder2&+z_plane4&-z_plane5)
root_cell4 = openmc.Cell(cell_id=203,fill=water_c,region=(~(-z_cylinder2&+z_plane4&-z_plane5))&-z_cylinder3&+z_plane6&-z_plane5)
root_cell5 = openmc.Cell(cell_id=204,fill=vessel,region=(~(-z_cylinder3&+z_plane6&-z_plane5))&-z_cylinder4&+z_plane7&-z_plane8)
root_universe = openmc.Universe(cells=[root_cell1,root_cell2,root_cell3,root_cell4,root_cell5])
geom = openmc.Geometry(root_universe)
geom.export_to_xml()
settings = openmc.Settings()
settings.particles = 100000
settings.batches = 1000
settings.inactive = 200
uniform_dist = openmc.stats.Box(*geom.bounding_box)
settings.source = openmc.Source(space=uniform_dist)
settings.export_to_xml()
`

**Comment by gridley** [comment]
Can you include the whole input, including materials?

**Comment by ternence6** [comment]
> Can you include the whole input, including materials? Also what nuclear data library are you using?

```
#  Materials
fuel1 = openmc.Material(1,"U235 wt% 4.694",temperature=600)
fuel1.add_nuclide('U235',0.02347,'wo')
fuel1.add_nuclide('Al27',0.05,'wo')
fuel1.add_element('Si',0.90653,'wo')
fuel1.add_element('Mo',0.02,'wo')
fuel1.set_density('g/cm3',11.57)

fuel2 = openmc.Material(2,"U235 wt% 2.414",temperature=600)
fuel2.add_nuclide('U235',0.01207,'wo')
fuel2.add_nuclide('Al27',0.05,'wo')
fuel2.add_element('Si',0.91793,'wo')
fuel2.add_element('Mo',0.02,'wo')
fuel2.set_density('g/cm3',11.57)

fuel3 = openmc.Material(3,"U235 wt% 1.95",temperature=600)
fuel3.add_nuclide('U235',0.00975,'wo')
fuel3.add_nuclide('Al27',0.05,'wo')
fuel3.add_element('Si',0.92025,'wo')
fuel3.add_element('Mo',0.02,'wo')
fuel3.set_density('g/cm3',11.57)

AgInCd = openmc.Material(4,"Ag-In-Cd",temperature=600)
AgInCd.add_element('Ag',0.80,'wo')
AgInCd.add_element('In',0.15,'wo')
AgInCd.add_element('Cd',0.05,'wo')
AgInCd.set_density('g/cm3',10.17)

water_c = openmc.Material(5,"cold coolant",temperature=600)
water_c.add_nuclide('H1',0.11,'wo')
water_c.add_nuclide('O16',0.89,'wo')
water_c.set_density('g/cm3',0.73282)

water_h = openmc.Material(6,"hot coolant",temperature=600)
water_h.add_nuclide('H1',0.11,'wo')
water_h.add_nuclide('O16',0.89,'wo')
water_h.set_density('g/cm3',0.70498)

can = openmc.Material(7,"cladding",temperature=600)
can.add_element('Sn',0.0120,'wo')
can.add_element('Zr',0.9826,'wo')
can.add_element('Fe',0.0024,'wo')
can.add_element('Cr',0.0030,'wo')
can.set_density('g/cm3',6.56)

vessel = openmc.Material(8,"core vessel",temperature=600)
vessel.add_nuclide('Mn55',0.01500,'wo')
vessel.add_nuclide('P31',0.00035,'wo')
vessel.add_element('Fe',0.97150,'wo')
vessel.add_element('C',0.00250,'wo')
vessel.add_element('S',0.00035,'wo')
vessel.add_element('Si',0.00030,'wo')
vessel.add_element('Ni',0.00500,'wo')
vessel.add_element('Mo',0.00500,'wo')
vessel.set_density('g/cm3',7.85)

He = openmc.Material(9,"He",temperature=600)
He.add_element('He',1,'wo')
He.set_density('g/cm3',1.786E-4)

air = openmc.Material(10,"air",temperature=600)
air.add_nuclide('N14',9.4326E-1,'wo')
air.add_nuclide('O16',5.6738E-2,'wo')
air.set_density('g/cm3',1.2510E-3)

Al2O3B4C = openmc.Material(11,"Al2O3B4C",temperature=600)
Al2O3B4C.add_nuclide('B11',0.1095654,'wo')
Al2O3B4C.add_nuclide('C12',0.0304346,'wo')
Al2O3B4C.add_nuclide('O16',0.4047059,'wo')
Al2O3B4C.add_nuclide('Al27',0.4552941,'wo')
Al2O3B4C.set_density('g/cm3',2.735)

SiC = openmc.Material(12,"SiC claddding",temperature=600)
SiC.add_element('Si',0.708,'wo')
SiC.add_element('C',0.292,'wo')
SiC.set_density('g/cm3',2.58)

UO2Gd = openmc.Material(13,"UO2Gd",temperature=600)
UO2Gd.add_nuclide('U234',3.13109E-02,'wo')
UO2Gd.add_nuclide('U238',8.14929E-01,'wo')
UO2Gd.add_nuclide('Gd154',7.13344E-04,'wo')
UO2Gd.add_nuclide('Gd152',6.70544E-05,'wo')
UO2Gd.add_nuclide('Gd155',5.06012E-03,'wo')
UO2Gd.add_nuclide('Gd156',7.08860E-03,'wo')
UO2Gd.add_nuclide('Gd157',5.43718E-03,'wo')
UO2Gd.add_nuclide('Gd158',8.64341E-03,'wo')
UO2Gd.add_nuclide('Gd160',7.69426E-03,'wo')
UO2Gd.add_nuclide('O16',1.19056E-01,'wo')
UO2Gd.set_density('g/cm3',10.291)

mats = openmc.Materials([fuel1,fuel2,fuel3,AgInCd,water_c,water_h,can,vessel,He,air,Al2O3B4C,SiC,UO2Gd])
mats.export_to_xml()
```
About the library,I tried the official library:endfb71 and endfb80,but it didn't work.

**Comment by gridley** [comment]
OK, i get the feeling OpenMC may not be calculating the bounding box of this geometry correctly, which is a known weak spot. I think the issue is that you have a fairly near critical system, but the initial source distribution guess is giving an unrealistically low estimate of k, so the neutron multiplication is amplified by 4x on the next power iteration, which overfills the fission bank and causes this.

I think you should try putting the initial source as a point somewhere in the middle of your reactor, or use a manually defined smaller box more fully inside the core.

I can try running your input tomorrow if this doesn't solve it.

**Comment by pshriwise** [comment]
@ternence6 I'll also suggest trying a source definition that rejects source sites in non-fissionable materials like so:

```python
uniform_dist = openmc.stats.Box(*geom.bounding_box, only_fissionable=True)
```

For a bounding box over an entire reactor, uniform sampling of the box is going to result in a lot of source sites far from fissionable materials. This will result in an artificially low k-eff in the first few batches like you're seeing here.

**Comment by ternence6** [comment]
> OK, i get the feeling OpenMC may not be calculating the bounding box of this geometry correctly, which is a known weak spot. I think the issue is that you have a fairly near critical system, but the initial source distribution guess is giving an unrealistically low estimate of k, so the neutron multiplication is amplified by 4x on the next power iteration, which overfills the fission bank and causes this.
> 
> I think you should try putting the initial source as a point somewhere in the middle of your reactor, or use a manually defined smaller box more fully inside the core.
> 
> I can try running your input tomorrow if this doesn't solve it.

ty for help,I'd try to change the initial source.

**Comment by ternence6** [comment]
> @ternence6 I'll also suggest trying a source definition that rejects source sites in non-fissionable materials like so:
> 
> ```python
> uniform_dist = openmc.stats.Box(*geom.bounding_box, only_fissionable=True)
> ```
> 
> For a bounding box over the entire reactor, uniform sampling of the box is going to result in a lot of source sites far from fissionable materials. This will result in an artificially low k-eff in the first few batches like you're seeing here.
Ty.That did work,but maybe the k would be bigger than the real k of the whole part?
