### ISSUE TITLE
Capture cross section in transport and depletion solvers

### ISSUE THREAD

**Issue by Mustafa-kk** [openmc-dev/openmc#1766]
I have noticed a difference in capture cross section generated with openmc.mgx module (referenced as capture) and the capture cross section obtained from tallied capture reaction rates (referenced as (n,gamma)). The capture cross section obtained from reaction rates is higher than the absorption cross section especially in the resonance energy range which doesn’t make sense. I noticed that for Th-232 isotope and other isotopes as well. So I am wondering why this difference exist?

I am generating multigroup cross sections for depletion calculations to verify my code. So I used the same depletion chain and same cross sections in my code and I noticed a growing difference with time. so I found this mismatch in the capture cross sections.
When I used the capture cross section obtained from openmc.mgx module in the transport calculations and used the capture cross section obtained from reaction rates tallies in depletion matrix, my code results match exactly with OpenMC. So my conclusion is that how OpenMC does. But why the capture cross section varies between the transport and depletion solvers?
This issue has a significant impact on the eigenvalue and nuclide concentrations. I would appreciate it if you could help me with this issue. I am using the OpenMC version 0.12.0.

**Comment by paulromano** [comment]
After digging into this with @Mustafa-kk, I was able to determine that this is indeed a bug. Right now, the `(n,gamma)` reaction rate tally is using the unshielded (n,gamma) cross section when a neutron is in the unresolved resonance region. It should be using the cross section that is sampled in `Nuclide::calculate_urr_xs`. I have a branch with a fix ready to go and @Mustafa-kk has graciously agreed to test it out to ensure that it resolves the problem he was observing.

**Comment by paulromano** [comment]
Closed with the merging of #1776
