### ISSUE TITLE
Theory guide missing explanation of n,g reactions

### ISSUE THREAD

**Issue by makeclean** [openmc-dev/openmc#1781]
The neutron theory guide stems from an era when OpenMC lacked photon transport, thus the section https://docs.openmc.org/en/develop/methods/neutron_physics.html#n-gamma-and-other-disappearance-reactions lacks the true description of how photons are sampled from radiative capture reactions

**Comment by paulromano** [comment]
Excellent point, looks like we need some updates there

**Comment by paulromano** [comment]
Closed with the merging of #1785
