### ISSUE TITLE
Pugixml linking error

### ISSUE THREAD

**Issue by jtramm** [openmc-dev/openmc#1789]
The build process appears to be broken if pugixml is already installed elsewhere on the system. I'm getting the following error when I try to compile a second version of OpenMC on the same system:

`[ 97%] Linking CXX shared library lib/libopenmc.so
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lpugixml
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/libopenmc.dir/build.make:1430: lib/libopenmc.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: CMakeFiles/libopenmc.dir/all] Error 2
make: *** [Makefile:149: all] Error 2`

Perhaps this was caused by #1770?

**Comment by AnderGray** [comment]
I'm experiencing the same issue

**Comment by gridley** [comment]
Hm, I'm unable to reproduce this. Is it possible you guys are using a build directory from before that commit? I get the feeling CMake is perhaps leaving some cache variable unchanged that actually should have been changed. Maybe removing the old build directory, then creating a new one will do the trick.

**Comment by gridley** [comment]
Could either of you guys please include the full output from when you ran cmake?
