### ISSUE TITLE
Testing of example notebooks

### ISSUE THREAD

**Issue by Shimwell** [openmc-dev/openmc#1802]
While adding an example notebook in PR #1800 I noticed the notebooks don't appear to be tested on the CI unless I have missed something.

So I was wondering if I should throw together a quick test for the notebooks and see that they at least run without error

Notebooks can be tested like this https://github.com/Shimwell/openmc/blob/testing_example_notebooks/tests/test_example_notebooks.py

I would also suggest we change the local images to urls like this https://github.com/Shimwell/openmc/commit/ba2470c0fa71d8684c0ea25c32f875d3fd8fa800

This makes it easier to test and also makes the notebooks more portable. I noticed there are several urls being used already to download ace data from the anl box and dagmc geometry from tiny urls so the use of urls in the notebooks already appears acceptable?

Let me know if this is a worthwhile aim and if the method looks suitable.

I would be keen to make a PR

**Comment by alex-treebeard** [comment]
hey there, I maintain a [pytest plugin](https://github.com/treebeardtech/nbmake) for this in case it helps, feedback very welcome.

**Comment by Shimwell** [comment]
Hi @alex-treebeard thanks for making the plugin it is most useful. 

I do actually have one slightly related question. If the ipynb wants to make use of an image or a local .py file that is imported is there a way to do that without getting the ```ModuleNotFoundError: No module named 'plotting_utils'``` error.

For example if I have a py file that the notebook imports like this ```import plotting_utils```

As you can see with this issue I've replaced all the local image paths with urls as a work around, but it might be nice to avoid having to do that without hardcoding the absolute path

**Comment by alex-treebeard** [comment]
hey @Shimwell , not sure if that question was aimed at me, But most developers install python dependencies locally before importing them into an example notebook. This makes it more likely that when someone tries to use the example, it works the same way for them.

In your case I would expect you should be doing something like `pip install .` To install your source code before running the notebook.

**Comment by Shimwell** [comment]
Thanks Alex

**Comment by paulromano** [comment]
All the functionality within notebooks should be already tested by other means (unit tests, regression tests), so testing the notebooks won't give us better coverage and will only potentially increase our CI time, which is already rather long. As has been discussed on the slack workspace, storing our example notebooks elsewhere might be a better long-term solution. Of course, the same issue will exist that they can get out of sync if they are not tested, but I'd rather not tie it directly to our main repo.

**Comment by Shimwell** [comment]
Thanks Paul, I can perhaps put some CI on the new example notebooks repo in the future.
