### ISSUE TITLE
Typos in regression test

### ISSUE THREAD

**Issue by ameliajo** [openmc-dev/openmc#1805]
In [tests/regression_tests/tallies/test.py](https://github.com/openmc-dev/openmc/blob/763817d6ab0a80506340e47d897aded03f9921b9/tests/regression_tests/tallies/test.py#L106), there's a number of instances where "estimator" is misspelled to "estimatir"

**Comment by paulromano** [comment]
Yikes! Thanks for the heads up on that. Feel free to fix those on your current PR for the collision filter (if you do, make sure you make the change before updating the test results)

**Comment by ameliajo** [comment]
None of the machines I have access to currently seem to get along with the openmc tests (hence why the collision filter PR tests haven't been fixed yet). Perhaps its mac weirdness, I'm not sure. I'll abstain from changing this myself for now, at least until I can get the test process to agree with me

**Comment by paulromano** [comment]
Fixed in #1798
