### ISSUE TITLE
MPI slowing down

### ISSUE THREAD

**Issue by KseniaBastrakova** [openmc-dev/openmc#1808]
Hello,
Running standard examples of openMC, I came across an interesting effect in a parallel version and not understood why it happens.
In general: I get a slowdown several times when I run the version with MPI.
OpenMC was compiled with `openmpi/2.1.2, gcc/7.3.0, cmake/3.15.2, hdf5-parallel/1.8.20` and run on the two-processors node with 20 (physical) cores each. 
And i used pyhton interface and run standart example (`openmc.examples.pwr_core`) with the number of particles = 10^6 and number of iterations = 10^3 like:

`openmc.run(mpi_args=['mpiexec', '-n', '2'], threads=20)`

and running with more MPI process gives us significant slowing down:
(i tried it with different number threads and processes and got slow down each time)
MPI Processes 1 | OpenMP Threads 20 |  simulation time = 6.8361e+02 seconds
MPI Processes 2 | OpenMP Threads 40 |  simulation time =  1.2219e+03 seconds
hypertrading was enabled on every launch 

Do you have any ideas as, why it happened?

**Comment by paulromano** [comment]
@KseniaBastrakova The number of OpenMP threads listed is really the number of threads _per process_, not total. This means if you have 40 physical cores total, you'd want to run 2 MPI processes each with 20 OpenMP threads. If you run with 40 threads per process, you're oversubscribing the physical resources which is likely leading to contention.

I'm going to close this for now but if you still believe there is an actual issue after further investigation, feel free to reopen the issue. Also -- for general questions like this, I'd encourage you to post a message on our [user's forum](https://openmc.discourse.group/).
