### ISSUE TITLE
1D z-axis RectLattice, can't set x,y pitch to 0 and openmc crashes with void outer, what can I do?

### ISSUE THREAD

**Issue by mcgeochd** [openmc-dev/openmc#1818]
I'm trying to model a grooved ring fuel element for a nuclear thermal rocket consisting of a cylindrical stack of grooved rings. I have a single grooved ring as a universe containing the fuel grooves, coolant between the grooves, and the flat fuel plate the walls sit on. I'm trying to fill a cell with a lattice of these grooved rings that extends in the z-axis only.
```
collat = openmc.RectLattice()
collat.lower_left = (0, 0, -height)
collat.pitch = (1, 1, h+tplate)
collat.universes = [[[groovedRing]]]*rings
fuelColumnRegion = -reactorTop & +reactorBot & -fuelCylOuter & +fuelCylInner
fuelColumn = openmc.Cell(fill=collat, region=fuelColumnRegion)
elementUni = openmc.Universe(cells=[fuelColumn])
```
The result I get back is: `WARNING: Particle 0 is outside lattice 2 but the lattice has no defined outer` repeating until a runtime error is raised and openmc aborts "unexpectedly".

I tried adding `collat.outer = openmc.Universe(cells=[openmc.Cell()])` but that just causes an immediate runtime error and "unexpected" abort as well.

I also tried `collat.pitch = (0, 0, h+tplate)`, but that also generated an error

Edit: To clarify. I am not trying to run any simulation at this point, these errors arise as a result of attempting to plot a slice through the fuel stack.

**Comment by gridley** [comment]
Hi, why did you close this? Figure out the problem?

**Comment by mcgeochd** [comment]
> Hi, why did you close this? Figure out the problem?

Further investigation revealed the problem was deeper than initially suspected, such that it was no longer covered by this issue, so I closed it and opened another. In short, plotting is frequently failing, even for the pre-packaged examples in `openmc.examples`. I’ve tried in Anaconda environments with Python 3.9.4, 3.8.8, and 3.7.10, and every time got a `RunTime Error: OpenMC crashed unexpectedly.` At first I thought it was lattices causing the problem, as explained in this issue, but the pin_cell example also failed to plot, and that doesn’t include any lattices.
