### ISSUE TITLE
RuntimeError: OpenMC aborted unexpectedly. occurs when plotting anything, including openmc.examples in Python 3.9.2

### ISSUE THREAD

**Issue by mcgeochd** [openmc-dev/openmc#1819]
I have openmc installed in a Python 3.9.2 anaconda environment with matplotlib and I'm trying to plot the geometry from openmc.examples:
```
import openmc

model = openmc.examples.pwr_pin_cell()
model.plots.export_to_xml()
openmc.plot_geometry()
```
but the plotting fails for all 3 examples. I have managed to write my own code with limited plotting success, so I can generate plots for some models, but still frequently experience this "unexpected" abort bug which makes me believe it is some aspect of the geometry that is causing this problem. The fact this issue occurs even for the examples packaged with openmc makes me believe this is an issue.

The full plotting trace is:
```
Plot ID: 1
Plot file: plot_1.ppm
Universe depth: -1
Plot Type: Slice
Origin: 0.0 0.0 0.0
Width: 1.26 1.26
Coloring: Materials
Basis: XY
Pixels: 300 300

Processing plot 1: plot_1.ppm...
Traceback (most recent call last):
  File "/home/dominicmcgeoch/Documents/OpenMC/test.py", line 7, in <module>
    openmc.plot_geometry()
  File "/home/dominicmcgeoch/miniconda3/envs/nuclear/lib/python3.9/site-packages/openmc/executor.py", line 59, in plot_geometry
    _run([openmc_exec, '-p'], output, cwd)
  File "/home/dominicmcgeoch/miniconda3/envs/nuclear/lib/python3.9/site-packages/openmc/executor.py", line 38, in _run
    raise RuntimeError(error_msg)
RuntimeError: OpenMC aborted unexpectedly.
```

Update: I created new environments with Python 3.8.8 and 3.7.10, fresh install of openmc and matplotlib each time, and got the exact same error for both. Still not sure what the problem is.

**Comment by gridley** [comment]
Sorry to see this, looks like a pain in the butt. Can you provide the OpenMC version you're running on with `openmc -v`? And also, try pasting the output from running openmc from the command line, with `openmc -p`. You may get a more useful error message.

**Comment by mcgeochd** [comment]
The version installed with Python 3.9 is `OpenMC version 0.12.1 Git SHA1: d49e6ccb837685e399efdef8b29e46cdc693ccec` As for running from the command line, I'm not sure how to do that for just the plots. All of the information in the documentation is for the Python API. I know the conda install comes with the executable, but I'm don't where in the environment folder it is, or even what file type I'm looking for. It seems as though plot_geometry is called with the arg -p though?
```
def plot_geometry(output=True, openmc_exec='openmc', cwd='.'):
    """Run OpenMC in plotting mode

    Parameters
    ----------
    output : bool, optional
        Capture OpenMC output from standard out
    openmc_exec : str, optional
        Path to OpenMC executable
    cwd : str, optional
        Path to working directory to run in

    Raises
    ------
    RuntimeError
        If the `openmc` executable returns a non-zero status

    """
    _run([openmc_exec, '-p'], output, cwd)
```

**Comment by gridley** [comment]
You may have `openmc` on your path with that installation. I usually don't install through conda. The docs cover far more than just the python API. It definitely mentions how the XML input system works, and describes the file formats completely. Most of the time, the python API is just generating some XML files that openmc reads in to run things. You should find some more info if you look a little harder.

**Comment by mcgeochd** [comment]
You are correct. Running from the command line for the pin_cell example I got: 
```
Processing plot 1: plot_1.ppm...
Segmentation fault (core dumped)
```

**Comment by gridley** [comment]
OK, thanks! Can you share the XML files that are in that directory?

**Comment by gridley** [comment]
OK, I can handle the debugging and find the fix faster since I'm already familiar with our C++ code. By the way, you shouldn't install the "mkdir" package. There should be a package called "coreutils" that contains it.

It looks like you may be new to using a terminal. May want to look up some tutorials on linux terminals; it will make all things OpenMC much easier.

**Comment by mcgeochd** [comment]
> OK, thanks! Can you share the XML files that are in that directory?

`OpenMCConfig.cmake`, `OpenMCConfigVersion.cmake`, `OpenMCTargets.cmake`, and `OpenMCTargets-release.cmake`

**Comment by gridley** [comment]
Hm, they should end in .xml. For instance, materials.xml or settings.xml.

**Comment by mcgeochd** [comment]
> Hm, they should end in .xml. For instance, materials.xml or settings.xml.

I think you may have misunderstood, I was not trying to run openmc or plot anything, I understand that requires xml files. I was following the the troubleshooting advice for a segmentation fault, which is to recompile openmc from its cmake files:
https://docs.openmc.org/en/stable/usersguide/troubleshoot.html
> 15.2. Problems with Simulations
15.2.1. Segmentation Fault

A segmentation fault occurs when the program tries to access a variable in memory that was outside the memory allocated for the program. The best way to debug a segmentation fault is to re-compile OpenMC with debug options turned on. Create a new build directory and type the following commands:

mkdir build-debug && cd build-debug
cmake -Ddebug=on /path/to/openmc
make

Now when you re-run your problem, it should report exactly where the program failed. If after reading the debug output, you are still unsure why the program failed, send an email to the OpenMC User’s Group mailing list.<

**Comment by mcgeochd** [comment]
> OK, thanks! Can you share the XML files that are in that directory?

I misread this as cmake at the time, but I can share the xml files
[openmc pin_cell xml files.zip](https://github.com/openmc-dev/openmc/files/6331110/openmc.pin_cell.xml.files.zip)

**Comment by mcgeochd** [comment]
I just managed to get the examples to plot, it turns out I wasn't outputting all of the required xml files before plotting. My code is still not plotting however:
[tricarbide grooved ring fuel element reactor.zip](https://github.com/openmc-dev/openmc/files/6331151/tricarbide.grooved.ring.fuel.element.reactor.zip)
```
Plot ID: 1
Plot file: plot_1.ppm
Universe depth: -1
Plot Type: Slice
Origin: 0.0 0.0 -31.5875
Width: 65.175 65.175
Coloring: Materials
Basis: XY
Pixels: 500 500

 Processing plot 1: plot_1.ppm...
Segmentation fault (core dumped)
```

**Comment by paulromano** [comment]
@mcgeochd I just tried running OpenMC in plotting mode on your files and it works for with the latest version of OpenMC (0.12.2). I would try updating your version. I'm going to go ahead and close this, but if you're still experiencing problems, I'd encourage you to reach out on our [user's discussion forum](https://openmc.discourse.group/).

![plot_1](https://user-images.githubusercontent.com/743095/125499956-3f97c33d-d3d5-4579-af6f-58e0ab5cac09.png)
