### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by E-Hossam96** [openmc-dev/openmc#1832]
Hello there,
I'm trying to install openMC on Windows 10 using Docker and I get this error message in terminal :

Unable to find image 'openmc/openmc:latest' locally
docker: Error response from daemon: manifest for openmc/openmc:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

**Comment by paulromano** [comment]
@E-Hossam96 give it a try again -- looks like we forgot to get the `latest` tag updated but it should be there now
