### ISSUE TITLE
Operator should respect Materials.cross_sections

### ISSUE THREAD

**Issue by drewejohnson** [openmc-dev/openmc#1843]
There have been a couple posts on the [discussion forum](https://openmc.discourse.group/t/cross-section-not-found-in-certain-file/1226) about the `Operator` not respecting / keeping `Materials.cross_sections`. The workflow for reproducing is usually something like
```python
mats = Materials([...])
mats.cross_sections = path_to_xs
mats.export_to_xml()
...
operator = Operator(geometry, settings, chain_file)
...
```

Running the depletion routine can lead to errors about cross sections files not being found. Or the file indicated with `path_to_xs` not being used.

## Short term

The workaround is to set the `OPENMC_CROSS_SECTIONS` environment variable to point to the new cross section file. Either in your python script with
```python
import os
os.environ["OPENMC_CROSS_SECTIONS"] = path_to_xs
```
or in your shell 
```shell
$ OPENMC_CROSS_SECTIONS=/path/to/new/xs python depletion_script.py
```
where `depletion_script.py` contains the script that expects the new cross sections.

## Possible fix

We write the new xml file in https://github.com/openmc-dev/openmc/blob/ef128f56095ac197600684ba9241dedde2b10998/openmc/deplete/operator.py#L597-L613

It might be worth checking if a `materials.xml` file exists already, load with `Materials.from_xml` and then grab the `cross_sections` attribute.

It looks like we only call that once during the initial set up https://github.com/openmc-dev/openmc/blob/ef128f56095ac197600684ba9241dedde2b10998/openmc/deplete/operator.py#L521-L534 rather than at every depletion step. Yay for in-memory material updates!

**Comment by paulromano** [comment]
@drewejohnson I like that idea. The only change I'd suggest is that we not use `Materials.from_xml`, which will load the entire file (that could be large), but rather just use `xml.etree` directly to look for the `<cross_sections>` element.

**Comment by jung-benjamin** [comment]
This problem is still (or perhaps again) occurring now (v0.15.2). From [this](https://github.com/openmc-dev/openmc/issues/2542#issuecomment-1636815453) comment, I gather that the intent is to deprecate the `Materials.cross_sections` variable. Nevertheless, the Documentation currently suggests that `Materials.cross_sections` variable can be used to override the environment variable. Perhaps it can to be updated to better explain the intended usage.
