### ISSUE TITLE
UnstructuredMesh::surface_bins_crossed has wrong call signature

### ISSUE THREAD

**Issue by gridley** [openmc-dev/openmc#1845]
see mesh.{cpp,h}. It appears that `UnstructuredMesh::surface_bins_crossed` has the wrong call signature, and as a result isn't actually overriding what we think it is. If someone tries to call it using the correct call signature of the base class, we'll get a "pure virtual called" error rather than the helpful error message which is currently in place.

**Comment by pshriwise** [comment]
Eesh. Thanks for catching this. I'll submit a fix shortly.
