### ISSUE TITLE
Possible error in Pincell Depletion Example

### ISSUE THREAD

**Issue by BenLindley** [openmc-dev/openmc#1849]
I believe this example https://docs.openmc.org/en/stable/examples/pincell_depletion.html has an error

on line 14, bound_box = openmc.rectangular_prism(0.62, 0.62, boundary_type="reflective") : the dimension should be 1.24. 

This drives the very low k seen for this problem. It is not seen in the geometry because it is visualized before bound_box is added

**Comment by gridley** [comment]
Nice catch! Would you be interested in making a PR to fix it?

**Comment by paulromano** [comment]
I'll take care of this since I'm making some other changes with notebooks.

**Comment by BenLindley** [comment]
Thanks Paul, sorry for not replying earlier Gavin!

**Comment by paulromano** [comment]
This has been [fixed](https://nbviewer.jupyter.org/github/openmc-dev/openmc-notebooks/blob/main/depletion.ipynb).
