### ISSUE TITLE
cross_sections.xml is missing

### ISSUE THREAD

**Issue by Bugami** [openmc-dev/openmc#1855]
Hi...
I am using openmc through anaconda3 and start Modelling a Pin-Cell. when I run the code, error showed me there is no cross_sections.xml. how to have cross_sections.xml in order to run the code?

Thank you in advance...

**Comment by pshriwise** [comment]
Hi @Bugami. Thanks for trying out OpenMC!

I'll refer you to the user's guide section on [cross section configuration](https://docs.openmc.org/en/stable/usersguide/cross_sections.html). We have a number of pre-processed cross section datasets at https://openmc.org/.

If you have further questions along these lines, the [OpenMC discussion forum](https://openmc.discourse.group/) is a good resource for this kind of question or any other issues you may run into.

**Comment by Shimwell** [comment]
@Bugami  you might also be interested in this package https://github.com/openmc-data-storage/openmc_data_downloader which can download the nuclear data required for your materials and set the cross_section.xml See the end of the [readme.md](https://github.com/openmc-data-storage/openmc_data_downloader/blob/main/README.md) for examples.
