### ISSUE TITLE
Possible error in openmc-ace-to-hdf5.py script

### ISSUE THREAD

**Issue by dzianislitskevich** [openmc-dev/openmc#1866]
There is a possible error in lines 126 and 127 of the openmc-ace-to-hdf5.py script (https://github.com/openmc-dev/openmc/blob/develop/scripts/openmc-ace-to-hdf5). OpenMC version 0.12.2; Python 3.9; installed using conda.

When I run this script to convert the ACE library to the HDF5 library, I've got the following error:

TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

The following fix helped me to solve the problem:

Current version:
126      data.export_to_hdf5(converted[name] + '_1', 'w', libver=args.libver)
127      os.rename(converted[name] + '_1', converted[name])

Suggested fix:
126      data.export_to_hdf5(str(converted[name]) + '_1', 'w', libver=args.libver)
127      os.rename(str(converted[name]) + '_1', converted[name])

**Comment by Shimwell** [comment]
That sounds like a Pathlib.Path object is being combined using + with a string object. Would you be keen to put in a pull request
