### ISSUE TITLE
Odd Expects() in set_cells for CellFilter ?

### ISSUE THREAD

**Issue by GiudGiud** [openmc-dev/openmc#1878]
When setting cells for a CellFilter we have this
```
void CellFilter::set_cells(gsl::span<int32_t> cells)
{
  // Clear existing cells
  cells_.clear();
  cells_.reserve(cells.size());
  map_.clear();

  // Update cells and mapping
  for (auto& index : cells) {
    Expects(index >= 0);
    Expects(index < model::cells.size());
    cells_.push_back(index);
    map_[index] = cells_.size() - 1;
  }
```

but index, (from cells argument, coming pretty much straight from xml) is the cell_id right? And they are arbitrary?
So we can reasonably expect index to be above 0 and below the maximum cell id in the geometry, but not that it's smaller than the size of the container of all cells (eg the total number of cells). 

Or am I missing something

**Comment by GiudGiud** [comment]
I see the same thing in UniverseFilter::set_universes. 
I have to be missing something

**Comment by paulromano** [comment]
In the constructor of `CellFilter`, the sequence of cell IDs is converted to indices in the cells array:
https://github.com/openmc-dev/openmc/blob/209fdd86ed14a16d4b73e9c44de8a9710a898e64/src/tallies/filter_cell.cpp#L15-L23

Then the resulting sequence of cell indices is sent to `set_cells`:
https://github.com/openmc-dev/openmc/blob/209fdd86ed14a16d4b73e9c44de8a9710a898e64/src/tallies/filter_cell.cpp#L25

I admit this is a bit confusing at first sight; perhaps we should change a variable name somewhere in there to make it clearer.
