### ISSUE TITLE
error: no matching constructor for initialization of 'libMesh::LibMeshInit'

### ISSUE THREAD

**Issue by yurivict** [openmc-dev/openmc#1893]
OpenMC-0.12.2 fails to build with libmesh-1.6.2

```
In file included from /disk-samsung/freebsd-ports/science/openmc/work/openmc-0.12.2/src/initialize.cpp:1:
In file included from /disk-samsung/freebsd-ports/science/openmc/work/openmc-0.12.2/include/openmc/initialize.h:5:
In file included from /usr/local/mpi/openmpi/include/mpi.h:2887:
In file included from /usr/local/mpi/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h:42:
In file included from /usr/include/c++/v1/map:481:
In file included from /usr/include/c++/v1/__tree:15:
/usr/include/c++/v1/memory:2927:32: error: no matching constructor for initialization of 'libMesh::LibMeshInit'
    return unique_ptr<_Tp>(new _Tp(_VSTD::forward<_Args>(__args)...));
                               ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

OS: FreeBSD 13

**Comment by pshriwise** [comment]
We require libMesh >= 1.6.0 right now. Not sure what's up here, but I'm going to look into it asap.

**Comment by pshriwise** [comment]
Hi @yurivict,

Thank you for reporting this. 

I unfortunately couldn’t reproduce this error in a virtual machine funning FreeBSD 13. OpenMC was able to compile with the libMesh (v1.6.2) package provided with the FreeBSD package manager. Were you using a manually installed version of libMesh? Any additional information on the compiler being used, etc. would be helpful too.

**Comment by makeclean** [comment]
My guess would be a failure from OpenMPI4, looking at this @yurivict you're the maintainer of the OpenMC 'port' https://cgit.freebsd.org/ports/tree/science/openmc - IIRC OpenMPI-4 would be quite a racey version of MPI for LibMesh.

**Comment by yurivict** [comment]
I switched the port to mpich.

@makeclean Thank you for your help!
