### ISSUE TITLE
Extend particle track files to include more than just position

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1923]
Our particle track files currently only contain information on the spatial location (x,y,z) of particles as they are being simulated. For some applications, it would be useful to have additional information stored in particle track files (energy, direction, weight, time).

**Comment by rihanafridi** [comment]
Hello @paulromano,  How to get energy of a particle at each position of spatial location in track file

**Comment by rihanafridi** [comment]
That would really assist! 
Thank you @paulromano
