### ISSUE TITLE
Customized source seems not to compile in Version 0.12.2

### ISSUE THREAD

**Issue by cfichtlscherer** [openmc-dev/openmc#1925]
Hey, I have a feeling the customized source example (source_ring.cpp) doesn't compile in the latest version of OpenMC 0.12.2 anymore.

When I try to run the example in OpenMC 0.12.2, I get the following error message when running the make command:

> error: 'SourceSite' in namespace' openmc' does not name a type; did you mean 'Source'

In version 0.12.0, I don't get this error message. Maybe somebody can check if they get the same error or if it's just a problem on my machine - then I would be sorry.

Unfortunately, I don't have time to take a closer look right now and can also provide no idea how to fix this. If this is a bug and still open after Christmas, I can try to work on a fix.

Thanks a lot already.

Christopher

**Comment by gridley** [comment]
Just move to the develop branch. It works fine there. Will close when you confirm.

**Comment by cfichtlscherer** [comment]
Thanks a lot for your fast reply. I still get the error in the developer branch, but it's working when I check out version 0.12.1. Still, if it works for you, it doesn't seem to be a general bug, so I think you can close this, and I would ask again in the forum?

**Comment by gridley** [comment]
Yep, that would be it. It's using headers installed to the system! The move to the name `SourceSite` is pretty recent.

**Comment by cfichtlscherer** [comment]
Thanks a lot, @paulromano and @gridley, I really appreciate your fast help! This is one reason that makes working with OpenMC such a good experience.
I think running it against an older version was the problem. Now it is working. Not sure if this is the best way to solve this issue, but just if somebody faces a similar issue. For me, the following worked (even though maybe not the best way to go):

1. copying the executable of the openmc development branch into `/usr/local/bin`
2. remove the from the `CMakeLists.txt` file the line 
> target_link_libraries(source OpenMC::libopenmc) 
3. Added the hint in the third line of the `CMakeLists.txt` file
> find_package(OpenMC REQUIRED HINTS /usr/bin/local/openmc)

Thanks a lot again. And I will close this issue.
