### ISSUE TITLE
model.run() can fail to return the statefile

### ISSUE THREAD

**Issue by ojschumann** [openmc-dev/openmc#1939]
I had a problem with running one of the tests, namely `trigger_statepoint_restart`. It crashed on the first assert of the statefile. I tracked it down to a problem with my setup and the logic in model.run(), that determines the last statefile.

The root cause is, that the time of the fileserver where my /home is located is ~30 s off the time of my compute-node (and I can't change that). The logic in model.run() looks for the newest statefile, that is newer than the starttime of `openmc`. Due to the time-difference of my machines and the short runtime this results in a `None` return value.

**Comment by paulromano** [comment]
Wow, that's definitely something I did not anticipate when writing that bit of code. One potential solution is instead of using `time.time()` as the starting time, we could create a temporary file and then look at the timestamp so that it's getting the 30 second behind time from the filesystem. Do you want to give that a shot and see if it works? Here's a patch:
```diff
diff --git a/openmc/model/model.py b/openmc/model/model.py
index d253bfb5b0..3c0dfcb871 100644
--- a/openmc/model/model.py
+++ b/openmc/model/model.py
@@ -4,6 +4,7 @@ from pathlib import Path
 from numbers import Integral
 import time
 from contextlib import contextmanager
+from tempfile import NamedTemporaryFile
 
 import h5py
 
@@ -508,7 +509,8 @@ class Model:
 
         # Setting tstart here ensures we don't pick up any pre-existing
         # statepoint files in the output directory
-        tstart = time.time()
+        with NamedTemporaryFile() as fp:
+            tstart = Path(fp.name).stat().st_mtime
         last_statepoint = None
 
         # Operate in the provided working directory
```

**Comment by ojschumann** [comment]
Yes, it took me quite some time to figure out, what was happening ;-) 

Unfortunately I destroyed my testing opportunity by asking our admins to update the timesource for the filer. But I did a test for the non-lib case and took `tstart` from the settings.xml. That worked. So I guess, your patch will work as well.
