### ISSUE TITLE
Incorrect calculation of material collision stopping powers

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1943]
When we calculate electron/positron collision stopping powers (used for bremsstrahlung) for a material, we rely on Bragg's additivity rule to handle multiple elements, which is an approximation:
https://github.com/openmc-dev/openmc/blob/d12e390f1a365c8e5b92e586cb8dc7a4599e80d2/src/material.cpp#L507-L509

To be fully correct, the collision stopping power would have to account for molecular properties like the mean excitation energy and the density effect correction (see discussion in this [technical report](https://doi.org/10.2172/1490825)).

**Comment by amandalund** [comment]
@paulromano I believe the issue described in the technical report was corrected by #1186 -- or is there still something we're missing?

**Comment by paulromano** [comment]
Yes, I believe you're right @amandalund. Thanks for pointing that out!
