### ISSUE TITLE
Test fail, when compiling with -D_GLIBCXX_DEBUG

### ISSUE THREAD

**Issue by ojschumann** [openmc-dev/openmc#1944]
Hi, after the discussion on #1934 I compiled OpenMC with -D_GLIBCXX_DEBUG. After patching the xtensor library, this is working. 

The CMakeLists.txt has to be updated to allow some of the tests to compile correctly. The test have be compiled with the same Debug-settings. Se the required patch below.

I found 5 tests, that do not run due to exceptions thrown by the flag. Most of the causes are due to access of an array element, that is out of range (read: Memory Error). Fun Fact: With -D_GLIBCXX_DEBUG the test took ages! That's for sure not for the CI

The failing tests are:

> regression_tests/filter_mesh/test.py F                                   [  7%]
regression_tests/filter_translations/test.py F                           [  7%]
regression_tests/mg_tallies/test.py F                                    [ 10%]
regression_tests/resonance_scattering/test.py F                          [ 14%]
regression_tests/triso/test.py F                                         [ 20%]

I tracked to bugs to:

`search.h`  -> V.begin() - 1 is invalid!
`nuclide.cpp` & `physics.cpp` -> off by one error for Nuclide::xs_cdf_
`tally_scoring.cpp`  -> Access of data::mg.nuclides_[-1]
`secondary_thermal.cpp` -> Access past energies[] and factors[]

In addition I made some optimization for `tally_scoring.cpp`

I have the patches in my repro [glibcxx_debug branch](https://github.com/ojschumann/openmc/tree/glibcxx_debug)
For `secondary_thermal.cpp` this alters the results and I'm not sure, if this is really correct. Here somebody with more experience should really have a look.

How should we proceed? One big PR od one PR for every bug? And do you like my "optimizations" for the tally routine or should I skip  them?

```diff
@@ -136,10 +136,12 @@ endif()
 
 set(CMAKE_POSITION_INDEPENDENT_CODE ON)
 
+set(LIBCXX_DEBUG FALSE)
 list(APPEND cxxflags -O2)
 if(debug)
   list(REMOVE_ITEM cxxflags -O2)
   list(APPEND cxxflags -g -O0)
+  set(LIBCXX_DEBUG TRUE)
 endif()
 if(profile)
   list(APPEND cxxflags -g -fno-omit-frame-pointer)
@@ -395,6 +397,9 @@ target_include_directories(libopenmc
 
 # Set compile flags
 target_compile_options(libopenmc PRIVATE ${cxxflags})
+if (LIBCXX_DEBUG)
+  target_compile_options(libopenmc PUBLIC -D_GLIBCXX_DEBUG)
+endif()
 
 # Add include directory for configured version file
 target_include_directories(libopenmc PRIVATE ${CMAKE_BINARY_DIR}/include)
@@ -443,6 +448,9 @@ endif()
 #===============================================================================
 add_executable(openmc src/main.cpp)
 target_compile_options(openmc PRIVATE ${cxxflags})
+if (LIBCXX_DEBUG)
+  target_compile_options(openmc PUBLIC -D_GLIBCXX_DEBUG)
+endif()
 target_include_directories(openmc PRIVATE ${CMAKE_BINARY_DIR}/include)
 target_link_libraries(openmc libopenmc)
```

**Comment by gridley** [comment]
I love how you removed the branches in the tallying code. I think there's probably even more room for branch removal in there, too. Have you quantified any performance gains with these changes? I would expect it to be helping, since data-dependent branches are terrible.

**Comment by ojschumann** [comment]
@gridley Thanks that you like my code. An no: I did not yet do any performance testing. Maybe I can gat into that towmorrow.
I already wrote in the commit, that there are more branches that might be removed, but I have to check if e.g. p.macro_xs().total is (including side effects) the same  as nuc_xs.get_xs(MgxsType::TOTAL, p_g). To you, that might be obvious. 
Especially that commit needs some more polishing.

**Comment by pshriwise** [comment]
Hi @ojschumann. Thanks for tracking down these bugs! The tally optimizations look good to me as well 💯 

As far as PRs go, I think one for all of the bugs and one for the tally optimization would be good.

**Comment by ojschumann** [comment]
OK, more stuff: Test with -DXTENSOR_ENABLE_ASSERT
that breaks regression_tests/photon_production in photon.cpp:229:
- profile_pdf_(i, j) is read from Al27.h5/Al/compton_profiles/J and is of size 5
- loop is over n_shell, taht is read from Al27.h5//Al/subshells:designators and has size 7
- Is that a data error?
- three more tests fail due to that, 57/100 files have incorrect data

Another bug is in distribution_energy.cpp:189
- e_out is accessed with n_discrete. distribution_[i].e_out[n_discrete];
- I did not read completely, but it might be, that the number of continuous points is 0, therefore access past the array. 
- The computation can be moved to the place, where it is actually needed. That allows to run the test. An expert is needed to judge, if that actually fixes this bug.

More to come: I now will try -fsanitize
