### ISSUE TITLE
GHA PR dependencies

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#1976]
I came across [this github action](https://github.com/marketplace/actions/pr-dependency-check) this morning. It allows one to add PR dependencies on other PRs or issues to ensure PRs are merged in a specific order. 

There's been a few times that I've wanted to add an extension or script related to a feature PR, but don't want to increase # of lines changed and distract from the core purpose of an open PR. This would allow us to break up something like that into smaller PRs that are easier to review. The contributor also won't have to come back to open the next PR in line each time a PR is reviewed and merged. It would also be handy when a PR is waiting on a bug fix to be merged.

I set this up in my fork to try it out. https://github.com/pshriwise/openmc/pulls

Thoughts?

**Comment by paulromano** [comment]
One of the problems I've seen is that if you have two branches, call them A and B, stacked on top of each other:
```mermaid
flowchart LR
  develop --> A;
  A --> B;
```
and you open PRs for both A and B, after A gets merged:
```mermaid
flowchart LR
  id1[old develop] --> A;
  A --> B;
  A --> develop;
  id1 --> develop;
```
the file diff for the PR for branch B doesn't seem to get updated and will still show changes from branch A, which is obviously confusing to a reviewer.

**Comment by pshriwise** [comment]
Yeah, you're right @paulromano. That's a shame. I'd love to be able to break up PRs into smaller chunks easily. Closing for now, but I'll reopen it if I come across a more robust solution for doing this.
