### ISSUE TITLE
Bug: Attribute error when using `--xsdata` flag in `openmc-ace-to-hdf5.py` 

### ISSUE THREAD

**Issue by yardasol** [openmc-dev/openmc#1993]
I am trying to convert a JEFF 3.1.2 ACE library to HDF5 format so I can do some geometry plotting using the `color_by=material`

I attempted to run the following command:
```
python openmc-ace-to-hdf5 --xsdata sss_jeff312.xsdata --metastable nndc
```
I get the following error:
```
Traceback (most recent call last):
  File "/home/ooblack/projects/cross-section-libraries/jeff312/../../openmc/scripts/openmc-ace-to-hdf5", line 64, in <module>
    ace_libraries.extend(openmc.data.ace.get_libraries_from_xsdata(args.xsdata))
  File "/home/ooblack/projects/openmc/openmc/data/ace.py", line 583, in get_libraries_from_xsdata
    lib = (xsdata.parent / words[8]).resolve()
AttributeError: '_io.TextIOWrapper' object has no attribute 'parent'
```
Poking around `ace.py` a bit, it looks like there may be some variable overwriting going on in `get_libararies_from_xsdata`. Starting at line 575, we have
```
 xsdata = Path(path)
  with open(xsdata, 'r') as xsdata:
      # As in get_libraries_from_xsdir, we use a dict for O(1) membership
      # check while retaining insertion order
      libraries = OrderedDict()
      for line in xsdata:
          words = line.split()
          if len(words) >= 9:
              lib = (xsdata.parent / words[8]).resolve()
.
.
.
```
I believe that on line 583, `xsdata` is suppposed to be a `Path` object, but it has been overwritten by as a `_io.TextIOWrapper` object. Can anyone confirm?

OpenMC version 0.13.0, built from source on Ubuntu 21.04

**Comment by paulromano** [comment]
@yardasol yes, looks like you're right. Thanks for catching this! Do you want to submit a PR to fix this?
