### ISSUE TITLE
Confidence level or significance level  in openmc

### ISSUE THREAD

**Issue by leaihh** [openmc-dev/openmc#2033]
Hello, professor. I want to know what is the Confidence level or significance level of calculation result judgment in openmc?

**Comment by gridley** [comment]
1) We'd prefer if we could reserve the github issues section for actual issues with the code. If you'd like help, please use the OpenMC discourse. https://openmc.discourse.group/
2) Please see here. Uncertainty can either be reported as a standard deviation of a result, or as a half-width of a 95% confidence interval assuming results are normally distributed. https://docs.openmc.org/en/latest/io_formats/settings.html?highlight=confidence
