### ISSUE TITLE
Inconsistency in source installation instructions and `CMakeLists.txt` command line options 

### ISSUE THREAD

**Issue by yardasol** [openmc-dev/openmc#2035]
The [build configuration](https://docs.openmc.org/en/stable/usersguide/install.html#build-configuration) section for the instructions to install OpenMC from source specify the existence of a `debug`  and `optimize` option. However, [the current `CMakeLists.txt` file does not include these options](https://github.com/openmc-dev/openmc/blob/69593033171e4d06af6c73004425318bf4e871c3/CMakeLists.txt#L25), so trying to use `-Ddebug=on`, for example, won't have an effect on the build.

Do these build options need to be added in, or do the install instructions need to be updated to remove them?

**Comment by paulromano** [comment]
@yardasol You're looking at the "stable" documentation. If you are building an in-development version, you should be looking at the ["latest"](https://docs.openmc.org/en/latest/usersguide/install.html#cmakelists-txt-options) documentation.

The -Ddebug=on option has now been replaced by use of `CMAKE_BUILD_TYPE`.  If you want debug flags, use either `-DCMAKE_BUILD_TYPE=Debug` or `-DCMAKE_BUILD_TYPE=RelWithDebInfo`.
