### ISSUE TITLE
Upgrade or control C++ standard

### ISSUE THREAD

**Issue by aprilnovak** [openmc-dev/openmc#2039]
libMesh now requires C++17 to build, which is used in OpenMC for unstructured mesh tallies. However, OpenMC's CMake files (and those of several of its dependencies) use the C++14 standard. In order for Cardinal to build (a coupling of OpenMC and MOOSE), we need to either:

- Upgrade OpenMC to use C++17 in its `CMakeLists.txt`, in these two sections:
```
 if (NOT pugixml_FOUND)
   add_subdirectory(vendor/pugixml)
-  set_target_properties(pugixml PROPERTIES CXX_STANDARD 14 CXX_EXTENSIONS OFF)
+  set_target_properties(pugixml PROPERTIES CXX_STANDARD 17 CXX_EXTENSIONS OFF)
 endif()

 set_target_properties(
     openmc libopenmc faddeeva
-    PROPERTIES CXX_STANDARD 14 CXX_EXTENSIONS OFF)
+    PROPERTIES CXX_STANDARD 17 CXX_EXTENSIONS OFF)
```

- Allow an external knob to control the C++ version, like with an environment variable:
```
 if (NOT pugixml_FOUND)
   add_subdirectory(vendor/pugixml)
-  set_target_properties(pugixml PROPERTIES CXX_STANDARD 14 CXX_EXTENSIONS OFF)
+  set_target_properties(pugixml PROPERTIES CXX_STANDARD $ENV{OPENMC_CXX_VERSION} CXX_EXTENSIONS OFF)
 endif()

 set_target_properties(
     openmc libopenmc faddeeva
-    PROPERTIES CXX_STANDARD 14 CXX_EXTENSIONS OFF)
+    PROPERTIES CXX_STANDARD $ENV{OPENMC_CXX_VERSION} CXX_EXTENSIONS OFF)
```

C++17 is backwards compatible with C++14, so I don't think option #1 causes any issues from a build perspective, but would have repercussions in terms of user compiler versions. 

tag @GiudGiud @loganharbour to continue this discussion from the MOOSE Slack.

**Comment by paulromano** [comment]
Actually, it looks like there's a cleaner way to do this using a [meta-feature](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards) (see also [here](https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#high-level-meta-features-indicating-c-standard-support)):
```CMake
target_compile_features(openmc PUBLIC cxx_std_14)
```
If a dependency further down the chain requires a higher standard, this is supposed to work just fine. It looks like this has been available since CMake 3.8, which is fine since our minimum CMake version at this point is 3.10.

**Comment by loganharbour** [comment]
This is the obvious solution ^ except in cardinal we just wrap the cmake builds with Make (call cmake directly from make) so I'm not sure the best place to add such a configuration, and there's no CLI option for adding compile features

**Comment by paulromano** [comment]
I see. If we're using the `cxx_std_14` compile feature, I think you could still set the global default standard higher with [`-DCMAKE_CXX_STANDARD=17`](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html)?

**Comment by loganharbour** [comment]
> I see. If we're using the `cxx_std_14` compile feature, I think you could still set the global default standard higher with [`-DCMAKE_CXX_STANDARD=17`](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html)?

Tried that one to no avail. That is:

```diff
diff --git a/config/openmc.mk b/config/openmc.mk
index 38ffc363..d8478e04 100644
--- a/config/openmc.mk
+++ b/config/openmc.mk
@@ -12,6 +12,7 @@ $(OPENMC_BUILDDIR)/Makefile: $(OPENMC_DIR)/CMakeLists.txt
        -DCMAKE_PREFIX_PATH=$(LIBMESH_DIR) \
        -DCMAKE_INSTALL_PREFIX=$(OPENMC_INSTALL_DIR) \
        -DCMAKE_INSTALL_LIBDIR=$(OPENMC_LIBDIR) \
+       -DCMAKE_CXX_STANDARD=17 \
        $(OPENMC_DIR)
```

in https://github.com/neams-th-coe/cardinal/blob/devel/config/openmc.mk

**Comment by paulromano** [comment]
To be clear, I don't expect that would work with our current CMakeLists.txt file because we hardcode the CXX_STANDARD property for the openmc and libopenmc targets, but if we were using the `cxx_std_14` feature I think changing `CMAKE_CXX_STANDARD` _would_ work in that case.
