### ISSUE TITLE
sample the theta angle for a spherical source

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2041]
During the workshop @pshriwise noticed that we don't have a good method of sampling a spherical source. I'm just making a note of it here so we don't forget

A uniform distribution is going to cause clustering of samples at the poles of the sphere, but there is not a nice was to specify the correct distribution (0.5 * sin(theta)) with any of the univariate types in ```openmc.stats```

One solution mentioned by @paulromano was to change the code to sample cos(theta) rather than theta

**Comment by paulromano** [comment]
Closed by #2061
