### ISSUE TITLE
CI status checks for documentation changes

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#2051]
The CI checks required to merge PRs will never be satisfied for changesets containing only changes in the set of paths ignored by our `ci.yml` file (docs, examples, etc.). We'll want to look into a way to either disable or replace those checks if possible.

**Comment by paulromano** [comment]
The merge of #2107 reverted the original changes from #2010, so now PRs with documentation changes only will trigger CI builds. Hopefully GitHub comes up with a better way to handle this situation in the future.
