### ISSUE TITLE
Missing version.h when building OpenMC as a dependency using FetchContent

### ISSUE THREAD

**Issue by HunterBelanger** [openmc-dev/openmc#2062]
Currently, if you try to use OpenMC in another cmake project using the FetchContent feature, the build will fail, because the `version.h` header file is missing from the source directory, as it is only configured in the build directory. This configured file should be place in the source directory, and also added to the gitignore file, so that it never gets added to commits.

**Comment by paulromano** [comment]
Thanks for submitting this issue (and proposed fix in #2063)! I'm trying to understand the problem a little better. I put together a minimal CMakeLists.txt file using FetchContent to get OpenMC, and the build worked ok for me. Where does it run into problems for you?

**Comment by gridley** [comment]
> Thanks for submitting this issue (and proposed fix in #2063)! I'm trying to understand the problem a little better. I put together a minimal CMakeLists.txt file using FetchContent to get OpenMC, and the build worked ok for me. Where does it run into problems for you?

Maybe this only happens if you've not built/installed OpenMC before but only pulled it as a submodule, since version.h gets created during the build IIRC?
