### ISSUE TITLE
RuntimeError: basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by Allentro** [openmc-dev/openmc#2067]
I have OpenMC installed on Ubuntu 20.04 in a Conda virtual environment. This was installed through Mamba due to the recent Conda installation issues. 

I've reinstalled the virtual environment and still get the same error message. I've tried running numerous scripts with increasing simplicity. I've also tried scripts I've taken from a fusion energy tutorial which I know have previously worked when running (https://github.com/fusion-energy/magnetic_fusion_openmc_dagmc_paramak_example/blob/main/2_run_openmc_dagmc_simulation.py) and still get the same error.

Here is the full error message: 
```
 Reading settings XML file...
 Reading cross sections XML file...
 Reading materials XML file...
 Reading geometry XML file...
Set overlap thickness = 0
Set numerical precision = 0.001
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Traceback (most recent call last):
  File "/home/alletro/openmc/magnetic_fusion_openmc_dagmc_paramak_example/2_run_openmc_dagmc_simulation.py", line 196, in <module>
    my_model.run()
  File "/home/alletro/miniconda3/envs/openmc/lib/python3.10/site-packages/openmc/model/model.py", line 580, in run
    openmc.run(particles, threads, geometry_debug, restart_file,
  File "/home/alletro/miniconda3/envs/openmc/lib/python3.10/site-packages/openmc/executor.py", line 276, in run
    _run(args, output, cwd)
  File "/home/alletro/miniconda3/envs/openmc/lib/python3.10/site-packages/openmc/executor.py", line 116, in _run
    raise RuntimeError(error_msg)
RuntimeError: basic_string::_M_construct null not valid

```

Is this an issue others have come across?

**Comment by shimwell** [comment]
I've not quite seen this error before. Just to help me understand the problem, have you previously got these fusion examples working, then reinstalled OpenMC with mamba and they no longer work?

Thanks for raising this issue and letting us know

**Comment by Allentro** [comment]
Thank you for your fast reponse. 

I've solved the problem. It turns out that I had unintentionally changed the name of my dagmc.h5m file and not corrected this in my code. 

I've not had a chance to look into this any further yet but I think it might be a good idea to update the error messaging to give a clear output if such a file isn't found. What're your thoughts on this?

**Comment by pshriwise** [comment]
Glad you got this sorted out! We should definitely update that failure with an error message. I'll put in a PR for it later today.

**Comment by pshriwise** [comment]
Reopening this so I can reference it and close it properly via the incoming PR.
