### ISSUE TITLE
documentation missing factor in TSL eq 81

### ISSUE THREAD

**Issue by andrewmholcomb** [openmc-dev/openmc#2082]
Eq. 81 in section 5.11.2 is missing a factor of 2. Code is correct, only a documentation bug. 

https://github.com/openmc-dev/openmc/blob/2efe223404680099f9a77214e743ab78e37cd08c/src/secondary_thermal.cpp#L50

in docs/source/methods/neutron_physics.rst
this: "\mu = 1 - \frac{E_i}{E}"
should be "\mu = 1 - \frac{2E_i}{E}"

**Comment by paulromano** [comment]
Thanks for pointing that out @andrewmholcomb! I just added a fix as part of pull request #2081.
