### ISSUE TITLE
Adding remove_element, feedback from workshop 

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2087]
Hi all

@pshriwise just got asked at the OpenMC IAEA on-core workshop if we have a material.remove_element() to go with the material.remove_nuclide() method 

https://github.com/openmc-dev/openmc/blob/64becd2c700a8b1fa9391bd39fe296f03a60cbcf/openmc/material.py#L394

I would be happy to add this feature to code if others in the community think it would be useful?

**Comment by paulromano** [comment]
Seems like a simple addition -- I would welcome that

**Comment by shimwell** [comment]
solved in #2089
