### ISSUE TITLE
Add constructor to create a mesh from a libMesh pointer, as opposed to from a mesh input file

### ISSUE THREAD

**Issue by lewisgross1296** [openmc-dev/openmc#2102]
Currently in `/openmc/src/mesh.cpp`, it is possible to create a `LibMesh::LibMesh` object with this constructor `LibMesh::LibMesh(const std::string& filename, double length_multiplier)`. For running adaptively refined meshes in a Cardinal simulation, it would be desirable to change a mesh on the fly without having to make a new mesh file each time the mesh change. Instead, Cardinal could use a pointer pointing to the mesh data from MOOSE. This would also benefit a moving mesh simulation, where mesh points are deformed on the fly due to thermal expansion. To accomplish this, a new constructor in `mesh.cpp` would be needed that accepts a `libMesh::Mesh` pointer and scaling factor for length conversion. The proposed change would modify both `Mesh.hpp` and `Mesh.cpp` .

**Comment by pshriwise** [comment]
Good call @lewisgross1296! Definitely on board for this.
