### ISSUE TITLE
feature request: automatic graveyard for graveyard free DAGMC models

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2104]
When making an openmc model using a graveyard free DAGMC geometry it is necessary to add a CSG surface with a vacuum boundary around the geometry

Currently the method I use is

```python
# makes use of the dagmc geometry
dag_univ = openmc.DAGMCUniverse("dagmc.h5m")

# creates an edge of universe boundary
vac_surf = openmc.Sphere(r=10000, surface_id=9999, boundary_type="vacuum")

# specifies the region as below the universe boundary
region = -vac_surf

# creates a cell from the region and fills the cell with the dagmc geometry
containing_cell = openmc.Cell(cell_id=9999, region=region, fill=dag_univ)

model = openmc.Model()
model.geometry = openmc.Geometry(root=[containing_cell])
```

It would be desirable from a user view point to have the graveyard surface / vacuum surface automatically made using the DAGMC bounding box information.

The bounding box knows the extent of the DAGMC geometry and therefore in the event that there is no graveyard in the DAGMC surfaces and there is no vacuum surface in the CSG surfaces it could be automatically added using this bounding box information.

Then the user input would could be simplified to ...

```python
# makes use of the dagmc geometry
dag_univ = openmc.DAGMCUniverse("dagmc.h5m", auto_bounds=True)

model = openmc.Model()
model.geometry = openmc.Geometry(root=[containing_cell])
```

What do people think, would this user simplification be helpful to others?

**Comment by pshriwise** [comment]
I can see a feature like this being very useful! And it shouldn't be difficult to implement. To maintain flexibility in the geometry interface I think we'll want to be careful in how we indicate that the containing cell's region should be automatically defined.

@shimwell what would you think of adding an attribute to the DAGMC universe that indicates it should be automatically bounded if inside a CSG cell? The process would look very much the same as what you have above, with one additional line:

```python
dag_univ = openmc.DAGMCUniverse("dagmc.h5m")
dag_univ.auto_bounds = True
```

**Comment by shimwell** [comment]
That is a nice balance, I would love to see that ```auto_bound``` option

Would a one liner also be possible?
dag_univ = openmc.DAGMCUniverse("dagmc.h5m", auto_bound=True)

Any chance of ```auto_bound``` defaulting to True :smile:

**Comment by shimwell** [comment]
Just so I don't forget and lose the code, after chatting with @pshriwise on slack I've fleshed out the Python side of such an aouto bounding feature and put it on this branch https://github.com/shimwell/openmc/tree/adding_auto_bounds_to_dagmc_models

The extra code can be seen on [this](https://github.com/openmc-dev/openmc/compare/develop...shimwell:openmc:adding_auto_bounds_to_dagmc_models) commit.

**Comment by pshriwise** [comment]
@shimwell had a rather clever idea to use our existing h5py dependency to query the vertices of the DAGMC model and extract the bounding box. The hdf5 structure of MOAB files is quite stable at this point, so I'm comfortable relying on the path to the nodes of the file. Querying the bounding box of the DAGMC model with h5py is just a few lines that can be turned into a property of the `DAGMCUniverse` object.

```
import h5py
f = h5py.File('dagmc.h5m')
coords = f['tstt']['nodes']['coordinates'][()]
llc = coords.min(axis=0)
urd = coords.max(axis=0)
bbox = (llc, urc)
```

From here we can add a convenience function to generate a bounding region of the DAGMC universe with CSG planes.

I'll note here that this could also be useful for gathering other basic information on the Python side (# surfaces, # volumes, and their IDs for example).

**Comment by shimwell** [comment]
I'm not quite sure about the next stage of this idea but perhaps adding something along these lines this to ```DAGMCUniverse```

I don't know how to get the cell id correctly or fill the cell

```python
    @property
    def add_bounding_cell(self):
        bounding_box = self.bounding_box
        bounding_box_center = (bounding_box[0] + bounding_box[1])/2
        radius = math.dist(bounding_box[0], bounding_box[1])
        bounding_surface = openmc.Sphere(x0=bounding_box_center[0], y0=bounding_box_center[1], z0=bounding_box_center[2], r=radius)
        region = -vac_surf
        bounding_cell = openmc.Cell(cell_id=9999, region=-bounding_surface, fill=dag_univ)   # not sure how to set cell id correctly also not sure how to fill with the dag geometry
        self.add_cell(bounding_cell)  # however DAGMCUniverse has no add_cell method
```

**Comment by shimwell** [comment]
I've been thinking about this a bit more and perhaps the bounding_cell would need adding to the ```cell``` property which is inherited from the UniverseBase

Perhaps something more along these lines

```python
    @property
    def add_bounding_cell(self):
        import math
        bounding_box = self.bounding_box
        bounding_box_center = (bounding_box[0] + bounding_box[1])/2
        radius = math.dist(bounding_box[0], bounding_box[1])
        bounding_surface = openmc.Sphere(x0=bounding_box_center[0], y0=bounding_box_center[1], z0=bounding_box_center[2], r=radius)
        bounding_cell = openmc.Cell(region=-bounding_surface, fill=self)   # not sure sure how to fill with the dag geometry, use self?

        cell_id = bounding_cell.id

        if cell_id not in self._cells:
            self._cells[cell_id] = bounding_cell
```

**Comment by pshriwise** [comment]
I'm thinking a couple of functions are in order for this:
  - A method that returns a bounding region for the DAGMC universe (might be useful for other purposes)
    ```python
    def bounding_region(self, bounded_type='box', boundary='vacuum'):
       ...
    ```
  - A method that returns a new universe containing a single bounding cell that's filled with the DAGMC universe
    ```python
    def bounded_universe(self, **kwargs):
       bounding_cell = openmc.Cell(fill=self, region=self.bounding_region(**kwargs))
       return openmc.Universe(cells=[bounding_cell])
    ```

I'd also think it would be good to include support for both a rectangular prism bounding region as well as a sphere bounding region (added a proposed keyword arg for that in the signatures above).

**Comment by shimwell** [comment]
Thanks Patrick, I shall try to get my head around this

I guess the ```DAGMCUniverse.create_xml_subelement``` would also need to write out the ```bounding_cell```

**Comment by shimwell** [comment]
Added another small #2118 PR that could close out this issue.

The python usage ended up not quite as initially proposed (passing auto_bound=True into the constructor) 
The proposed solution adds a method that operates on the class and returns a new universe object.
```
Geometry= openmc.DAGMCUniverse("dagmc.h5m").bounded_universe()
```

**Comment by pshriwise** [comment]
Added in #2118
