### ISSUE TITLE
write_data_to_vtk producing scambled vtk files

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2109]
Hi all

While using the nice new ```write_data_to_vtk``` with regular mesh tallies. I've been getting a vtk file which appears to be a bit messed up and I just wanted to check if I am doing things correctly.

I've defined a mesh like this
```
mesh = openmc.RegularMesh()

mesh.dimension = [100, 50, 100]  # number of mesh cells in each dimension (resolution)

mesh.lower_left = [-750, 0, -750]  # x,y,z coordinates
mesh.upper_right = [750, 750, 750]  # x,y,z coordinates
```

I've extracted a mesh tally like this and written it to vtk
```
statepoint = openmc.StatePoint('statepoint.2.h5')

my_tbr_tally = statepoint.get_tally(name='tbr_on_mesh')

mesh.write_data_to_vtk(
    filename="tbr_tally_on_mesh5.vtk",
    datasets={"mean": my_tbr_tally.mean}
)
```

However I get a vtk geometry like this

![Screenshot from 2022-07-11 12-17-42](https://user-images.githubusercontent.com/8583900/178254663-12457817-bb66-478b-869d-9330861a80b6.png)

**Comment by RemDelaporteMathurin** [comment]
This is a bug. Sorry about that, I'm have a fix but I'm working on a test to catch the bug
