### ISSUE TITLE
Feature request: materials specific activity

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2141]
```Material.activity``` and ```Material.get_nuclide_activity()``` are both super useful for looking at the activity of a material after irradiation.

Quite often it is convenient to have the activity as specific_activity in units of Bq per unit mass instead of just Bq.

As the openmc.Material class already has a ```.volume``` and a ```.density``` attribute this would be easy to add 

I would be keen to add a ```Material.specific_activity``` to the material class if it is welcome ?

**Comment by paulromano** [comment]
Closed by #2142
