### ISSUE TITLE
Unable to download test suite specific set of cross section data

### ISSUE THREAD

**Issue by spfeiffer1** [openmc-dev/openmc#2170]
I tried "wget -O - https://anl.box.com/shared/static/teaup95cqv8s9nn56hfn7ku8mmelr95p.xz" and got 
--2022-08-12 11:29:31--  https://anl.box.com/shared/static/teaup95cqv8s9nn56hfn7ku8mmelr95p.xz
Resolving anl.box.com (anl.box.com)... 107.152.26.197
Connecting to anl.box.com (anl.box.com)|107.152.26.197|:443... connected.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
HTTP request sent, awaiting response... 503 Service Unavailable
2022-08-12 11:29:31 ERROR 503: Service Unavailable.

I tried "wget -O - https://anl.box.com/shared/static/4kd2gxnf4gtk4w1c8eua5fsua22kvgjb.xz" and got 
--2022-08-12 11:29:46--  https://anl.box.com/shared/static/4kd2gxnf4gtk4w1c8eua5fsua22kvgjb.xz
Resolving anl.box.com (anl.box.com)... 107.152.26.197
Connecting to anl.box.com (anl.box.com)|107.152.26.197|:443... connected.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
HTTP request sent, awaiting response... 503 Service Unavailable
2022-08-12 11:29:47 ERROR 503: Service Unavailable.

Is there something wrong with the site?

**Comment by paulromano** [comment]
@spfeiffer1 I just tried it and it seems to work fine. Can you try again and see if it's resolved at this point?

**Comment by spfeiffer1** [comment]
It's working now.  Thank you!

**Comment by yardasol** [comment]
This does happen from time to time, but I think more an ANL side issue than anything to do with OpenMC.
