### ISSUE TITLE
Cannot re-run openmc after opening statepoint file without manual closure

### ISSUE THREAD

**Issue by mkreher13** [openmc-dev/openmc#2206]
Once a statepoint is opened (to get tallies for example), users cannot re-run openmc because the summary file is not accessible. The summary file is automatically opened when the statepoint file is loaded, but it is never closed. I haven't found a function documented that easily allows the user to close the summary file before continuing with other runs. 

See this discussion on the discourse: [ERROR: Failed to open HDF5 file with mode ‘w’: summary.h5](https://openmc.discourse.group/t/error-failed-to-open-hdf5-file-with-mode-w-summary-h5/1360). I just ran into the same problem. My solution was to use `openmc.StatePoint.__exit__()` which is not a function meant to be called by users. 

The issue arises if a script calls for multiple OpenMC runs with statepoint files being read in between runs. I think it is reasonable for users to be able to write scripts in which multiple OpenMC runs are called while accessing statepoint files in between. So, a function like `openmc.StatePoint.close()` seems necessary.

**Comment by yardasol** [comment]
Great catch @mkreher13! This actually is relevant to some current work I'm doing, so I might try and take a crack at this unless you're already working on it.

**Comment by pshriwise** [comment]
Agreed! Unless I'm missing something, this method has already been added in #1854. Hopefully I caught you before you dove in, @yardasol.

The [troubleshooting section of the documentation](https://docs.openmc.org/en/stable/usersguide/troubleshoot.html#runtimeerror-failed-to-open-hdf5-file-with-mode-w-summary-h5) has been updated to reflect recommended practices around accessing the statepoint file and performing subsequent runs, but the notes on these practices w/ statepoint files may not have proliferated yet. 

I'll make sure to add a link to this section of the troubleshooting documentation to the discourse thread @mkreher13 provided to help spread the word.

**Comment by mkreher13** [comment]
Oh, thank you for pointing that out! You know, I am off on a thesis branch of OpenMC, and I can't pull from the develop branch anymore because it's incompatible with my thesis work. It's not uncommon that I run into issues that have already been resolved, and I sometimes forget to switch over to develop to make sure it's still relevant. Ooops.

**Comment by shimwell** [comment]
![Screenshot from 2022-09-09 16-31-46](https://user-images.githubusercontent.com/8583900/189387521-3ff31f65-a304-4b06-8ccb-f27277ff044c.png)

I think this bug :bug: might have survived and lives on in development branch as I'm seeing this error when I run multiple simulations from a single script. I should reduce the script to a minimal version and share the script

**Comment by mkreher13** [comment]
I think the behavior is expected to continue, but now users can call the statepoint's `close()` function to fix it.
