### ISSUE TITLE
feature request: RegularMesh from universe class method

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2210]
I find myself making RegularMesh that encompass the entire geometry quite often. When making weight windows, flux maps or dose maps.

We have ```Universe.bounding_box``` property and I was wondering if anyone else would like a new class method on the ```RegularMesh``` class so that regular meshes can be made from a universe.

This would automatically set ```lower_left``` and the ```upper_right``` using the universe.bounding_box

Perhaps not a huge saving for the user but let me know if this is a worthwhile upgrade and I can make a PR

usage
```python
mesh = openmc.RegularMesh.from_universe(my_universe, dimension=[100, 100, 100])
```

current method
```python
mesh = openmc.RegularMesh()
mesh.dimension = [100, 100, 100]
mesh.lower_left = geometry.bounding_box[0]
mesh.upper_right = geometry.bounding_box[1]
```

additional code required in mesh.py
```python
    @classmethod
    def from_universe(cls, universe, dimension=[10, 10, 10], mesh_id=None, name=''):
        """Create mesh from an existing openmc universe

        Parameters
        ----------
        universe : openmc.Universe
            Open used as a template for this mesh
        dimension : Iterable of int
            The number of mesh cells in each direction.
        mesh_id : int
            Unique identifier for the mesh
        name : str
            Name of the mesh

        Returns
        -------
        openmc.RegularMesh
            RegularMesh instance

        """
        cv.check_type('rectangular lattice', universe, openmc.Universe)

        mesh = cls(mesh_id, name)
        mesh.lower_left = universe.bounding_box[0]
        mesh.upper_right = universe.bounding_box[1]
        mesh.dimension = dimension

        return mesh
```

**Comment by paulromano** [comment]
`Universe` is one of several classes that has a `bounding_box` property (`Cell`, `Region`, `Geometry` also do), so if we were to do this, we'd probably want to make it more general

**Comment by pshriwise** [comment]
Agreed @paulromano. A few instance type checks, new parameter name for `universe`, and an update to the docstrings should get us pretty close I think.
