### ISSUE TITLE
Thermoluminescence Dosimeter, He-3 Proportional counter

### ISSUE THREAD

**Issue by rubayetalamnse** [openmc-dev/openmc#2220]
I want to simulate TLD-600 AND TLD-700, and I want to simulate the glow curve for a certain neutron source. How can I do that?

**Comment by ahnaf-tahmid-chowdhury** [comment]
There is a repository available named [BSUnfold] (https://github.com/kpws/BSUnfold). For TLD600 and TLD700, you may check this [csv](https://github.com/kpws/BSUnfold/blob/master/expData/cms1_tld.csv) file.

For glow curve analysis, there is a python package available called [gcpy](https://github.com/flome/gcpy).

There is a repository named as [GlowCurveAnalysis](https://github.com/JeremyHepker/GlowCurveAnalysis) which uses c++ language for plotting glow curve for TLD100 TLD300 and TLD400.

**Comment by rubayetalamnse** [comment]
thank you @ahnaf-tahmid-chowdhury. I understand the fact @paulromano.
