### ISSUE TITLE
Surface Source Write/Read in 0.13.1: *Time*

### ISSUE THREAD

**Issue by yrrepy** [openmc-dev/openmc#2223]
Hello,

I believe I have found a bug in OpenMC 0.13.1.
I am producing custom Surface Source Files from MCPL using the Python API. (openmc.write_source_file, etc...)

I am finding that Surface Source Files produced via the 0.13.1 API will not work in OpenMC EXE (in 0.12.2 nor in 0.13.1).

If I produce the Surface Source File via 0.12.2 API, it will run in both OpenMC EXE 0.12.2 and in 0.13.1

I believe the issue is the 0.12.2 API is producing the RSSA **w/o** *time*, whereas 0.13.1 API is producing it with *time*, but the OpenMC 0.13.1 EXE does not want to accept the RSSA with time.

I am using:
- Python3.8
- OpenMC 0.12.2 and 0.13.1 (stable GIT releases, compiled by me with OneAPI).
- The Python API of the respectively built OpenMCs.

Regards,
Perry

Below is the error in OpenMC 0.13.1:

                | The OpenMC Monte Carlo Code
       Copyright | 2011-2022 MIT, UChicago Argonne LLC, and contributors
         License | https://docs.openmc.org/en/latest/license.html
         Version | 0.13.1
        Git SHA1 | 33bc948f4b855c037975f16d16091fe4ecd12de3
       Date/Time | 2022-09-18 00:58:13
  OpenMP Threads | 16

   Reading settings XML file...
   Reading source file from ../**********************.time.20.h5...
   ERROR: Source site attributes in file do not match what is expected for this
        version of OpenMC. File attributes = (r, u, E, time, wgt, delayed_group,
        surf_id, particle). Expected attributes = (r, u, E, wgt, delayed_group,
        surf_id, particle)

**Comment by paulromano** [comment]
Thanks for reporting this @yrrepy. You are, unfortunately, 100% correct. This is a bug that is my fault :disappointed: I have a fix ready to go and will submit a PR shortly.
