### ISSUE TITLE
Bug: `xsdir` file created by `njoy.make_ace` and `njoy.make_ace_thermal` doesn't specify the path to the `ace` file.

### ISSUE THREAD

**Issue by yardasol** [openmc-dev/openmc#2236]
When using `njoy.make_ace` or `njoy.make_ace_thermal`, the  `xsdir` file created conatins `filename route` instead of the path to the `ace` file. I am not too familiar with NJOY, so I am not sure if this is a limitation of the tool or there is something missing from the `njoy.py` file to enable writing the path to the ace file to `xsdir`.

Here is my input fpr `make_ace`:

```python
openmc.data.njoy.make_ace('endfb71_ace/neutrons/n-006_C_000.endf',
                          temperatures=[900])
```
and this is the `xsdir` file looks like:
```
  6000.01c   11.898000 filename route 1   1   111227     0     0 7.756E-08
```

Here is the input for `make_ace_thermal`:
```python
openmc.data.njoy.make_ace_thermal('endfb71_ace/neutrons/n-006_C_000.endf',
                                  'endfb71_ace/thermal_scatt/tsl-graphite.endf',
                                  temperatures=[800, 1000])
```
and again, the `xsdir` file:
```
 graph.01t   11.898000 filename route 1 1    848566     0     0 6.894E-08
 graph.02t   11.898000 filename route 1 1    832377     0     0 8.617E-08
```

I am sourcing my ENDF files from [NNDC](https://www.nndc.bnl.gov/endf-b7.1/download.html).

**Comment by paulromano** [comment]
This is just the behavior of NJOY itself, so there's nothing we can do about it. Here are the relevant lines in NJOY:
https://github.com/njoy/NJOY2016/blob/1cb7237b89c92eb7a469e3727179cf439835d3ea/src/acefc.f90#L12982-L12990
