### ISSUE TITLE
Plotting universes in MG with library specified on materials

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#2244]
Plotting a universe containing materials with macroscopic cross sections fails if the cross section library is not specified using the `OPENMC_MG_CROSS_SECTIONS` environment variable.

When a new model is created in the `openmc.Unvierse.plot` method, it is exported in a temporary directory and a new `openmc.Materials` object is created, but its `cross_sections` attribute will not be set. The plot execution will then fail to find the cross sections on initialization.

```python
RuntimeError: No mgxs.h5 file was specified in materials.xml or in the OPENMC_MG_CROSS_SECTIONS environment variable. 
OpenMC needs such a file to identify where to find MG cross section libraries. Please consult the user's guide at 
https://docs.openmc.org/ for information on how to set up MG cross section libraries.
```

**Comment by paulromano** [comment]
Yeah, this is pretty similar to #2189 and part of the reason why I developed #2221 (openmc.config), which gives us the option to set the library without having to directly manipulate an environment variable

**Comment by paulromano** [comment]
See associated documentation [here](https://docs.openmc.org/en/latest/usersguide/data.html#runtime-configuration)

**Comment by pshriwise** [comment]
Closing since there's an existing solution.
