### ISSUE TITLE
Cylinder meshes to allow non central location

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2248]
As mentioned by @paulromano in PR #2233 the ```CylindricalMesh``` is central around a location.

We could allow for an x,y,z offset that defaults to (0,0,0).

Also tagging @RemDelaporteMathurin

**Comment by RemDelaporteMathurin** [comment]
I'm currently having a look at this.

It seems that all the mesh coordinates in the python API are in cylindrical/spherical coordinates (except for `write_data_to_vtk()` where we do the conversion in mesh.py) .
The base change to cartesian coordinates must be done somewhere in the C++ lib. (@paulromano ?)

This offset (which is in fact the centre of the mesh) should be added to the mesh vertices in **cartesian** coordinates.

**Comment by shimwell** [comment]
I think you are on the right track @RemDelaporteMathurin. 

The C++ side you need some extra math to offset the voxel locations in the code block you found.

Also we would need the c++ to read in another xml element tag a few lines above, in a similar manner to reading in the r_grid, phi_grid, z_grid
```
origin = get_node_array<double>(node, "origin");
```

Also we would need the python side to write out the origin xml tags

Adding something like this to the ```to_xml_element``` [method](https://github.com/openmc-dev/openmc/blob/434dc1f30d4d10105b9025adf4498b7f1321b89c/openmc/mesh.py#L1140-L1163
)
```python
subelement = ET.SubElement(element, "origin")
subelement.text = ' '.join(map(str, self.origin))
```

**Comment by pshriwise** [comment]
Very on board with this! I've been meaning to add it in. Let me know if you'd like a hand with anything @RemDelaporteMathurin.
