### ISSUE TITLE
Error when calling decay_photon_energy on stable isotope

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2250]
When calling ```decay_photon_energy``` on a material which has no gamma decays the code raises an indexError

in this case ```dists``` is ```[]``` so ```dists[0]``` is not possible

Perhaps we should add some error handling for empty lists to ```combine_distributions```

Code to reproduce
```python
import openmc
openmc.config['chain_file']='chain-endf.xml'
a=openmc.Material()
a.add_nuclide('Li6',1)
a.volume=1
a.decay_photon_energy
```
error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/openmc/openmc/material.py", line 276, in decay_photon_energy
    return openmc.data.combine_distributions(dists, probs)
  File "/home/openmc/openmc/stats/univariate.py", line 1252, in combine_distributions
    return dist_list[0]
IndexError: list index out of range
```

**Comment by paulromano** [comment]
Oops! Thanks for reporting @shimwell. I'll submit a fix for this shortly.
