### ISSUE TITLE
Wrong unit of flux in Jupyter Notebook Example

### ISSUE THREAD

**Issue by ray-pH** [openmc-dev/openmc#2294]
In the [Notebook Example for Tallying Flux Spectrum](https://nbviewer.org/github/openmc-dev/openmc-notebooks/blob/main/flux-spectrum.ipynb) the unit given for flux is `[n/cm-src]`. Based on the [Documentation for Tally](https://docs.openmc.org/en/stable/usersguide/tallies.html) it should be `[n-cm/src]`. This might be confusing and misleading for beginners.

**Comment by pshriwise** [comment]
Thanks for bringing this to us @ray-pH! I've opened a [PR](https://github.com/openmc-dev/openmc-notebooks/pull/5) with a correction.

**Comment by paulromano** [comment]
Closing as the PR referenced above has been merged. Thanks @ray-pH and @pshriwise!
