### ISSUE TITLE
Rename `max_split` parameters.

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#2308]
There's currently a `max_split` parameter on both the `Settings` and `WeightWindow` classes. The parameter on settings limits the number of times a particle can be split over its entire history and the other limits the number of splits per weight window chcek.

Renaming these parameters for to distinguish them by their purpose would be helpful.

**Comment by shimwell** [comment]
How about ```lifetime_max_splits``` and ```max_splits_per_ww```

**Comment by paulromano** [comment]
Closed by #2954
