### ISSUE TITLE
Implement more efficient sampling  for large discrete PDFs

### ISSUE THREAD

**Issue by gonuke** [openmc-dev/openmc#2328]
The general `Discrete` distribution uses a linear search with no caching of the CDF when sampling.  Two improvements are recommended:
1. calculate and store the CDF instead of the PDF on initialization and implement a binary search of the CDF
2. alias tables allowing for O(1) sampling of extremely large discrete PDFs

**Comment by gonuke** [comment]
May also want to add some robustness checks - sum(PDF) > 0 and PDF_i > 0

**Comment by paulromano** [comment]
@myerspat already has an implementation of alias sampling in the works actually!
