### ISSUE TITLE
Tally triggers exit early if results are null

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#2343]
At a trigger checkpoint, a tally trigger is considered satisfied if the mean of the score is zero. If one applies a tally with a `fission` score and corresponding trigger to the model described in #2342 (a model without any fissionable materials), the simulation will always complete at the first trigger checkpoint. 

I'd argue that this shouldn't be the default behavior and that the simulation should continue to account for the possibility that particles haven't reached the right region of phase space to contribute to the tally yet. A message for the user that the score has no contributions yet would be useful to indicate that the score may be invalid for the simulation.

**Comment by paulromano** [comment]
Closed by #2344
