### ISSUE TITLE
mamba install openmc fails

### ISSUE THREAD

**Issue by TankTech** [openmc-dev/openmc#2350]
I installed mamba by conda to install OpenMC finally following the document, but there is nothing to find after implementing mamba search openmc:

```
Loading channels: done
No match found for: openmc. Search: *openmc*
Name                       Version           Build  Channel             
openmc-plotter                 0.2.0    pyhd8ed1ab_0  conda-forge    
```

I haven't found a similar issue here, let me know if this is something that you have encountered before.

Thanks in advance for your help with this.

**Comment by Allentro** [comment]
What's the result if you enter `mamba --version`?

**Comment by shimwell** [comment]
By any chance are you running this command from Windows.

If so then that would explain why nothing is found.

The conda distributions is currently only available for Mac OS and Linux.

**Comment by kkktttaan** [comment]
> mamba --version
mamba 1.1.0
conda 22.11.1

I think it is the latest version.

**Comment by kkktttaan** [comment]
> By any chance are you running this command from Windows.
> 
> If so then that would explain why nothing is found.
> 
> The conda distributions is currently only available for Mac OS and Linux.
> 
> Current options for Windows is to use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) or Docker

Sorry for this ambiguous description. Actually, I run those commands on Mac OS.

**Comment by lewisgross1296** [comment]
I'm not sure if it is related, but I opened a [PR](https://github.com/openmc-dev/openmc-notebooks/pull/8) in `openmc-dev/openmc-notbooks` and the CI is also failing due to mamba/conda, despite my changes not having anything to do with mamba/conda. You can check my error report [here](https://github.com/openmc-dev/openmc-notebooks/actions/runs/3916296651/jobs/6713686029). Does it look similar to yours @kkktttaan?

**Comment by pshriwise** [comment]
I think this related to the github action being used to setup the conda environment. Several others have posted error reports from GAH in [this issue](https://github.com/conda-incubator/setup-miniconda/issues/274) that look similar to yours @lewisgross1296. It seems they have just merged a fix a few hours ago. I'll try re-running CI on your PR one more time, but if that doesn't work we can keep an eye on the status of that thread for workarounds or a new solution.

**Comment by kkktttaan** [comment]
> 

it is not similar to mine seemingly. I have installed OpenMC on my desktop (Linux) successfully. Maybe there is no problem with mamba/conda because mamba and conda all work for other packages on my laptop (MAC).

**Comment by pshriwise** [comment]
@kkktttaan are you still having trouble with this?

**Comment by paulromano** [comment]
I have done a mamba install of OpenMC recently and everything seemed to go fine. I'm going to close this out but if any of you are still experiencing issues, feel free to reopen or post a message on our [discussion group](https://openmc.discourse.group/).
