### ISSUE TITLE
CI failing due when mpi=y build

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2366]
I recently made two minor PRs (#2365, #2364) and the CI failed in the same place for both of them

with this error message

```
error in mpi4py setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '!=3.4.*''
```

I reran parts of the CI ```(mpi=n)``` that don't use MPI and they appear to be working fine

After a bit of searching it appears others have also come across [this issue ](https://github.com/h5py/h5py/issues/2222)and it has kindly been raised in the h5py repo and there are already some possible solutions :+1: .

**Comment by shimwell** [comment]
Looks like we could alternatively pin the latest h5py after this PR is merged in
https://github.com/h5py/h5py/pull/2225/files

**Comment by paulromano** [comment]
I think we actually should be doing `--no-build-isolation` even with that fix since we want to build h5py against the specific version of mpi4py that was built against MPICH.
