### ISSUE TITLE
Feature request: DAGMCUniverse to support get_all_universes

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2387]
When we call ```.get_all_universes()``` on a ```Geometry``` that is a ```Universe``` that is filled with a DAGMC cell we get this error. ```Universe```  has the attribute but as the code cycles through the individual  parts it calls ```.get_all_universes()``` on each part and fails when it reaches the DAGMCUniverse

```python
>>>AttributeError: 'DAGMCUniverse' object has no attribute 'get_all_universes'
```

code to reproduce 

```python
import openmc
bound_dag_univ = openmc.DAGMCUniverse(filename='dagmc.h5m').bounded_universe()
my_geometry = openmc.Geometry(root=bound_dag_univ)
my_geometry.get_all_universes()
```

Could we add the same ```get_all_universes()``` method that is in ```Universe``` to the ```DAGMCUniverse```?

Alternatively could we move  ```get_all_universes()```  from ```UniverseBase``` to  ```Universe``` so that the  ```DAGMCUniverse``` inherits it?

**Comment by shimwell** [comment]
Happy to put in a PR to move the method to the ```UniverseBase``` class if others think that is the way to go?

**Comment by paulromano** [comment]
Sounds reasonable to me, but @pshriwise is the DAGMC god so I defer to him on this

**Comment by pshriwise** [comment]
Totally reasonable @shimwell. I ran into this as well and have a change to this effect in a local branch. A PR that addresses this specifically would be most welcome.
