### ISSUE TITLE
Simulation restart isn't terminated correctly

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#2389]
As @eepeterson and I were discussing restart capabilities today, I noted that the restart of a problem without editing the number of batches in the `settings.xml` file results in an unbounded simulation. I believe this is caused by the following lines in `simulation.cpp`:

https://github.com/openmc-dev/openmc/blob/6e2a9add5ef5019147e20422c380900c9b4a21a4/src/simulation.cpp#L238-L246

When a restart occurs and the initial number of batches read from the statepoint file is equal to `settings::n_max_batches` set by the `settings.xml` file, the simulation will continue indefinitely.

This probably should be caught here:

https://github.com/openmc-dev/openmc/blob/6e2a9add5ef5019147e20422c380900c9b4a21a4/src/state_point.cpp#L406-L409

I think a couple of changes are in order:

  - change the check in `simulation.cpp`  from `==` to `>=`
  - change the check in `state_point.cpp` from `>` to `>=` and update the error message appropriately

**Comment by eepeterson** [comment]
Thanks @pshriwise - This wasn't actually the issue I was having (which is not actually an issue in the end), but can confirm this behavior as well and your fix should solve the problem.
