### ISSUE TITLE
Spherical mesh VTK coordinates bug

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#2416]
As I was working on #2397, I noticed that spherical meshes with a `theta_grid` property covering only part of  [0, $\pi$] resulted in an incorrect mesh

```python
import openmc
import numpy as np
sphere_mesh = openmc.SphericalMesh()
sphere_mesh.r_grid = np.linspace(0, 50, 31)
sphere_mesh.theta_grid = np.linspace(0, 0.5 * np.pi, 11)
sphere_mesh.phi_grid = np.linspace(0, 2*np.pi, 21)
sphere_mesh.write_data_to_vtk('test.vtk', datasets={})
```

![image](https://user-images.githubusercontent.com/4563941/223874698-279dc6a5-c318-4cb0-a035-ec4437ea9f14.png)

This is caused by incorrect use of $\phi$ and $\theta$ in the `SphericalMesh.write_data_to_vtk` method:

https://github.com/openmc-dev/openmc/blob/9768e34b869e9d698282778d2397bf9a982ed24f/openmc/mesh.py#L1536-L1538

The meaning of these variables in spherical coordinates have opposite conventions in mathematics and physics. This can be confusing. Our implementation adopts the one used in physics. After correcting these lines, the VTK file is correct:

![image](https://user-images.githubusercontent.com/4563941/223875754-502c54a1-15ab-4bd9-85b0-d46f4491ef49.png)

I'll submit a PR with this fix and some additional test coverage shortly.

**Comment by paulromano** [comment]
Closed by #2417

**Comment by pshriwise** [comment]
This bug was reintroduced by #2256. I'll open a PR shortly to correct the issue.

**Comment by pshriwise** [comment]
And I suppose I'll improve the related test since reverting the code didn't trigger a failure...
