### ISSUE TITLE
Inquiry of cell nuclides or materials

### ISSUE THREAD

**Issue by simpledpr** [openmc-dev/openmc#2426]
If a larger universe is filled into a small cell, cell.get_nuclides() returned a list of all nuclides included in the universe even if it is not actually included in the cell because of cutoff by cell boundaries. This caused a problem in MGXS generation. Simply speaking, the nonexisting nuclide will be given zero densities and contained in the built openmc.mgxs.Library object while the actual nuclide densities calculated with statistical volume calculation contain only those nuclides actually presented in the cell, which makes sense. After simulation, when I use openmc.mgxs.Library.load_from_statepoint  and try to build an MGXS library with library.create_mg_library, the zero density nuclide led to NaN values (the Python API openmc.mgxs.get_xs does not check this).

Is it possible to return only those nuclides/materials that are actually present in a cell rather than simply return self.fill.get_nuclides()?

**Comment by pshriwise** [comment]
This is unfortunately something that would be difficult to detect in a call like `get_nuclides()` from the Python API. Determining which materials/nuclides in a universe are excluded from the interior of a cell that is filled with that universe is non-trivial. A volume calculation could in theory be used to do this, but I think that would be an overly complicated and non-robust solution. To me, this sounds like something that should be handled in the MGXS generation code to ignore nuclides with tally values of zero.

**Comment by simpledpr** [comment]
Yes, I did volume calculations and I simply modified cell.py in this way to utilize the _atoms field:
def get_nuclides(self):
        ...
        if self._atoms is not None:
            return list(self._atoms.keys())
        else:
            return self.fill.get_nuclides() if self.fill_type != 'void' else []

In any case, we need to provide volume information and the total number of atoms in a tallied region if we like to have microscopic cross sections. This will avoid those nuclides to be included in openmc.mgxs.Library objects. How do you think? @pshriwise

**Comment by pshriwise** [comment]
Mmm yes that's a fair point about the atom densities. What we may want to use here instead is the `Cell.get_nuclide_densities` method. I can see that this method prefers to get the atom densities from the cell material if possible, though. Maybe we should add some code that allows for preference of one over the other?

Atom density retrieval aside, it still seems like our MGXS module should be handling cross section generation with null tally values more cleanly.

**Comment by paulromano** [comment]
@simpledpr None of our current developers are actively working on the `mgxs` module. That module was primarily developed by several students from MIT, none of whom are active at this point in OpenMC development. If you want to propose improvements through a pull request, it would certainly be welcome!
