### ISSUE TITLE
Cross section flux at half height for a fuel assembly

### ISSUE THREAD

**Issue by luisdejuan** [openmc-dev/openmc#2484]
I want to make a rectangular 2D plot that shows the flux of the midplane (z=0) of a fuel assembly. I tried using 2 methods that lead to different results:
1. 2D mesh.
```
mesh = openmc.RegularMesh()
mesh.dimension = [200, 200]
mesh.lower_left = [-lattice_width/2, -lattice_width/2]
mesh.upper_right = [lattice_width/2, lattice_width/2]
mesh_filter = openmc.MeshFilter(mesh)

tally = openmc.Tally(name = 'flux')
tally.filters = [mesh_filter]
tally.scores = ['flux']
tally.export_to_xml()

# after running...

spectrum = sp.get_tally(name='flux')
flux = spectrum.get_slice(scores=['flux'])

flux.mean.shape = (200, 200)
flux.std_dev.shape = (200, 200)

fig = plt.subplot(111)
plt.imshow(flux.mean)
plt.colorbar()
```

Result:
![Flux_2D](https://user-images.githubusercontent.com/131185127/232835782-61717720-49ee-4999-a629-67065abab21b.jpg)

2. 3D mesh
```
mesh = openmc.RegularMesh()
mesh.dimension = [200, 200, 1]
mesh.lower_left = [-lattice_width/2, -lattice_width/2, -10]
mesh.upper_right = [lattice_width/2, lattice_width/2, 10]
mesh_filter = openmc.MeshFilter(mesh)

tally = openmc.Tally(name = 'flux')
tally.filters = [mesh_filter]
tally.scores = ['flux']
tally.export_to_xml()

# after running...

spectrum = sp.get_tally(name='flux')
flux = spectrum.get_slice(scores=['flux'])

flux.mean.shape = (200, 200)
flux.std_dev.shape = (200, 200)

fig = plt.subplot(111)
plt.imshow(flux.mean)
plt.colorbar()
```

Result:
![flux_3D](https://user-images.githubusercontent.com/131185127/232836266-ff1dda2c-0f73-4a13-922e-57ce871cd490.jpg)

Question: In method 1, how do we know at which z-plane is cutting the cross-section? Cannot be an average of the whole height because then we would get a lower value than by method 2. Which would be the correct answer? Is there a better or correct way to do this?

Thank very much in advance

**Comment by ranhoujunzi123** [comment]
Why can't I run it with your code
![QQ截图20230502163108](https://user-images.githubusercontent.com/132341979/235618156-bc930b28-17b1-4274-a50e-1beb03fc8612.png)

**Comment by ranhoujunzi123** [comment]
![QQ截图20230502163249](https://user-images.githubusercontent.com/132341979/235618348-2ee8bef6-a0d9-4c38-a8f6-acd3781fbfee.png)

**Comment by shimwell** [comment]
Sorry this is not an exact answer to your question but I wanted to mention this draft pull request allows one to get a slice of regular mesh data on a specified slice index

https://github.com/openmc-dev/openmc/pull/2491

might be helpful

**Comment by pshriwise** [comment]
> Question: In method 1, how do we know at which z-plane is cutting the cross-section? Cannot be an average of the whole height because then we would get a lower value than by method 2. Which would be the correct answer? Is there a better or correct way to do this?

Hi @luisdejuan! When using a 2D mesh in the XY plane, the Z dimension is unbounded. So the plot you've generated shows the tally contribution over the entire assembly axially. It's the equivalent of setting the Z bounds of the regular mesh in your second method to +/- inf.

As for why the first plot looks a jumbled mess and the second is coherent, I think that will have to do with the ordering of the data when reshaped before being passed to the plotting function. I'll play around with this example a bit to see if we can make it more intuitive to plot 2D meshes.

Thanks for sending this our way!

**Comment by ranhoujunzi123** [comment]
@pshriwise thank you.I'm a beginner. I don't know how to define it（sp）

**Comment by pshriwise** [comment]
> @pshriwise thank you.I'm a beginner. I don't know how to define it（sp）

No problem! Welcome to the user base :) 

After you've run your simulation, a statepoint file will be produced that you can open in Python to extract results. You'll want to create an `openmc.StatePoint` object with something like:

```python

sp_filename = 'statepoint.10.h5' # this name may change for you depending on simulation parameters
statepoint = openmc.StatePoint(sp_filename)

# call get_tally 
statepoint.get_tally(name='flux')
...
```

I'd suggest taking a look at the [post-processing notebook](https://github.com/openmc-dev/openmc-notebooks/blob/main/post-processing.ipynb) in the examples repo when you have a chance.

**Comment by pshriwise** [comment]
@ranhoujunzi123 I'm going to close this thread for now given that there isn't an issue here related to code development. 

I'll direct you to the discourse forum: https://openmc.discourse.group/ where we like to keep answers to these types of questions surrounding use of OpenMC. There are many previous threads/questions that could help you out as you move forward and there are more people looking at those threads to provide you with assistance than there are here.

Thanks for reaching out about your issue!
