### ISSUE TITLE
Dagmc Universe not found when running from Model.XML

### ISSUE THREAD

**Issue by Adambar24** [openmc-dev/openmc#2490]
An error occurs when searching for the location of the dagmc universe file when running openmc from a single model XML file. In 0.13.3 the export_to_model_xml was added. If you use this function with a DAGMC universe H5M, as part of the model, openmc cannot find the file when it is ran with the command line:

``
$ openmc model.xml
``

When using this command (assuming you are already in the directory of the model file) openmc searches for the dagmc file in the model.xml file causing an error because model.xml as it is not a directory. Though if i replicate it with the export_to_xml function and create separate xml files and run:

``
$ openmc ./path/to/directorywithXML
``

With the .h5m and XML files in this directory it runs fine. I presume the when openmc searches for the DAGMC univserve file it using the same code in both cases and looking in the directory passed to openmc. Which will work in the second case but not in the new case where you can run model.xml and have to pass the model.xml file. 

A change to make Openmc look at the directory inwhich the model.xml in is or a separately supplied path would work

**Comment by Adambar24** [comment]
Also to add to this it can only find the DAGMC universe file if you:

`cd /home/username/somemodel `<br>`openmc`

Rather than 

`openmc /home/username/somemodel`

**Comment by pshriwise** [comment]
Hi @Adambar24!

Thanks very much for reporting this. I'll put some thought into how we can best support some of these cases or update our documentation to indicate requirements more clearly.

**Comment by paulromano** [comment]
Resolved by #2842
