### ISSUE TITLE
should tally.nuclides docstring request list of strings?

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2525]
I was just making use of ```tally.nuclides``` and accidentally set it to a list of strings and delighted that it worked.

I notice the doc string asks for a list of ```openmc.Nuclide```

https://github.com/openmc-dev/openmc/blob/d8dbd9bfca5f9e8faf992422149ff0573fb49551/openmc/tallies.py#L59

Should this be change this to list of ```str```?

**Comment by pshriwise** [comment]
Yeah I'd say we can update that to `list of openmc.Nuclide or str`.
