### ISSUE TITLE
IncidentNeutron.From_njoy method fails for larger isotopes

### ISSUE THREAD

**Issue by mlazaric97** [openmc-dev/openmc#2529]
Hello, I am using the method "IncidentNeutron.from_njoy" to read in an ENDF file and export it to an hdf5. I am able to do this for some but not all of the nuclides. I have been able to do this with Fe-56 and K-39 however it has failed with U-235, Pu-239, Pu-238, Gd-157. NJOY begins to run, goes through all modules save "acer" then returns a fortran runtime error.  

Here is what my code looks like: 
"""
example = openmc.data.IncidentNeutron.from_njoy( 'file_name.endf', temperatures = [0.0], stdout = True)
example.export_to_hdf5( 'new_file_name.h5')
"""

Here "file_name.endf" is **directly** from the ENDF/B release with no edits. 

For the cases that do work(ex. K39) the NJOY output looks as follows:

njoy
**********************
reconr...                                                                                                           0.0s
-- message from rdf2bw---calculation of angular distribution not installed. 
broader...                                                                                                         2.0s
heatr...                                                                                                             3.1s
graspr...                                                                                                           5.0s
purr...                                                                                                               8.3s
mat = 1925                                                                                                      8.3s

---message from purr---mat 1925 has no unresolved parameters
                                              copy as is to nout
acer...                                                                                                               8.6s
                                                                                                                         13.8s
*********

For the not working cases the same error keeps popping up during the running of the acer module. This error is as follows:

at line 852 of file /PATH_TO_NJOY2016/src/endf.f90 (unit = 26, file = 'tape26')
fortran runtime error: Bad value during floating point read. 

The rest of the error message is a back trace through memory addresses culminating in 

"subprocess.CalledProcessError: Command 'njoy' returned non-zero exit status 2. 

For this case the ENDF file is 'n-094_Pu_238.endf' from ENDF/B-Viii.0 however the same error message pops up when looking at a variety of evaluations as mentioned at the start of the question. 

Do you have any suggestions for how to either fix or work around this issue? 

Thank you for your time. Please let me know if I can provide more information on this issue. 

Python version = python 3.10.8
OS = macOS Monterey version 12.4

**Comment by shimwell** [comment]
Thanks for posting. I've noticed a few releases of NJOY recently and have not generated ENDF/B8.0 with the latest version yet. I wonder if something has changed there.

Would you be able to run this script from the data processing repository and let us know if you get the same error

https://github.com/openmc-dev/data/blob/master/generate_endf.py

**Comment by gridley** [comment]
I also encountered this not long ago. Looked a little at the code, and boy, this seems absolutely miserable to debug. Messy, messy fortran...

**Comment by shimwell** [comment]
I maintain another less official package that you are welcome to try

https://github.com/openmc-data-storage/openmc_data

This one has some testing to check the URLs work periodically. It still certainly fails from time to time but might be worth a try

**Comment by paulromano** [comment]
@mlazaric97 I believe the problem here is that you are passing a temperature value of 0.0. I don't think NJOY can properly process an ENDF file all the way through ACE with a temperature of 0 K (results in divide-by-zeros, which results in bad values, hence the error you're seeing). A common workaround is to use a small but non-zero value, like 0.1 K (this is what the LANL nuclear data team does even for the [official ACE data files](https://nucleardata.lanl.gov/ace/lib80x) for MCNP). In any case, the bug here is really downstream in NJOY so this is not something we can fix.
