### ISSUE TITLE
openmc.deplete.MicroXS.from_model() throws missing kwarg error

### ISSUE THREAD

**Issue by jlball** [openmc-dev/openmc#2530]
When trying to run `openmc.deplete.MicroXS.from_model()` to generate a MicroXS object for setting up a transport-independent depletion operator I encounter the following error:

File "independent-depletion-arc-1.py", line 85, in <module>
    U_micro_xs = openmc.deplete.MicroXS.from_model(U_device,
  File "/home/jlball/openmc/openmc/deplete/microxs.py", line 99, in from_model
    statepoint_path = model.run(**run_kwargs)
TypeError: run() got an unexpected keyword argument 'cwd'

**Comment by jlball** [comment]
Tested with pull request #2523,  does not seem to resolve the problem.

**Comment by gridley** [comment]
Are you able to share your input? Can you paste the output of `openmc -v`, too?

**Comment by jlball** [comment]
You can find my full input script here: [https://github.com/jlball/arc-nonproliferation/blob/master/openmc-scripts/arc-1/independent_depletion/independent-depletion-arc-1.py](https://github.com/jlball/arc-nonproliferation/blob/master/openmc-scripts/arc-1/independent_depletion/independent-depletion-arc-1.py)
 
and here is the output of `openmc -v` :

OpenMC version 0.13.4
Git SHA1: ec220fa9899e92869f8a110987c9dd3282fb7ac1
Copyright (c) 2011-2023 MIT, UChicago Argonne LLC, and contributors
MIT/X license at <https://docs.openmc.org/en/latest/license.html>
Build type:            RelWithDebInfo
Compiler ID:           GNU 9.4.0
MPI enabled:           no
Parallel HDF5 enabled: no
PNG support:           yes
DAGMC support:         no
libMesh support:       no
MCPL support:          no
NCrystal support:      no
Coverage testing:      no
Profiling flags:       no

**Comment by paulromano** [comment]
@jlball Looking at your code, you are not passing an `openmc.Model` object but rather a `arc_nonproliferation.Device` object, which subclasses `Model`. Importantly, it overrides the `run` method which breaks the behavior in `MicroXS.from_model`:
https://github.com/jlball/arc-nonproliferation/blob/e138b77918e20a076544ed9eca43d2ba4d53214c/arc_nonproliferation/device.py#L82

**Comment by jlball** [comment]
> @jlball Looking at your code, you are not passing an `openmc.Model` object but rather a `arc_nonproliferation.Device` object, which subclasses `Model`. Importantly, it overrides the `run` method which breaks the behavior in `MicroXS.from_model`: https://github.com/jlball/arc-nonproliferation/blob/e138b77918e20a076544ed9eca43d2ba4d53214c/arc_nonproliferation/device.py#L82

Whoops! Thanks for the catch, my apologies!
