### ISSUE TITLE
Run depletion with all isotopes from depleted material

### ISSUE THREAD

**Issue by Justine-Luminet** [openmc-dev/openmc#2570]
Hello,

Would it be possible to add a feature that enables to specify initial nuclides in a material that have no cross sections (for instance to run a depletion with an already depleted fuel with all the nuclides created) ?

Justine

**Comment by paulromano** [comment]
If you want to run a new depletion calculation with the material compositions that were already determined from a previous OpenMC depletion calculation, this can be done with the `prev_results` argument on `openmc.deplete.CoupledOperator`:
```python
prev_results = openmc.deplete.Results('depletion_results.h5')
op = openmc.deplete.CoupledOperator(..., prev_results=prev_results)
```

Would that satisfy your use case or do you need something a little more general (i.e., not relying on a previous OpenMC depletion simulation)?

**Comment by Justine-Luminet** [comment]
Hello  !
Thanks for the answer, but I don't necessarily  want to use all of the depleted materials for a new depletion (if I want  fresh fuel for instance) so prev_results wouldn't work in that case I think ?

**Comment by paulromano** [comment]
@Justine-Luminet This should now be possible thanks to pull request #2616.
