### ISSUE TITLE
Muir energy spectrum

### ISSUE THREAD

**Issue by giovanni-mariano** [openmc-dev/openmc#2597]
## Bug Description

The helper function openmc.stats.muir return a wrong distribution: the standard deviation is not correctly calculated. The linked document in the function description (https://permalink.lanl.gov/object/tr?what=info:lanl-repo/lareport/LA-05411-MS) shows how to calculate the "W" parameter (page 2, eq. 8): however it is not a standard deviation (as you can see in eq. 7). To get the standard deviation it should be divided by square root of 2.
 
std_dev = math.sqrt(4 * e0 * kt / m_rat) / math.sqrt(2)

**Comment by paulromano** [comment]
Thanks for reporting -- I agree with your assessment. @makeclean do you also agree?

**Comment by pshriwise** [comment]
Turns out this one's on me -- didn't follow that factor through correctly from 7 to 8. Thanks for catching it @giovanni-mariano! I'll submit a fix shortly.

**Comment by paulromano** [comment]
Closed with merging of #2598
