### ISSUE TITLE
CylindricalMesh().from_domain fails for domain away from 0 axis

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2603]
## Bug Description
The ```openmc.CylindricalMesh().from_domain()``` method sometimes makes a cylindrical mesh that misses the geometry. 

I think this is because 0 is used on this line of code
https://github.com/openmc-dev/openmc/blob/3f9cd0d7cb982428295cff25963f4ee2726d34a9/openmc/mesh.py#L1364

Also the ```from_domain``` method does not change the mesh origin and appears to assume the mesh is centered around the Z axis.

Image shows the openmc.Geometry and the mesh don't overlap
![Screenshot from 2023-07-17 14-27-28](https://github.com/openmc-dev/openmc/assets/8583900/1f89e999-9643-45c8-9aa3-e2509228113d)

## Steps to Reproduce

```python
import openmc
import numpy as np
surf = openmc.Sphere(r=10, x0=100, y0=100, z0=100)
cell = openmc.Cell(region=-surf)
my_geometry = openmc.Geometry([cell])
mats = openmc.Materials([])
mats.export_to_xml()
my_geometry.export_to_xml()
c_mesh = openmc.CylindricalMesh().from_domain(domain=cell, dimension=(8,8,8))
c_mesh.write_data_to_vtk(
    filename='test.vtk',
    datasets={'data':np.array([1.]*8*8*8)},
    volume_normalization=True,
    curvilinear=False
)
vox_plot = openmc.Plot()
vox_plot.type = 'voxel'
vox_plot.width = my_geometry.bounding_box.width
vox_plot.origin = my_geometry.bounding_box.center
vox_plot.pixels = [int(w)*10 for w in my_geometry.bounding_box.width]
vox_plot.color_by = 'cell'
vox_plot.to_vtk(output='voxel_plot.vti')
```

## Environment
develop branch of openmc, ubuntu 18.04, installed from source

**Comment by paulromano** [comment]
@shimwell Has this been resolved?

**Comment by shimwell** [comment]
yes sorry, this has been solved
