### ISSUE TITLE
exposing weight window max_splits though openmc.lib

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2607]
## Description
Currently it does not appear possible to set the weight window max splits property when using openmc lib
```python
import openmc.lib
tally = openmc.lib.tallies[55]
wws = openmc.lib.WeightWindows.from_tally(tally, max_split=11) # this does not work
wws.max_split=11  # this does not work
```

## Alternatives
use the python api where the attributes of the WeightWindow class are fully controllable.

## Compatibility
This would add to the existing openmc lib API

**Comment by caderache2014** [comment]
I think this can be closed. According to @shimwell

**Comment by shimwell** [comment]
Thanks
