### ISSUE TITLE
MacOS Cross Section Library Parse Failure with lxml.etree in element.py.

### ISSUE THREAD

**Issue by stchaker** [openmc-dev/openmc#2611]
## Bug Description

When the latest develop branch of OpenMC is compiled from source on the latest MacOS environment, the python API fails to parse cross section libraries, even after the cross section library has been explicitly located through a bash profile environment label.

![image](https://github.com/openmc-dev/openmc/assets/108743711/74308010-8a85-45f8-b4f5-ec394bae8d1f)

To fix the issue I have to change an importation statement in element.py from the following: 

![image](https://github.com/openmc-dev/openmc/assets/108743711/ac79f068-6d68-4813-a55f-21fb2e4dca03)

To this:

![image](https://github.com/openmc-dev/openmc/assets/108743711/6adfee7e-27b3-4664-bdd7-417c2501c3a3)

I am unsure as to why this is occurring. 

## Steps to Reproduce
To reproduce this bug, compile OpenMC from source on the latest version of MacOS and attempt to read any cross section data through the Python API. 

## Environment

Operating System: MacOS Ventura 13.4.1
OpenMC version: latest develop
Open MC installed through source
Nuclear data: ENDFB_71 HDF5 library

**Comment by paulromano** [comment]
I believe this is due to an outdated version of lxml. Try updating the lxml package and see if that fixes it

**Comment by stchaker** [comment]
Ah that did the trick, thanks!
