### ISSUE TITLE
Apply weight window upon crossing surfaces

### ISSUE THREAD

**Issue by XinyanBradley** [openmc-dev/openmc#2624]
## Description

So far weight window splits/roulettes kill are only performed upon collisions, and it would be helpful if weight window can also be applied upon crossing a surface (either mesh surfaces or cell surfaces). Such feature would be beneficial for cases where a large number of particles are desired such as detector response tallies.

## Alternatives

No

## Compatibility

Shouldn't be? Maybe an option to choose the weight window type (collision, crossing surface, or both) just like in MCNP.

**Comment by pshriwise** [comment]
I couldn't agree more @XinyanBradley. This is something we'd like to add to our weight window capabilities soon!

**Comment by paulromano** [comment]
Closed by #2670
