### ISSUE TITLE
openmc.StatePoint.source is has no source details

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2642]
## Bug Description
Running a fixed source simulation and accessing the statepoint.source appears to return None.

## Steps to Reproduce
statepoint = openmc.StatePoint('statepoint.10.h5') 
print(statepoint.source)

## Environment
wsl ubuntu with latest dev branch of openmc

**Comment by paulromano** [comment]
@shimwell I'm pretty sure we've talked about this one before 😄 Once upon a time, fixed source simulations used to store a vector of source particles, the same as what we do for eigenvalue calculations. However this was changed a while ago such that source sites are sampled as needed, so we don't have a single vector of source site data to write to a state point. If you want a bunch of source sites from a fixed source definition, you can use our handy `openmc.lib.sample_external_source` function.

**Comment by shimwell** [comment]
I remember the source creation coordinates are not added  to the statepoint file and this makes sense to me.

I am looking for a way of getting the openmc.Source object used in the simulation and have looked through the statepoint and summary files but couldn't see anything.

I'm keen to get the openmc.Source object from the output files as I am plotting results of the tallies and need the source.strength to know the source intensity.

Currently I get this from the model.xml but I would be keen to get it from the h5 output files

**Comment by paulromano** [comment]
Yes, I do see your point. I think the easiest way we could get something like this is to write the original XML data to the summary.h5 file instead of creating a bunch of nested HDF5 groups/datasets as we currently do (and which misses some information, like the source definition).
