### ISSUE TITLE
Cell.color and Material.color attributes

### ISSUE THREAD

**Issue by tjlaboss** [openmc-dev/openmc#2644]
## Description

Add an attribute `Cell.color`, and an attribute `Material.color`, to facilitate plotting. When plotting a universe, automatically build the `colors` dictionary using `Universe.get_all_cells()`, or `Universe.get_all_materials()`, using the Cell (or Material) colors as available. Continue to generate random colors when `color` is none.

The `color` attribute should check that the assigned value is a known named color or valid RGB or hex code.

## Alternatives

If the user wants consistent colors on each plot:

 - Require users to construct their own dictionary of cell, or material, IDs.
 - Generate a color algorithmically based on the cell / material properties.

## Compatibility

The only API change would be the addition of the new attribute.

**Comment by pshriwise** [comment]
Totally on board with this @tjlaboss. Mentioned it in #2506. Is that something you'd want to tackle?

**Comment by tjlaboss** [comment]
Happy to tackle it!

**Comment by tjlaboss** [comment]
Started messing around with this on a fork. https://github.com/tjlaboss/openmc/pull/6

**Comment by shimwell** [comment]
@tjlaboss I was just making an image and then I remembered this github issue.

I see you have made some nice progress over on https://github.com/tjlaboss/openmc/pull/6

**Comment by tjlaboss** [comment]
I forgot about this!

Yes, I will finish this and PR to to develop
