### ISSUE TITLE
No match for operator+ when compiling openmc with g++ (SUSE Linux) 7.5.0

### ISSUE THREAD

**Issue by guojian6616** [openmc-dev/openmc#2677]
## Bug Description

error: no match for ‘operator+’ (operand types are ‘std::complex<double>’ and ‘__complex__ double’)
![openmc_2](https://github.com/openmc-dev/openmc/assets/15259582/56998db7-181b-4704-8e9a-886367dd286c)

## Steps to Reproduce

I changed the following two lines and fixed the error. It seems that there is a strict grammar check in g++ (SUSE Linux) 7.5.0
![openmc_1](https://github.com/openmc-dev/openmc/assets/15259582/dc8490e9-4e60-4bb4-a2b3-e24f852d1129)

## Environment

compiler:
g++ (SUSE Linux) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by paulromano** [comment]
This should work in g++ 7.5 as long as the `-std=c++14` flag is getting passed. That is supposed to happen as a result of this line:
https://github.com/openmc-dev/openmc/blob/d21b653d32fa81b1965a9136d6a61c436502b119/CMakeLists.txt#L560

But perhaps that's not working in your case. You can run `make VERBOSE=1` to see what flags are getting passed when it is compiling source files. You may need to add a line to CMakeLists.txt as suggested [here](https://stackoverflow.com/a/59257219).

**Comment by guojian6616** [comment]
Thanks for your reply. I succeeded in compiling openmc after adding `set(CMAKE_CXX_STANDARD 14)` to the CMakeLists.txt.

**Comment by paulromano** [comment]
@guojian6616 Glad to hear you got it working. Out of curiosity, what version of cmake are you using?

**Comment by guojian6616** [comment]
cmake version 3.20.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by paulromano** [comment]
That's really strange. The `target_compile_features` line I mentioned above should definitely result in the `-std=c++14` getting added to the compile line with that version of cmake. I'm going to close this issue since you have a workaround but let me know if you run into any further problems with this.
