### ISSUE TITLE
Feature request move ```_differentiate_burnable_mats``` to model class

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2714]
## Description

I've been making use of ```CoupledOperator.deplete``` with ```diff_burnable_mats``` and am thinking it might be better to separate it from ```deplete```.

Currently I'm using the ```VolumeCalculation``` to find the volumes of all the cells in the problem.

Then I'm calling ```CoupledOperator.deplete``` with ```diff_burnable_mats``` set to True and ```diff_volume_method``` set to 'divide equally'.

This works for this simple use case which only have cells with the same material fill, however if I add another cell with a different depletable material then I get the error 
```RuntimeError: Volume not specified for depletable material with ID=2 Name=lower_vessel.```

I did think about doing a VolumeCalculation on materials but this would not work for the model as it has single materials assigned to multiple cells (hence the use of diff_burnable_mats to break these apart)

I see a need to do the diff_burnable_mats before the VolumeCalculation, and I also see a need to to the VolumeCalculation before the deplete call.

So I propose that the ```_differentiate_burnable_mats``` could be moved to the model class. Then users can diff the materials **before** doing the VolumeCalculation. Then the VolumeCalculation can be done on the model with diff materials assigned to every cell and this can be followed up by a deplete simulation

## Alternatives
Keep _differentiate_burnable_mats it where it currently lives

## Compatibility
It would be a change to the API

**Comment by shimwell** [comment]
I would be happy to make a PR if others think this is useful

**Comment by shimwell** [comment]
I've written this method that I'm keen to add to openmc.model.Model , I'm also keen to renamed it to use ```depletable ``` instead of ```burnable``` but perhaps that is a step too far.

```python
def differentiate_burnable_mats(self, diff_volume_method: str):
    """Assign distribmats for each burnable material

    .. versionadded:: 0.13.4

    Parameters
    ----------
    diff_volume_method : str
        Specifies how the volumes of the new materials should be found.
        Default is to 'divide equally' which divides the original material
        volume equally between the new materials, 'match cell' sets the
        volume of the material to volume of the cell they fill.
    """
    # Count the number of instances for each cell and material
    self.geometry.determine_paths(instances_only=True)

    # Extract all burnable materials which have multiple instances
    distribmats = set(
        [mat for mat in self.materials
            if mat.depletable and mat.num_instances > 1])

    if diff_volume_method == 'divide equally':
        for mat in distribmats:
            if mat.volume is None:
                raise RuntimeError("Volume not specified for depletable "
                                    f"material with ID={mat.id}.")
            mat.volume /= mat.num_instances

    if distribmats:
        # Assign distribmats to cells
        for cell in self.geometry.get_all_material_cells().values():
            if cell.fill in distribmats:
                mat = cell.fill
                if diff_volume_method == 'divide equally':
                    cell.fill = [mat.clone() for _ in range(cell.num_instances)]
                elif diff_volume_method == 'match cell':
                    for _ in range(cell.num_instances):
                        cell.fill = mat.clone()
                        if not cell.volume:
                            raise ValueError(
                                f"Volume of cell ID={cell.id} not specified. "
                                "Set volumes of cells prior to using "
                                "diff_volume_method='match cell'."
                            )
                        cell.fill.volume = cell.volume

    self.materials = openmc.Materials(
        self.geometry.get_all_materials().values()
    )
```

**Comment by gridley** [comment]
This is interesting. So, why do you need to split into separate materials before doing the volume calculation? It seems like you're going to lose a lot of efficiency in the volume calculation from having MC-calculated volumes for individual divvied up regions; those get sampled individually much less.

So, what if you could specify the volume that is to be assigned to each distribcell instance? Then you wouldn't need nearly as many samples in the MC volume calculation.

**Comment by shimwell** [comment]
Splitting into sperate materials is needed as I need each material to have an assigned volume for the deplete simulation.

I can also do the volume calculation on cells but the I need to loop through the cells finding the material fill and setting its volume to match the cell.

I don't quite understand the last part, sorry

The cells with common materials are not the same volume.
