### ISSUE TITLE
Move `test_evaluate_legendre` to the C++ test suite.

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#2728]
The `openmc.lib.math.evaluate_legendre` function (and maybe others in that file) exists only for the purpose of testing the C++ implementation of this function. The wrapper can be removed from `openmc/lib/math.py` and the tests should be moved to the C++ test suite.

**Comment by pshriwise** [comment]
Reopening this as it might have been inadvertently closed due to being linked in PR #2729

**Comment by paulromano** [comment]
Closed by #2955
