### ISSUE TITLE
Running jupyter twice won't give the same result

### ISSUE THREAD

**Issue by WeiWeiZong** [openmc-dev/openmc#2735]
<!--
Hi， I have some problems。
The same code is run twice to get different results, how to solve the problem？
But running python from an openmc terminal doesn’t have this problem。
I am not clear which result is credible and want to solve this problem。
I would appreciate it if you could help me。
Thanks。

**Comment by paulromano** [comment]
Closing in favor of discussion on the [discourse group](https://openmc.discourse.group/t/running-jupyter-twice-wont-give-the-same-result/3521/2)
