### ISSUE TITLE
New Feature: A One-step OpenMC HDF5 Data Generation directly from ENDF by FrendyPlus

### ISSUE THREAD

**Issue by newcomputelab** [openmc-dev/openmc#2753]
## Description
Here introduces FrendyPlus, a nuclear data processing code with Julia/Python interface based on the Frendy code by JAEA. It now integrates with the OpenMC HDF5 formatted data generation.

Open-source repository (GitLab): https://jihulab.com/newcomputelab/frendyplus

## Alternatives
Traditionally, when NJOY is used, one first uses OpenMC Python code for generation of NJOY input files templates, then switches to NJOY, and finally switches back to OpenMC HDF5 data generation Python utilities. 

Such a three-step procedure is now replaced by a one-step solution by FrendyPlus, which is simply a single Julia/Python script. Now no input files are needed,  it therefore offers a coherent experience.

## Compatibility
The Python code `build_openmc_hdf5_from_endf.py` from `https://jihulab.com/newcomputelab/frendyplus/-/blob/main/python/` have been tested to work with OpenMC Python utilities.

The Julia code `build_openmc_hdf5_from_endf.jl` from `https://jihulab.com/newcomputelab/frendyplus/-/blob/main/julia/` have been tested to work with OpenMC Python utilities through the PyCall.jl library.

**Comment by paulromano** [comment]
Thanks for letting us know about this! I've added a link to FrendyPlus in our OpenMC [ecosystem list](https://github.com/openmc-dev/openmc-ecosystem)

**Comment by newcomputelab** [comment]
Thanks and glad to experience such a rapid reply.
