### ISSUE TITLE
Histogram `stats.univariate`

### ISSUE THREAD

**Issue by jbae11** [openmc-dev/openmc#2766]
## Description
Similar to `stats.univariate.Tabular`, it'd be great to have a stats that'll sample from a binned distribution, since a lot of emission spectra are binned. The inputs will be, similar to `Tabular`,
- x (Iterable of float) – Tabulated values of the random variable
- p (Iterable of float) – Tabulated probabilities

but `len(x) == len(p)+1`, since `x` would define the upper and lower bounds of each `p` value (i.e., for `p[0]`, it represents the probability of anything between `x[0]` and `x[1]`).

Sampling will be:
1. sample which bin
2. return value that's sample uniformly within bin bounds

If such capability exists, please feel free to comment and close the issue.

**Comment by paulromano** [comment]
Unless I'm misunderstanding this, the `Tabular` class can do exactly what you want — you just need to specify `Tabular(..., interpolation='histogram')`. The only difference is that the length of `p` needs to match the length of `x` and the last value of `p` should simply be zero.

**Comment by eepeterson** [comment]
To add on to what Paul said, the input to `Tabular` needs to be the probability _density_. So if you have unevenly spaced bins you need to make sure you're passing in the probability density of the bin not the total integrated probability in that bin. MCNP has support for both I believe, but the default is integrated so that behavior is different.

**Comment by jbae11** [comment]
Just reproducing what I've learned:

If you want to model:
- 50% to be between 0 and 1
- 20% to be between 1 and 2
- 30% to be between 2 and 3

```
x = [0, 1, 2, 3] #bounds
p = [0.5, 0.2, 0.3] # probabilities
p.append(0) # add 0 at the end
s = openmc.stats.Tabular(x, p, interpolation='histogram')
```

Then you'll get:

```
import matplotlib.pyplot as plt
plt.hist(s.sample(1_000_000), bins=x)
```
![image](https://github.com/openmc-dev/openmc/assets/20345275/0476dabd-df2b-44b5-b2d1-998e5963ce81)
