### ISSUE TITLE
Underflow when computing speed for very low energy neutrons

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#2810]
If a neutron reaches a very low energy, the way the speed is calculated results in a value of exactly zero. This is due to the following line:
https://github.com/openmc-dev/openmc/blob/fb65dfd53cf8de6a360e23234bcc77f6a1d1f3c2/src/particle.cpp#L63

When the energy is very small relative to the mass (939.565 eV/c²), the denominator is effectively just `mass`, which results in an inverse gamma value of exactly one. Then, on the following line:
https://github.com/openmc-dev/openmc/blob/fb65dfd53cf8de6a360e23234bcc77f6a1d1f3c2/src/particle.cpp#L66

the value inside the sqrt becomes zero. Further on in the code, this can result in a divide-by-zero (and hence a nan), when computing time (distance / speed).

I discovered this issue when investigating a [report from a user](https://openmc.discourse.group/t/openmc-stop-running-for-shielding-calculation-in-a-specific-batch/3742).

**Comment by shimwell** [comment]
Many thanks for fixing this and thanks to @Asuthink for reporting, I think @rlbarker might also be interested in this. We have models with water and occasionally see the batches freeze after many particles

**Comment by Asureda** [comment]
Thank you both!

**Comment by paulromano** [comment]
The solution here is pretty obvious to me — when the energy of the particle is very low, we can switch to the non-relativistic formula for speed, $v=\sqrt{2E/m}$. For neutrons, underflow in the calculation of `inv_gamma` happens at an energy of 5.0e-8 eV, but in fact the relativistic formula starts to suffer from limited precision even for much higher energies. I did [a comparison of the error](https://gist.github.com/paulromano/da3b473fe3df33de94b265bdff0c7817) using the relativistic formula (with normal double precision)  and the non-relativistic formula to the relativistic formula using extended precision (100 decimal digits). The results show that we ought to be using the non-relativistic formula when neutrons are below ~1.0 eV. More generally, when the energy of the particle is smaller than $10^{-9}$ times the rest mass energy, we can switch over to the non-relativistic formula.

I'll submit a PR shortly with a fix for this.

**Comment by Asureda** [comment]
Hi Paul,
For me this solution sounds ideal! If I remember correctly, you can use the non-relativistic expression when it is less than 0.1*c. I've also seen this one, maybe you could skip the use of the root for the calculation. https://physics.stackexchange.com/questions/589970/why-is-the-kinetic-energy-for-non-relativistic-velocities-not-described-by-ke-m/595175#595175

Thanks for the solution!
