### ISSUE TITLE
Improve docstrings for Cones (and possibly others)

### ISSUE THREAD

**Issue by MicahGale** [openmc-dev/openmc#2891]
This pertains to the Cone docstrings: https://docs.openmc.org/en/stable/pythonapi/generated/openmc.Cone.html, and others.

The documentation for `openmc.Cone` lacks a quadric surface equation, and more importantly, an intuitive explanation of `r2`. `[X|Y|Z]Cone` does include the equation, but `r2` is still not super intuitive.

In general many surfaces' documentation probably needs more intuitive explanations. 

Thanks @pshriwise for making me find this.

**Comment by MicahGale** [comment]
I can do this. I just can't assign myself.

**Comment by MicahGale** [comment]
Other thought. Example figures from @gridley's work (i.e., 3D renders) might be helpful.

**Comment by gridley** [comment]
"Parameter related to the aperture" Lol what. That isn't the best! Is this the radius squared one unit along the cone's axis? I agree it'd be good to include a sketch. A 3D rendering would be nice, but perhaps convey only marginally more info!

**Comment by MicahGale** [comment]
> "Parameter related to the aperture" Lol what. That isn't the best! Is this the radius squared one unit along the cone's axis?

We found out that it is the square of the radius 1 unit along the axis. The square of the slope of the edge works quite nicely.

> A 3D rendering would be nice, but perhaps convey only marginally more info!

Touche. Time to either get good at inkscape (@tjlaboss) or scour wikimedia.

**Comment by pshriwise** [comment]
Thanks for taking this on, @MicahGale! Let's get the documentation updated for now and revisit the parameter naming.

Mention of the [`XConeOneSided`](https://github.com/openmc-dev/openmc/blob/b75ccd598e8442c97eed315b965736a31b6a67c8/openmc/model/surface_composite.py#L617) and similar composite surfaces here is probably appropriate

**Comment by MicahGale** [comment]
Good idea. Best not to make this monolithic. Should I open a separate issue to discuss the possible refactor?
