### ISSUE TITLE
Move to using black auto-formatting to enforce PEP8.

### ISSUE THREAD

**Issue by MicahGale** [openmc-dev/openmc#2904]
## Description
In the [OpenMC style guide](https://docs.openmc.org/en/latest/devguide/styleguide.html) automated formatting of C++ code is required, and PEP8 compliance is required for python, however no autoformatting is used for python AFAIK. [Black](https://black.readthedocs.io/en/stable/index.html) is a PEP8 formatting tool for python. 

Suggestion for using black:

1. [x] Add `black` as an optional dependency
2. [ ] Update style guide to require using black
3. [x] Reformat all python using `black`. This would be a large commit
4. [x] Implement a GHA test that checks if any python files need reformatting.

## Alternatives
Do nothing, and continue relying on reviewers determining if code is PEP8.

## Compatibility
No API changes would be needed. This would add an additional test, and would reformat the whole code base.

**Comment by shimwell** [comment]
Super keen to see this

Some similar discussions in this related issue https://github.com/openmc-dev/openmc/issues/2002

By the way I think Ruff is perhaps also good option to consider

**Comment by MicahGale** [comment]
Oh I didn't see that issue. I'll close this one.
