### ISSUE TITLE
Move CI to Node 20

### ISSUE THREAD

**Issue by MicahGale** [openmc-dev/openmc#2905]
## Description
[Github is deprecating support for Node 16 due to EOL](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). To deal with this is pretty simple: for the most part it just means updating to the latest version for each GHA. 

So far I have noticed the following need upgraded:
* actions/checkout@v3
* actions/setup-python@v4

## Alternatives
Do nothing, and wait for Github to stop running the CI jobs. 

I can tackle this.

**Comment by MicahGale** [comment]
Also would this be a good time to update tests to cover all maintained versions of python? i.e., Python 3.8 - 3.12

**Comment by shimwell** [comment]
Keen to see the action versions moved to the latest versions. I can offer to review that PR as I think it would be straightforward. I've noticed those warning messages github prints out.

The python versions might need doing as well but I'm less confident offering to review that one as I think it is a more involved decision. 

But if you are able to do the Ci version upgrades I guess we can get that reviewed and potentially merged in quickly.
