### ISSUE TITLE
Print warning if no natural isotopes when using `add_element`

### ISSUE THREAD

**Issue by aprilnovak** [openmc-dev/openmc#2926]
## Description
When adding nuclides to a material with `add_element`, OpenMC will silently do nothing if there are no natural nuclides of that element (e.g., plutonium). It would be nice if the user encountered a warning about this, because if the user was trying to do this in the first place they did not realize/recognize that there weren't actually any natural isotopes for that element.

## Alternatives
Print a warning if `add_element` does not add any nuclides.

## Compatibility
New feature, better user experience.

**Comment by shimwell** [comment]
Perhaps we could add to the ```element.expand``` method that is called by ```material.add_element```. We could add a check [here](https://github.com/openmc-dev/openmc/blob/9fee6534b6e873d24a4df7fe42d0bf5a988e207a/openmc/element.py#L320) in the expand method to check the length of isotopes found and print a warning ```if len(isotopes) == 0```

**Comment by cxtherineyu** [comment]
Is this issue still open? I'd love to attempt to tackle it.

**Comment by shimwell** [comment]
I think the issue is all yours @cxtherineyu thanks for volunteering

**Comment by MicahGale** [comment]
My quick two sense. A custom Warning class should be defined so warnings can be correctly filtered by the end user instead of just calling `Warnings.warn("")`. I think maybe something like: `NoNaturalIsotopesWarning`
