### ISSUE TITLE
Replace math function unit tests in Python with C++ tests

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#2943]
## Description

We have a few functions on the C++ side that have associated unit tests in Python (see `tests/unit_tests/test_math.py`) that predate our use of Catch2 for C++ unit tests. These should ideally be moved to C++ unit tests, which would obviate the need to have Python bindings for them exposed through openmc.lib.

**Comment by lhchg** [comment]
Hello paulromano, sorry to bother, I wonder if I can do this task.
If possible, may I ask a question?

I've seen python unit tests using interfaces in scipy as benchmarks for comparison, and can I use GNU Scientific Library (GSL)([https://www.gnu.org/software/gsl/]) as benchmarks for c++ unit tests?
