### ISSUE TITLE
openmc.settings.track does not always validate input

### ISSUE THREAD

**Issue by MicahGale** [openmc-dev/openmc#2984]
## Bug Description
If you set `openmc.settings.track` to a nonsensical value it can sometimes raise no errors and export the values while having no impact on what is actually exported to `xml`.

## Steps to Reproduce

MWE:

``` python
import openmc
model = openmc.Model()
model.settings.track = it.chain(*[[(j, 1, n) for n in range(1, 10_000)] for j in range(80, 101)])
model.export_to_xml()
```
The subsequent XML file then has `<track></track>`, with no warnings or errors. 

## Environment
* Openmc 0.14.0

**Comment by paulromano** [comment]
Closed by #3071
