### ISSUE TITLE
Implement plot for openmc.Region

### ISSUE THREAD

**Issue by MicahGale** [openmc-dev/openmc#3014]
## Description

While constructing geometry it is nice to verify that it is correct prior to fully defining a cell. Being able to call `plot` on an `openmc.Region` would be convenient at times. 

## Alternatives
Users can always create a dummy cell to side step this issue:

``` python
region = ...
cell = openmc.Cell(region = region)
cell.plot()
```

## Compatibility
I suspect that the plotting machinery makes a lot of assumptions about having cells. Is that correct?

**Comment by pshriwise** [comment]
I had the same thought this spring: https://github.com/openmc-dev/openmc/pull/2895
