### ISSUE TITLE
Conda provided OpenMC does not have MPI enabled

### ISSUE THREAD

**Issue by msavtchouk-pf** [openmc-dev/openmc#3017]
Following the installation guide:
https://docs.openmc.org/en/latest/quickinstall.html#installing-on-linux-mac-with-mamba-and-conda-forge
and package documentations:

https://anaconda.org/conda-forge/openmc
... Parallelism is enabled via a hybrid MPI and OpenMP programming model.
However, looking at the acquired library, I don't see any dependency on libmpi or similar.
This seems to be confirmed by practical experiments running in parallel with  mpiexec
https://docs.openmc.org/en/latest/usersguide/parallel.html#distributed-memory-parallelism-mpi
Logs don't provide any insights either (i.e. are we running in parallel or not), unfortunately

**Comment by paulromano** [comment]
The `openmc` package on conda-forge does have MPI "variants" where MPI support is enabled. To install one of these versions, run the following:
- Built against MPICH: `conda install "openmc=*=*mpi_mpich*"`
- Built against OpenMPI: `conda install "openmc=*=*mpi_openmpi*"`
