### ISSUE TITLE
Delayed neutrons are emitted promptly

### ISSUE THREAD

**Issue by gridley** [openmc-dev/openmc#3037]
## Bug Description
I have not written any test cases, but we can see that in physics.cpp's `sample_fission_neutron`, in the delayed case, the decay time is not sampled and added on to the site's time entry.

## To resolve
Sample a decay time for the precursor, and add that value to `site.time`. This alters the random number stream, so some means of preserving the prior RNG stream would be needed, too.

**Comment by ilhamv** [comment]
This is addressed in #2898 .

**Comment by gridley** [comment]
Closing b/c this is a duplicate. Doh! I will review your code after I submit my PhD thesis around August 13, Ilham! Sorry your stuff has stayed open for so long. It's not a lot of code, but I need to take a little more time to understand exactly what it's doing fully.
