### ISSUE TITLE
Automatically try "cross_sections.xml"

### ISSUE THREAD

**Issue by tjlaboss** [openmc-dev/openmc#3048]
## Description

A minor usability enhancement and a potential "Good First Issue".

The cross sections file is usually named _cross_sections.xml_. If a user sets the `OPENMC_CROSS_SECTIONS` environment variable to a directory, automatically try _cross_sections.xml_, and optionally warn the user.

Current behavior:

```
$  OPENMC_CROSS_SECTIONS=/path/to/folder/  openmc
 . . .
 Reading settings XML file...
 Reading cross sections XML file...
 ERROR: Error processing cross_sections.xml file.
```

Desired behavior:

```
$  OPENMC_CROSS_SECTIONS=/path/to/folder/  openmc
 . . .
 Reading settings XML file...
 Reading cross sections XML file...
 WARNING: Found cross sections file: /path/to/folder/cross_sections.xml
 Reading materials XML file...
 Reading geometry XML file...
 Reading U235 from /path/to/folder/U235.h5
 . . .
```

This is something that bites new users regularly, especially those coming from MCNP who are used to just setting `DATAPATH` to a directory.

## Alternatives

Just remind the user to set the environment variable to the cross sections XML 

```
$  OPENMC_CROSS_SECTIONS=/path/to/folder/  openmc
 . . .
 Reading settings XML file...
 Reading cross sections XML file...
 ERROR: "/path/to/folder/" is a directory. OPENMC_CROSS_SECTIONS must be set to a cross_sections.xml file.
```

## Compatibility

Adds something new

**Comment by paulromano** [comment]
Along philosophical lines of "explicit is better than implicit" I would be in favor of the alternative here, simply reminding the user that they need to set the environment variable to an XML file.

**Comment by ybadr16** [comment]
Just noticed this right now, I am very busy this week but i'll close the PR and issue a new PR with the alternative as soon as I can.
