### ISSUE TITLE
Type hint for geometry does not allow iterable of Cells

### ISSUE THREAD

**Issue by akoen** [openmc-dev/openmc#3079]
Small bug. `root` accepts either a Universe of an Iterable of Cells, but type checking does not allow the latter:

https://github.com/openmc-dev/openmc/blob/a5a26bb749d08618ea88e160af955890e799afe0/openmc/geometry.py#L44

**Comment by paulromano** [comment]
@johvincau can you take a crack at fixing this one?

**Comment by johvincau** [comment]
I'll take a look!
