### ISSUE TITLE
Improve description of probabilities for openmc.stats.Tabular class

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#3089]
When specifying a probability distribution using the `openmc.stats.Tabular` class, the probabilities are interpreted per unit of the  independent variable. For example, if you are specifying an energy distribution for a source, the probabilities would be given per eV. The docstring currently does not mention this but really should since this often trips up users.

Thanks to @eepeterson for pointing this out at our [TOFE workshop](https://www.ans.org/meetings/tofe2024/calendar/event-1271/).

**Comment by pshriwise** [comment]
Resolved by #3099
