### ISSUE TITLE
Rename MAX_STACK_SIZE internal variable

### ISSUE THREAD

**Issue by aprilnovak** [openmc-dev/openmc#3096]
## Description
MOOSE has a `#define MAX_STACK_SIZE` which is conflicting with OpenMC now that we are including the `photon.h` header file in Cardinal.

## Alternatives
I am not sure if there is a workaround (someone more experience in C++ can tell me if there is), but a fix is to simply rename this internal variable in OpenMC to avoid a conflict. `MAX_STACK_SIZE` appears in outward-facing documentation for MOOSE and in a greater number of places in their code base, hence I think it'd be easier to modify in OpenMC.

## Compatibility
No anticipated change.

**Comment by paulromano** [comment]
I strongly recommend you file an issue on idaholab/moose and don't believe that OpenMC should be responsible for the bad behavior of another library. Defining a generic-sounding preprocessor macro like `MAX_STACK_SIZE` could potentially affect other downstream libraries, so they really should change that to either avoid using a macro or at least have some kind of "namespace" (`MOOSE_MAX_STACK_SIZE`?).

As a workaround, would it fix things for you in Cardinal if photon.h is included before any MOOSE headers?

**Comment by aprilnovak** [comment]
Fair point, I'll bring this up with the MOOSE team.

Thanks for the idea to swap header files around, but it doesn't seem to work for our use case (unless I did something incorrectly).
