### ISSUE TITLE
Unstrucutred mesh to accept vtk file formats when library=moab

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#3210]
## Description
Currently the UnstructuredMesh accepts a damgc h5 file or a libmesh exodus file.

Currently I'm making use of UnstructuredMesh with ```library='moab'``` and passing in a mesh in h5 format.

I'm making the mesh in gmsh and writing a vtk file, then I'm using moab to load the vtk file and write out a h5 file. This seams like an inefficient process to me and I would be keen if the UnstructuredMesh class was able to accept the vtk file directly. As PyMoab is able to read a vtk and convert to h5 I suspect that MOAB can also take a vtk file directly.

I think allowing vtk files as a input format for UnstructuredMesh when library=='moab' will be enabling for a few mesh workflows as not many support h5 file writing.

## Alternatives
continue to convert the vtk to h5 with pymoab before sending it to openmc. I fear this will slow down for larger meshes. Another alternative is that I make use of the exodus format more and move to libmesh. However this is not currently included in the conda install and compiling with autotools can take a long time.

## Compatibility
Will the enhancement compatibility with meshers

**Comment by pshriwise** [comment]
I was about the say the same @makeclean. Thanks!

I, like you, @shimwell confirmed that this does in fact work. I'll keep an eye out for the PR with the documentation update -- thanks for being willing to update that!
