### ISSUE TITLE
Photon transport

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#431]
OpenMC has thus far been primarily a reactor-oriented code. Photon transport is important in reactor energy deposition and depletion calculations as it causes some fraction of fission energy to be redistributed away from a local fission site. As a first step towards being able to do coupled neutron/photon calculations, we first need to implement photon transport. Having the ability to simulate photon transport will also open up opportunities for use in non-reactor applications, e.g. medical physics calculations.

Fortunately, photons being neutral particles behave much like neutrons, so most of the existing logic in the code can be maintained. The major additions would be being able to handle reading in photon cross section data, performing photon physics (Compton scattering, Rayleigh scattering, photoelectric effect, pair production, relaxation of excited atomic nuclei, thick-target bremsstrahlung approximation), and extending tally functionality. I've already begun work on this (read: I have a working prototype with everything except TTB) and I've chosen to rely on ENDF files natively rather than ACE photon data because of limitations in the latter. This works by using a few Python scripts to generate an HDF5 library of photon data.

**Comment by smharper** [comment]
I'm curious how you plan to handle photon particle banks.  Will we be picking photons from the same fission bank that we get each generation's neutrons from?  Will they instead be considered secondary particles that we transport after we finish each neutron that ends in a fission?  Are fission product gammas going to be handled differently than those born in radiative capture?

**Comment by paulromano** [comment]
Photons generated from neutron-induced or photon-induced reactions will simply be put in the secondary bank and transported once the primary particle has reached the end of its life. In principle, gammas produced from fission will be handled no differently than those from radiative capture. However, do note that handling the yield of photons from fission properly will require some thought. Prompt fission gammas are straightforward since they generally have tabulated yields and spectra, so we can just sample from those. For delayed gammas, there is no "total spectrum" in the same way that there is one for prompt gammas -- if you really wanted to know it, you'd have to compute it using information in the ENDF decay sublibraries.

To be clear - the first step on the path to coupled neutron/photon transport is simply just the capability to transport photons alone, which is what I am targeting for the 0.8 release. Photon production from neutron reactions will come along after that.

**Comment by paulromano** [comment]
Photon transport is now in the develop branch with the merging of #1023. I'll create separate issues for remaining issues.
