### ISSUE TITLE
Improve complex cell performance by using AST

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#476]
When determining whether a cell contains a particle, there are two cases currently -- simple (cell region defined only by intersection of half-spaces) and complex (anything else). The simple case exists as a performance optimization, because in that case it's very easy to use short-circuit logic to minimize the number of surface evaluations needed. For example, if you have the following cell:

``` xml
<surface id="1" type="x-plane" coeffs="-5" />
<surface id="2" type="x-plane" coeffs="5" />
<surface id="3" type="y-plane" coeffs="-5" />
<surface id="4" type="y-plane" coeffs="5" />
<cell id="1" material="1" region="1 -2 3 -4" />
```

and the particle is at (-6, 0, 0), then as soon as you realize that it is on the wrong side of surface 1, you know it's not in the cell. In general, this isn't true for complex cells, and so the entire boolean expression has to be evaluated. However, this is only because we store the expression in reverse Polish notation. If instead the cell region expression were stored as an abstract syntax tree, it would be possible to short-circuit because some branches of the tree wouldn't need to be evaluated. Let's say you had a cell defined as:

``` xml
<cell id="1" region="-1 | (3 -4)" />
```

The abstract syntax tree looks something like

```
Union
  |--> -1
  |--> Intersection
           |--> 3
           |--> 4
```

In this case, if the particle is found to be on the negative side of surface 1, there is no reason to evaluate the intersection branch of the tree because we already know the overall expression will evaluate to true.

**Comment by rzehumat** [comment]
Hello @paulromano , is this issue still open? If so, would it be possible to volunteer here?

**Comment by paulromano** [comment]
Indirectly, yes. With PR #2178, we now do short circuiting on complex cells, which makes a huge difference for complex geometries. It doesn't use an AST but achieves the same thing, so I'll go ahead and close this. @myerspat and I have [a paper](https://doi.org/10.1016/j.cad.2024.103803) on this that was published recently.

In any case, thanks for offering to volunteer! We can find something else for you to work on if you're interested in making more contributions.
