### ISSUE TITLE
Incorrect behavior for bound H in HCH2

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#505]
It appears that something is wrong in the physics for bound H in HCH2. I ran a fixed source problem with a 30 cm sphere of H in HCH2 with an isotropic 14.1 MeV source in the center of the sphere and then tallied the flux with both MCNP and OpenMC. I get the following:
![hch2](https://cloud.githubusercontent.com/assets/743095/11272213/d35625c8-8e90-11e5-94e3-f7ccbfcd3d17.png)

If MCNP is correct, then something is definitely wrong with the thermal treatment for HCH2 in OpenMC. I originally noticed this when comparing OpenMC and MCNP results on the ICSBEP mix-comp-therm-012 benchmark, which are hundreds of pcm apart.

@makeclean you'll probably recognize the description of the problem. Did you ever do any cross-code comparisons with S(a,b) tables?

**Comment by paulromano** [comment]
Looks like this was at least a partial scare. Apparently I was not plotting the right data for MCNP. Here is a comparison of the current develop branch versus MCNP5 1.51 along with the relative error compared to the uncertainty on the MCNP5 result.
![hch2_actual](https://cloud.githubusercontent.com/assets/743095/11279271/1d41a422-8eb5-11e5-9f9e-4d211e1c2089.png)
![hch2_error](https://cloud.githubusercontent.com/assets/743095/11279273/1e7c317c-8eb5-11e5-8982-e9ff3bdacd6c.png)
I did the same for H in H2O and it looks just as good. Now, I say "partial" scare because upon looking into things in a little more detail, it looks like there is a new treatment in MCNP6 whereby the discrete energies are "smeared" to prevent some of the weird artifacts in the energy spectrum. Once I get MCNP6 running, I'll do comparisons with an updated treatment in OpenMC.

**Comment by nelsonag** [comment]
Is this new MCNP6 feature any different than what I put in for issue #211 / pr #233?

**Comment by paulromano** [comment]
It is actually. The new treatment is for when the data in the ACE file is still given as discrete outgoing energies; the seems purpose of the "smearing" is to eliminate the ugly non-physical spikes in the energy spectrum so that it looks closer to what you'd get with the continuous treatment.

**Comment by paulromano** [comment]
We adopted the discrete angle smearing in #777. Using @amandalund's nifty [validation](https://github.com/openmc-dev/validation) scripts, I compared H in CH2 on our develop branch and everything looks great:
![H1-c_H_in_CH2-1 0e+06eV-293 6K](https://user-images.githubusercontent.com/743095/56304596-144f1000-6104-11e9-9d18-a2a46878f8a9.png)
