### ISSUE TITLE
How to build OpenMC projet file（*.sln） using CMAKE tool for IDE VS2013/IVF2013 ？

### ISSUE THREAD

**Issue by chzping** [openmc-dev/openmc#747]
Hi, Dr paulromano: 
     Could you help me and tell me the detailed procedures to build OpenMC projet file（*.sln） using CMAKE tool for IDE VS2013/IVF2013 ? Using the latest version source code （0.8.0）with sole HDF5 output format. The key problem is how to configure the HDF5 environment？ I have already build successfully the VS2013 project file with source code version 0.7.0 （with traditional output format, not HDF5 only）
contacting email： chzping@yeah.net
Thank you so much. 
Dr. Zhenping CHEN.

**Comment by paulromano** [comment]
@chzping I have never used Visual Studio so unfortunately can't offer you any words of advice. I believe all of our other developers are also using Linux or Mac.

**Comment by chzping** [comment]
@paulromano OK. Thanks.

**Comment by paulromano** [comment]
Closing in favor of #1243
