### ISSUE TITLE
Update "openmc-statepoint-3d" script with latest PyAPI

### ISSUE THREAD

**Issue by felixletkemann** [openmc-dev/openmc#815]
When I try to execute 
`openmc-statepoint-3d statepoint.100.h5 -o output.silo`
I get an error like this: 
`Traceback (most recent call last):
  File "/home/felix/Entwicklung/anaconda3/bin/openmc-statepoint-3d", line 393, in <module>
    main(args[0],options)
  File "/home/felix/Entwicklung/anaconda3/bin/openmc-statepoint-3d", line 123, in main
    sp.read_results()
AttributeError: 'StatePoint' object has no attribute 'read_results'
1 felix@apfelhund ..openmc/examples/xml/pincell_multigroup (git)-[master] %  `

I opened the editor end read the relevant code. As said in the error message, there is not read_results method in statepoint.py. I don't get how this piece of code can work for someone else? Or is this method defined somewhere else? 
Searching the web for the problem didn't get me any fix for this.

**Comment by wbinventor** [comment]
@felixletkemann it appears that the "openmc-statepoint-3d" script is far out-of-date - it hasn't been updated since late 2015. The OpenMC Python API has changed dramatically since then and as a result, it's not surprising that this script no longer works. In addition, the script isn't included in our test suite so it has been easy to overlook as we continue to develop the Fortran and Python codebase. I've changed the title on this issue to reflect this, though I'm not sure that we will prioritize updating the script to make it work. You are very welcome to update it yourself and submit it as a PR if you so wish!

**Comment by felixletkemann** [comment]
Thanks for the fast answer!
Is there any replacement for openmc-statepoint-3d ? Maybe it should be changed in the documentation as well since this is the only thing i found in the docs in order to visualize the results.

**Comment by wbinventor** [comment]
At present there is no replacement; either the existing script must be revised or a new one must be developed from scratch based upon the latest version of the PyAPI (which is well documented [here](http://openmc.readthedocs.io/en/stable/pythonapi/index.html)). Very good point about the documentation being out-of-date with regards to this script. I believe there is some motivation to update some of our documentation soon (as mentioned on #791 by @paulromano), so this issue should be taken care of at that time.

**Comment by felixletkemann** [comment]
Okay, thank you very much for the information! Maybe I will look into the documentation and give it a try. :)

**Comment by felixletkemann** [comment]
There is another thing missing in the documentation: It is no possible to find anything about length units. In the geometry.xml there are coeff-values but there is no information if this is meter, inch, cm oder anything else. Its simply not possible to create an object of a distinct size with this information missing. Maybe someone can add it to the documentation?

**Comment by paulromano** [comment]
@felixletkemann Thanks for pointing that out. I'll add that to the documentation. For reference, length is in centimeters, energy is in eV, and time is in seconds.

**Comment by paulromano** [comment]
You'll now find information about [physical units](http://openmc.readthedocs.io/en/latest/usersguide/input.html#physical-units) in the user's guide.

As far as the statepoint-3d script, I was taking a look at it and it is *really* outdated. I don't even know if it makes sense to refactor it; rather it needs to be completely rewritten. For now, I'm considering removing the script and the mention of it in the documentation so as not to confuse users. At some point, we'll get around to adding a replacement.

**Comment by felixletkemann** [comment]
Awesome that you fixed that! :) 
I just got used to use openmc without plotting anything, but it would still be nice to do so. Unfortunately I didn't get good enough at this to be able to rewrite this script. 
And when I got good enough at this I guess the first thing to do for me would not be to fix this script but to write something that allows me to convert CAD files to geometry.xml files.

**Comment by Shimwell** [comment]
Hi all, @makeclean @pshriwise  and myself are working on a new openmc-statepoint-3d script that can make vtk files for visualizing your 3d mesh tally. It is getting closer to being complete but I just wanted to mention it here in case anyone is still keen on the feature. I guess there will be a PR on the develop branch to include this soon

**Comment by paulromano** [comment]
This script got removed at some point, so this issue can be closed.
