### ISSUE TITLE
Surface neighbour lists differ depending on how complex cell is described

### ISSUE THREAD

**Issue by GiudGiud** [openmc-dev/openmc#898]
In the case of nested cubes (sample input below), defining the outer cube with '~' the complement operator (to act on the inner cube) or with a few union operators '|' (to act on half-spaces defining the inner cube), the inner cubes'  surfaces' neighbour lists differ. 

In one, the outer cube cell is listed as a pos neighbour, and in the other, as a neg neighbour. (in the lists of neighbours, surf%neighbor_pos and surf%neighbor_neg). Technically, the outer cube is actually on both sides of the surface. For now, the preferable neighbour list are with '|'.

This creates a bug for surface filters in surface tallies, introduced in #893 , as the p % surface is reset to 0 when the next cell is not found among the neighbours. Then the event of crossing the surface is not tallied, because p%surface doesn't match the surface filter bin.

Having the neighbour list be complete and consistent could help with performance, as it avoids a search through all cells. For cells that are on both sides of surfaces used to define them, it could mean having the cell in both neighbor_neg and neighbor_pos

Example:
```
x2 = openmc.XPlane(surface_id=2, x0=-7)
x3 = openmc.XPlane(surface_id=3, x0=-4)
x4 = openmc.XPlane(surface_id=4, x0=4)
x5 = openmc.XPlane(surface_id=5, x0=7)
y2 = openmc.YPlane(surface_id=12, y0=-7)
y3 = openmc.YPlane(surface_id=13, y0=-4)
y4 = openmc.YPlane(surface_id=14, y0=4)
y5 = openmc.YPlane(surface_id=15, y0=7)
z2 = openmc.ZPlane(surface_id=22, z0=-7)
z3 = openmc.ZPlane(surface_id=23, z0=-4)
z4 = openmc.ZPlane(surface_id=24, z0=4)
z5 = openmc.ZPlane(surface_id=25, z0=7)

# Instantiate Cells
inner_box = openmc.Cell(cell_id=1, name='inner box')
outer_box = openmc.Cell(cell_id=2, name='outer box')

# Use each set of six planes to create solid cube regions.
inner_cube            = +x3 & -x4 & +y3 & -y4 & +z3 & -z4
middle_cube           = +x2 & -x5 & +y2 & -y5 & +z2 & -z5
outside_inner_cube    = -x3 | +x4 | -y3 | +y4 | -z3 | +z4

# Use surface half-spaces to define regions
inner_box.region = inner_cube
middle_box.region = middle_cube & outside_inner_cube     # **1st way** 
middle_box.region = middle_cube & ~inner_cube                # **2nd way** 
```
Modify neighbor_lists() in geometry.f90 to see the lists.

**Comment by smharper** [comment]
Looks like this issue was closed by #1140.  When I run this geometry, I find that the new neighbor list implementation correctly allows cells to be their own neighbors, and the `cross_surface` method doesn't lose particles (which would cause `p->surface_` to be reset---affecting tally results).
