### ISSUE TITLE
Dimensional inconsistency for SLBW competitive width terms

### ISSUE THREAD

**Issue by apmccartney** [openmc-dev/openmc#907]
The neutron wave number factor seems to be missing in the channel radius ratio (`rhoc`) and scattering radius ratio (`rhochat`) terms for the competitive width branch of `reconstruct_slbw`. See lines 302 and 303 of [openmc/data/reconstruct.pyx](https://github.com/mit-crpg/openmc/blob/1008ab8ea1509e17151a96b535c57b4f64831831/openmc/data/reconstruct.pyx#L302)

**Comment by paulromano** [comment]
Nice find @apmccartney. Do you know of any evaluations that have non-zero competitive widths for SLBW/MLBW?

**Comment by apmccartney** [comment]
Not yet, but I'm planning to build up a test suite as part the resonance reconstruction effort. Assuming I can find such an evaluation, it will be available there. I'll ping you if I come across one before then.

**Comment by paulromano** [comment]
Yeah, I hadn't run into one either which is probably part of the reason this slipped through. I'd welcome a PR if you want "credit" for finding the bug. If you have better things to do though, I can put in a fix :)

**Comment by apmccartney** [comment]
I'll post a fix sometime this weekend =)

**Comment by Iwan-Zotow** [comment]
math for wavenumber in reconstruct.pyx seems to be wrong. Code looks ok though
