### ISSUE TITLE
binary search for a value out-of-range

### ISSUE THREAD

**Issue by walshjon** [openmc-dev/openmc#969]
It may be worth re-thinking having the binary search return -1 for a value that is outside the range of supplied values.  I don't know if this is being used as an error code for some other host code, but developer's (at least this one) can run into trouble when calling the search in the standalone OpenMC.  The issue I ran into occurs when doing a binary search on a subset of a larger vector of values.  To illustrate:

E = E ! some energy that is actually higher than I think it should be
ia = binary_search(Es(i_min:i_max), i_max - i_min + 1, E) ! search the range that I think I should search (returns -1 because I was wrong about E being within the range of supplied Es)
ib = my_func(ia) ! some new index that depends on ia being >= i_min and <= i_max is now screwed up because the binary search returned -1 instead of an error

I seem to recall it being a fatal_error to search for a value outside the range of supplied values in the past.  Things may have changed, but I only remember hitting that error when I was doing something I didn't want to be doing (i.e., I only hit it when there was a bug in my new code)

**Comment by cjosey** [comment]
I believe that this change was my fault and was merged in PR #466.  Removing those bounds checks, along with a few other tweaks, improved the overall simulation performance roughly 5-10%.

If you really want it back, one "good for everyone" possibility is to ``#ifdef`` the error check if debug is enabled.

**Comment by walshjon** [comment]
Right, if we're checking anyway, returning the upper or lower bound seems at least as good as -1, probably better (unless -1 is being used elsewhere).

**Comment by paulromano** [comment]
`binary_search` is gone after #1154 is merged, so this issue will not be relevant anymore
