### ISSUE TITLE
Possible to extract matplotlib graph/plot elements from openmc.Plot().from_geometry()?

### ISSUE THREAD

**Issue by SterlingButters** [openmc-dev/openmc#974]
Just wondering if it is possible to do the above in order to plot the geometry using a different data visualization API such as matplotlib?

**Comment by paulromano** [comment]
Not currently but that's a great idea! We'll look into adding that for the next release.

**Comment by SterlingButters** [comment]
Getting close to doing it externally (from OpenMC), in the interface I am building... Though I don't plan to do anything with geometries that aren't x, y, z or cylindrical planes.

<img width="871" alt="screen shot 2018-03-18 at 1 15 19 pm" src="https://user-images.githubusercontent.com/22737286/37569338-d0247c30-2aae-11e8-839a-ddbcf561da9e.png">

**Comment by paulromano** [comment]
I actually have a branch with the changes needed in order to get the actual image object (as opposed to just displaying the image). I'll be submitting a pull request this week with the change.

**Comment by SterlingButters** [comment]
May I ask what attributes will be available under the image object? I’m asking because the interface I’m building may require more/something-other-than what the pull request will provide. Still a useful feature though!

**Comment by paulromano** [comment]
For a geometry plot, you'd get an `IPython.display.Image` object. What information do you actually need for the interface you're building?

**Comment by SterlingButters** [comment]
If you look in the picture I uploaded you can actually see that it tells me the cell-location on mouse-hover. In addition, I can get it to tell me what “universe” is selected on mouse hover. The other plot that I have (not posted) graphs the regions in the cell and it will tell me what region the mouse-hover is in. It is supposed to fill the region once the user clicks a button though I think there is some bug or something with Dash that it preventing the “update”.

**Comment by SterlingButters** [comment]
So in terms of attributes, say for an assembly plot, I’d be looking for number of cells (x/y directions), x/y dimensions of assembly, and outer radius of fuel pin/equivalent.

**Comment by paulromano** [comment]
How are you actually rendering the plot? Right now, plots in OpenMC are just rasterized images -- it loops over a bunch of (x,y) coordinates and figures out what cell is present at a given location and then uses that to produce a bitmap (first a PPM file which is then converted to a PNG).

**Comment by SterlingButters** [comment]
Right now I am using the Plotly API for (heatmap) plotting which takes the outer radius of the ZCylinder object and loops that over the user defined number of cells in each direction. A change is also accounted for in space between cells via a change in assembly x/y .dimension

**Comment by SterlingButters** [comment]
And I don’t understand how I would do this (yet) for more complex plane configurations. Maybe that’ll come in a later release. Or if I can get a collaborator lol

**Comment by paulromano** [comment]
Out of curiosity--are you working on this as part of a particular project?

**Comment by SterlingButters** [comment]
No haha I’m just bored

**Comment by paulromano** [comment]
This was implemented in #985.
